### PR TITLE
Repalce deprecated headers of tf2_sensor_msgs

### PR DESCRIPTION
**Pull request by wep21**
### Related PR
https://github.com/ros-planning/navigation2/pull/2342

### CODE REVIEW

**Comment by ruffsl** [comment]
We'll rerun CI tomorrow after the dockerhub image updates. That'll sort out the missing commits with colcon cache. I built the image manually first, so the image included commits from my PR that have since been squashed.

**Comment by wep21** [comment]
Note: header of `tf2_geometry_msgs` should be fixed if `geometry2` in docker is latest.
https://github.com/ros2/geometry2/pull/418

**Review by SteveMacenski — APPROVED** [review]
Will merge after Galactic branch off and release

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/2350 supercedes, it replaces all of the tf2 hpp files, not just 1

**Pull request closed without merging**
