### PR TITLE
Export nav2_bt_navigator library and dependencies

### PR DESCRIPTION
**Pull request by MarcoLm993**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | |

---

## Description of contribution in a few bullet points
* Export the nav2_bt_navigator library to allow inheritance from it

## Description of documentation updates required from your changes

---

### CODE REVIEW

**Comment by doisyg** [comment]
I was thinking about a PR in this sense too, same for `nav2_behavior_tree` libraries (`BtActionNode` is very convenient)

**Review by SteveMacenski — APPROVED** [review]
@MarcoLm993 please submit one for `main` as well, we do not accept PRs only to a specific distribution

**Comment by SteveMacenski** [comment]
@doisyg I'd merge that too - just to `main` :wink

**Comment by MarcoLm993** [comment]
> @MarcoLm993 please submit one for `main` as well, we do not accept PRs only to a specific distribution

Just opened another PR to the main branch: https://github.com/ros-planning/navigation2/pull/2213

**Pull request merged**
