### PR TITLE
Convert all wall timers and wall rates to ROS clock respecting rates and timers

### PR DESCRIPTION
**Pull request by SteveMacenski**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3303|
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation of turtlebot |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

* Removes all wall clocks and timers to using the Node's clock
* So in simulation time, uses ROS time. Else, uses a steady clock

## Description of documentation updates required from your changes

* Migration guide note

---

## Future work that may be required in bullet points

* Finish with costmap2dROS node

#### For Maintainers: 
- [x] Check that any new parameters added are updated in navigation.ros.org
- [x] Check that any significant change is added to the migration guide
- [x] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [x] Check that any new functions have Doxygen added
- [x] Check that any new features have test coverage
- [x] Check that any new plugins is added to the plugins page
- [x] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by Benjamin-Tan** [comment]
Will this be backported to humble?

**Comment by SteveMacenski** [comment]
I just took a look and it looks like the auto-backport failed on this but in reviewing the code nothing here breaks ABI/API policy so yes it could be backported. Are you open to submitting a PR to do that? Happy to review/merge and would be a great contribution for Humble users from you!

**Comment by Benjamin-Tan** [comment]
Sure, how would you suggest to do a backport PR to humble branch? Manually bring these changes onto the humble branch?

**Comment by SteveMacenski** [comment]
Use `git log` or the GitHub UI to find the commit hash in `main` to the work you want, then run `git cherry-pick <hash>` on the `humble` branch. Resolve appropriate conflicts and then submit a new PR! :smile:

**Pull request merged**
