### PR TITLE
line-buffer stdout

### PR DESCRIPTION
**Pull request by rotu**
When launched with launch_ros, executables can withhold logging output at log level "INFO" until termination.
So RCLCPP_WARN will get output immediately, but you won't see RCLCPP_INFO until the program terminates.
Explicitly make stdout line-buffered so this doesn't happen.

### CODE REVIEW

**Comment by mjeronimo** [comment]
Something to be aware of is that you can set RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED in the environment in order to force the ROS2 logging system to be line buffered:

$ export RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED=1

I wonder if there are performance implications of making the proposed changes in each of the source files, to always force line buffering. At least with the environment variable there is an option to not use line buffering (for example, running on a physical robot and perhaps not interactively viewing logs).

**Comment by rotu** [comment]
Thanks, @mjeronimo! I didn't know that. With that in mind, this PR seems less necessary.

Yet still that default behavior seems pathological. At the very least the model launch file in `nav2_bringup` should set that flag.

**Comment by mjeronimo** [comment]
Yes, I totally agree about the pathological and unexpected behavior. I was very suprised when I first encountered this recently. I also agree about setting this option from the launch scripts if possible. 

@crdelsey @mkhansen-intel What do you guys think?

**Comment by crdelsey** [comment]
We could just add it to our bringup docs as an alternative to changing the code.

**Comment by rotu** [comment]
> We could just add it to our bringup docs as an alternative to changing the code.

I don't think it's a good idea to inflict this on users who didn't RTFM or forgot to run a step before calling ros2 launch. The fewer manual steps the better - that's the whole point of a launch file.

**Comment by crdelsey** [comment]
Fair enough. I don't see anything in the upstream PRs that indicate they preferred unbuffered output for some reason. We just need to figure out a way to do it cleanly now.

**Comment by mjeronimo** [comment]
I recommend just setting it from the launch script(s), somewhere in the generate_launch_description function:

    os.environ["RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED"] = "1"

It could also be a command-line option to allow setting this differently, but that might be overkill.

**Comment by rotu** [comment]
You can ignore the git history here. I screwed up with some rebasing changes and just wound up moving this to a new.

**Pull request closed without merging**
