### PR TITLE
removed unused .gitignore files

### PR DESCRIPTION
**Pull request by mkhansen-intel**
Fixes issue #56 
Removes unused .gitignore files

### CODE REVIEW

**Comment by mjeronimo** [comment]
No, we aren't going to need these as .gitignore files. They are just there so that a file is present (and hence the directory shows up in the hiearchy). If you like, we can use a different filename, such as .TODO or something. The files are present to encourange the correct directory structure as the hiearchy is filled out.

**Comment by mkhansen-intel** [comment]
Take a look at my branch here: https://github.com/mkhansen-intel/navigation2/tree/rm_gitignore/src

You'll see that all the main folders are still there (navigation, planning, etc.) We're just pruning the unpopulated leaf folders. There is still a clear hierarchy in place. Also, when people submit PRs for code review, we can ensure they put new code in the right place then. So I don't see a need for these placeholders anymore. They have served their purpose in my opinion, and they confuse new users.

**Comment by mjeronimo** [comment]
Yeah, I understand but disagree. The basic difference is: do we have a template that we fill out, or build incrementally. I prefer the former as it demonstrates the directories and files that will be populated.

**Comment by mkhansen-intel** [comment]
OK, just to document our stand-up discussion this morning, we agreed that we'll delete these files but add an outline of the directory structure we want to the contributing section of the documentation [README ](https://github.com/mkhansen-intel/navigation2/blob/master/doc/README.md) file. Mike's going to make that change and push it to the branch as part of this PR.

**Comment by mjeronimo** [comment]
The outline of the directory structure won't be needed not that we're going to reorganize according the Steve's PR, so I went ahead and integrated this and will close this issue.

**Pull request merged**
