### PR TITLE
Enable reloading BT xml file with same name

### PR DESCRIPTION
**Pull request by huemerj**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | None |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Inhouse AGV & Gazebo |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points
- Current state: In the current implementation of the `BtActionServer`, a new BT is not loaded if its xml name is the same as the current one. This means that if you want to change and then test a BT xml file (while keeping the same filename), you need to restart the action server each time the file changes. 

- This PR: Adds a boolean parameter `always_reload_bt_xml` (defaults to `false`) to decide if a new BT should always be loaded, even if the xml names are the same. This allows keeping the action server running while changing/developing the xml file.
 

## Description of documentation updates required from your changes

- Might be necessary to add the new parameter `always_reload_bt_xml` to the Behavior-Tree Navigator docs.

---

## Future work that may be required in bullet points

- Would be nice to backport this PR to Humble/Iron.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
Rename to `always_reload_bt_xml` and add to the Nav2 configuration / migration guides and this LGTM

**Comment by huemerj** [comment]
> Rename to `always_reload_bt_xml` and add to the Nav2 configuration / migration guides and this LGTM
> 
> Please heed the DCO bot (sign commits `-s`)

Done. https://github.com/ros-planning/navigation.ros.org/pull/534

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@huemerj please heed the DCO bot, all commits need to be signed, then I can merge this. If you click on the CI job, it'll give you instructions about how to adjust your previous commits 

I'm going to merge this but I'd like to note for future onlookers of this: This is useful for the context @huemerj brings it up in. If you're using this because you have a BT that isn't properly resetting its state with your custom BT nodes, so using this to hard reset everything, I highly suggest fixing your underlying issues which could be causing other issues on the blackboard which could possibly persist in some cases. This may seem like an easy solution, but I suggest spending a little bit of time to look into the proper solution, especially in robotics where small mistakes in odd cases can cause real headaches.

**Comment by huemerj** [comment]
@SteveMacenski Would be nice if you could please backport this to Humble/Iron.

**Comment by SteveMacenski** [comment]
Next release cycle it will be

**Comment by christophfroehlich** [comment]
> Next release cycle it will be

@SteveMacenski May I ping you again and ask for a backport?

**Comment by SteveMacenski** [comment]
If it wasn't backported (which it looks like it could have been?) it was due to huge merge conflicts on cherry picking. If you'd like this in iron, please submit a PR against `iron` making these changes manually and I can merge that and have it released in the next sync. 

Sorry about the manual-ness, the automated tools must have failed badly enough that I judged it not possible at the time.

**Pull request merged**
