### PR TITLE
including install forgotten costmap 2d cloud publisher and removing lifecycle nodes from debug instruments

### PR DESCRIPTION
**Pull request by SteveMacenski**
Somehow we missed the install rule for the cloud publisher.

How were folks visualizing the voxel layer cloud to know how it works? (serious question)

There's also no reason for the marker or cloud publisher to be lifecycle, they're just quick scripts taking a voxelgrid message and converting types for rviz visualization (or maybe we should make an rviz plugin that does that for you in the application?). 

Closer to fully describe parameters in param file, especially ones that are really important to have correct. Included TB3 URDF needed for depth processing. Turtlebot ws no longer required if we just have this.

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
You have at least 2 unrelated changes here, can you split into 2 PRs? One for adding the costmap2d cloud and another for including the TB3 model?

**Comment by SteveMacenski** [comment]
Sure, fair enough

**Comment by SteveMacenski** [comment]
@mkhansen-intel done

**Comment by SteveMacenski** [comment]
@orduno can you give this a quick look?

**Pull request merged**
