### PR TITLE
Replace deprecated launch params

### LINKED ISSUE #1775: Replace launch 'node_name' and 'node_executable' with 'name' and 'executable'
They are now deprecated in master and it causes warnings on runtime use.

### PR DESCRIPTION
**Pull request by naiveHobo**
Signed-off-by: Sarthak Mittal <sarthakmittal2608@gmail.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | closes  #1775 |
| Primary OS tested on | Ubuntu 18.04 |

---

## Description of contribution in a few bullet points

* Replace launch 'node_name', 'node_executable', and 'node_namespace' with 'name', 'executable', and 'namespace'

### CODE REVIEW

**Comment by SteveMacenski** [comment]
```
[tester_node-13] Traceback (most recent call last):
[tester_node-13]   File "/opt/overlay_ws/src/navigation2/nav2_system_tests/src/system/tester_node.py", line 332, in <module>
[tester_node-13]     main()
[tester_node-13]   File "/opt/overlay_ws/src/navigation2/nav2_system_tests/src/system/tester_node.py", line 307, in main
[tester_node-13]     testers = get_testers(args)
[tester_node-13]   File "/opt/overlay_ws/src/navigation2/nav2_system_tests/src/system/tester_node.py", line 266, in get_testers
[tester_node-13]     tester = NavTester(
[tester_node-13]   File "/opt/overlay_ws/src/navigation2/nav2_system_tests/src/system/tester_node.py", line 46, in __init__
[tester_node-13]     super().__init__(name='nav2_tester', namespace=namespace)
[tester_node-13] TypeError: __init__() got an unexpected keyword argument 'name'
```

I think you shouldn't have changed the internal python stuff - I think just the launch functions changed.

**Comment by naiveHobo** [comment]
Ah, yes sorry. I assumed these were inheriting from launch_ros Node class. I'll revert those changes.

**Comment by SteveMacenski** [comment]
I think that'll make it work - ping me when it passes, thanks for the quick turn around. I'm battling an annoying issue with my backup test that I didn't get when I wrote the wait test .... fun times....

**Comment by naiveHobo** [comment]
> I'm battling an annoying issue with my backup test that I didn't get when I wrote the wait test .... fun times....

Haha, yes I noticed :laughing:

**Comment by naiveHobo** [comment]
@SteveMacenski good to go!

**Comment by SteveMacenski** [comment]
-0.01% coverage 

**_### REJECTED_**

**Pull request merged**
