### PR TITLE
Null-terminate string to dirname function

### PR DESCRIPTION
**Pull request by rotu**
possibly responsible for heisenbug https://github.com/ros-planning/navigation2/issues/1079#issuecomment-526782592

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Weird question, but why not `image_path = yaml_name.substr(0, myString.size()-5);` to kill the `.yaml` extension? I suppose some folks name using `yml` but the automated saver/loader if consistent can enforce that standard

**Comment by rotu** [comment]
@SteveMacenski I think you misunderstand the code. We're not stripping the extension - we're stripping the file name. If the image is a relative path (usually is), we resolve it relative to the parent directory of the yaml file.

**Comment by SteveMacenski** [comment]
Ah ok, I think there's an issue here, you're assuming that the yaml and the image file are in the same directory. In the past that filename in the yaml could be a full or relative path, ei. `image.png` for next to it or `/home/steve/.../.../image.png` to load an image in another path than the yaml file. 

My understanding of what you have written here is that you're stripping the yaml file for a directory and inputting the image name at the end of it, which only works for relative paths.

**Comment by rotu** [comment]
@SteveMacenski Look at the guard above it, which handles the absolute case: `if (image_file_name[0] != '/')`

This code was pretty much carried forward from legacy code, I just switched out the call to `strdup` and forgot to null terminate the result.

**Comment by SteveMacenski** [comment]
Ah got it, thanks for clarifying

**Comment by SteveMacenski** [comment]
Anyhow, you've passed CI and its a stupid small change, I think you're safe to ship it

**Pull request merged**
