### PR TITLE
Adds missing commas so default plugin names are not stuck together

### PR DESCRIPTION
**Pull request by aaronchongth**
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | [(add tickets here #1)](https://github.com/ros-planning/navigation2/issues/3092) |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation |

---

## Description of contribution in a few bullet points

Added missing commas to ensure default plugin lib names are accurate.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by aaronchongth** [comment]
@jwallace42 Thanks!

**Review by jwallace42 — APPROVED** [review]

**Comment by jwallace42** [comment]
Looks like you will need to get @SteveMacenski to approve but it LGTM. He gets back from vacation in a couple of weeks so we will have to wait :).

**Review by jwallace42 — APPROVED** [review]

**Comment by jwallace42** [comment]
@AlexeyMerzlyakov are you able to approve pr's?

**Review by SteveMacenski — APPROVED** [review]
Thanks kindly!

**Comment by SteveMacenski** [comment]
@AlexeyMerzlyakov should be able to approve / merge PRs like this

**Comment by AlexeyMerzlyakov** [comment]
@jwallace42, my apologies. I was in PTO, and was not able to check this PR.

**Comment by SteveMacenski** [comment]
No worries!

**Pull request merged**
