### PR TITLE
Updated the specific releases/versions instead of referring to ros2.

### PR DESCRIPTION
**Pull request by wilcobonestroo**
The references in the `ros2_dependencies.repos` are updated to the specific versions that were used for that build.

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #1863  |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | n/a |

---

## Description of contribution in a few bullet points

As suggested by the [comment](https://github.com/ros-planning/navigation2/issues/1863#issuecomment-660264308) from @SteveMacenski at , the dependencies.repos file is updated so that it contains the specific versions after they were released.

| Repo | Version |
|----|--------|
| BehaviorTree | 3.5.1 |
| angles | 1.12.3 |
| gazebo_ros_pkgs | eloquent |
| image_common | eloquent |
| vision_opencv | eloquent |

## Description of documentation updates required from your changes

There are no updates needed for documentation. This PR is not for current development.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
The PR builder has every integration test failing with this PR. It would be fine if a couple did but every single one points to a potential problem this introduced.

**Comment by SteveMacenski** [comment]
@wilcobonestroo any updates?

**Comment by wilcobonestroo** [comment]
I am still trying to understand and figure out the CircleCI errors. Tomorrow I will work on it.

**Comment by wilcobonestroo** [comment]
It seems it tries to build this eloquent branch in an Ubuntu Focal (20.04) version. How can I make sure CircleCI uses Ubuntu Bionic (18.04)?

**Comment by SteveMacenski** [comment]
Pay attention to the PR builder from the build farm - that's what I'm looking at to say that all the tests fail

**Comment by wilcobonestroo** [comment]
I was trying to solve `ci/circleci: release_build`. From the logs I can see that it tries to build the eloquent branch in Ubuntu Focal and that does not work. Am I correct that the CI is only for the updates in latest/current branch and that I can discard them for this PR?

I assume that you are referring to the test errors in the `Epr__navigation2__ubuntu_bionic_amd64` with "PR builder from the build farm". Is that correct? The details show that the build was successful, but that a large number of tests did fail. I don't have experience with tests in Colcon yet, so I will dive into that and try to run it on my own machine.

**Comment by SteveMacenski** [comment]
OK. @wilcobonestroo these just run in the docker containers in the repo so you can build them yourself from the eloquent branch. I'd also sanity check yourself by reverting your changes and seeing if it passes then in case this isn't from your PR but some other sync in eloquent.

**Comment by wilcobonestroo** [comment]
The failing tests were already there before I made the changes in this PR. However, I started with 14 failing tests and managed to solve 8 of them. The remaining failing tests are more difficult. I also see some strange behavior where a test sometimes passes and sometimes fails. E.g. running the same command twice:
```
ros@vm:~/pr_nav2$ colcon test --packages-select nav2_util
Starting >>> nav2_util
Finished <<< nav2_util [13.3s]            

Summary: 1 package finished [13.6s]
ros@vm:~/pr_nav2$ colcon test --packages-select nav2_util
Starting >>> nav2_util
--- stderr: nav2_util                     
Errors while running CTest
---
Finished <<< nav2_util [12.8s]	[ with test failures ]
                      
Summary: 1 package finished [13.0s]
  1 package had stderr output: nav2_util
  1 package had test failures: nav2_util
ros@vm:~/pr_nav2$
```
I don't completely get what the goal of the test is. I will check if the remaining failing tests are already solved/fixed in the foxy-devel branch and I can apply those things to this eloquent-devel PR.

**Comment by wilcobonestroo** [comment]
The failing test from `nav2_util` seems related to this one: https://github.com/ros2/rclcpp/issues/861

**Comment by SteveMacenski** [comment]
Which test within nav2_util is failing? You can find out with colcon test-result --verbose. Eloquent and prior did have some flaky tests. I'm OK if a couple of the system tests fail in CI because of that but all of them failing means something is critically wrong

**Comment by wilcobonestroo** [comment]
It was in test 12: test_actions / test_simple_action_preemption_after_succeeded. It has really nasty behavior. Sometimes it runs fine and sometimes it fails. I now only have issues with `nav2_system_tests` on my machine. I will try to solve those.

**Comment by SteveMacenski** [comment]
The system tests are the only ones im concerned about

**Comment by SteveMacenski** [comment]
You should be able to run all this locally through docker or on your machine - I think trying to develop through CI for this case is going to take you much longer and ultimately you may not find the issue because its only in CI or something and works OK locally. 

If things didn't work before your changes, then we can probably merge this in with your original changes to the repos file as long as the repos file matches the rosdistro/eloquent.yaml release versions / branches. I don't want you spinning your wheels on this if you didn't break anything and things work when you play with it locally.

**Comment by wilcobonestroo** [comment]
I have noticed some really inconsistent test behavior. For example, when I run tests separately (with `--packages-select`) they succeed and when I run them as a batch (`colcon test`) they fail. Moreover, some tests sometimes fail and sometimes succeed. I think it would be nice when tests "always" uncover errors and not sometimes.

I also would like to create the identical environment as on the build server. Is there a description of how to do that? I see that the build server uses the Navigation 2 docker image. It would be nice if I can use the same commands to get that environment locally.

**Comment by wilcobonestroo** [comment]
> If things didn't work before your changes, then we can probably merge this in with your original changes to the repos file as long as the repos file matches the rosdistro/eloquent.yaml release versions / branches. I don't want you spinning your wheels on this if you didn't break anything and things work when you play with it locally.

The change of the repos did not break anything. The tests were already failing. I think it makes sense to split the issues. This PR was originally only about the repos and that is the first commit.

The commits after the first one are about making the tests work again, but that is another issue. I should learn some more about testing in ROS before refactoring all tests :)

**Comment by SteveMacenski** [comment]
Look at rosdistro/eloquent.yaml and see what the versions for each of these are. Copy them over here and let me know when CI is done on that. I'll merge. We can then move on.

**Comment by wilcobonestroo** [comment]
Hi Steve, I am not sure if I understand what you mean. The versions were in the first commit of this PR: https://github.com/ros-planning/navigation2/pull/1881/commits/c6d2fcfb0a126bf430bc8dd134e0ae4943263ffc. The CI built was number 43 (http://build.ros2.org/job/Epr__navigation2__ubuntu_bionic_amd64/43/) and there were no problems except for the tests. However those were already there in built number 42.

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/blob/master/eloquent/distribution.yaml

This contains the released versions of everything. They will also contain branches. Grab those and lets use them in this file and we can merge with just those changes since its clearly working for people working with eloquent on their machines.

**Comment by wilcobonestroo** [comment]
Maybe we can than close this one. On my machine, it is still downloading behaviortree version 3.1.1-1. I used the following entry in the .repos file.
```
  behaviortree_cpp_v3:
    type: git
    url: https://github.com/BehaviorTree/behaviortree_cpp_v3-release.git
    version: release/eloquent/behaviortree_cpp_v3/3.5.1-1
```
However, I am able to build it using the instructions described [here](https://github.com/ros-planning/navigation2/issues/1863#issuecomment-660958343).

**Pull request closed without merging**
