### PR TITLE
Refactor rclcpp::executor::FutureReturnCode deprecation

### PR DESCRIPTION
**Pull request by shivaang12**
---

## Description of contribution in a few bullet points
* Remove deprecated rclcpp::executor::FutureReturnCode to rclcpp::FutureReturnCode

### CODE REVIEW

**Comment by shivaang12** [comment]
I think this will have to wait till we shift to new ros2 nightly.

**Comment by SteveMacenski** [comment]
We are running nightly master builds in CI.

**Comment by shivaang12** [comment]
I've recently build ros2 from source and I cannot pass this error without making this change. I am wondering why it's failing?

**Comment by SteveMacenski** [comment]
I did verify that that is a change between eloquent and master branch in `rclcpp`. I'm not exactly sure why that is, it takes a little while for the caches to update but that change looks like it happened about 2 weeks ago. It might be related to the Foxy freeze, maybe master builds have paused to be uploaded? 

Can you update the PR name to be more descriptive. I think it might be hanging around for awhile until we sort it out

**Comment by SteveMacenski** [comment]
Lets spin this puppy again

**Comment by SteveMacenski** [comment]
Given other PRs built fine a few hours ago, I doubt anything has changed.

**Comment by SteveMacenski** [comment]
@shivaang12 try adding some extraneous info in `ros2_dependencies.repos` to break the cache. I believe that's what https://github.com/ros-planning/navigation2/blob/master/.circleci/config.yml#L203 is doing. 

Add anything, doesn't really matter. A comment, a new package, etc

**Comment by shivaang12** [comment]
okay

**Comment by shivaang12** [comment]
Let me know if this will work

**Comment by SteveMacenski** [comment]
```
Cleaning Underlay
Input data is not valid yaml format: while parsing a block mapping
  in "<stdin>", line 2, column 3
expected <block end>, but found '<block mapping start>'
  in "<stdin>", line 22, column 4

```

well... it did _something_ :robot: but you added an extra space so it was invalid yaml in the `ompl` line

**Comment by shivaang12** [comment]
Oh, it was one space indent.

**Comment by SteveMacenski** [comment]
Wow, OMPL takes a long time to build. I guess I shouldn't be surprised with all those templates

**Comment by SteveMacenski** [comment]
I really hope after all of that building it doesnt fail from 

```
]0;colcon build [9/16 done] [4 ongoing]Finished <<< image_common [2.89s]
]0;colcon build [10/16 done] [3 ongoing][Processing: behaviortree_cpp_v3, gazebo_msgs, ompl]
--- stderr: behaviortree_cpp_v3
In file included from /opt/underlay_ws/src/BehaviorTree.CPP/src/action_node.cpp:166:0:
/opt/underlay_ws/src/BehaviorTree.CPP/3rdparty/coroutine/coroutine.h: In function ‘void coroutine::yield()’:
/opt/underlay_ws/src/BehaviorTree.CPP/3rdparty/coroutine/coroutine.h:367:11: warning: unused variable ‘stack_top’ [-Wunused-variable]
     char* stack_top = routine->stack + ordinator.stack_size;
           ^~~~~~~~~
/opt/underlay_ws/src/BehaviorTree.CPP/3rdparty/coroutine/coroutine.h:368:10: warning: unused variable ‘stack_bottom’ [-Wunused-variable]
     char stack_bottom = 0;
          ^~~~~~~~~~~~
/opt/underlay_ws/src/BehaviorTree.CPP/tools/bt_log_cat.cpp: In function ‘int main(int, char**)’:
/opt/underlay_ws/src/BehaviorTree.CPP/tools/bt_log_cat.cpp:27:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(buffer.data(), sizeof(char), length, file);
     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
```

**Comment by shivaang12** [comment]
Well it didn't work. How can we remove the cache?

**Comment by SteveMacenski** [comment]
Didn't work. 

@ruffsl I think I know the answer but just need to verify - we added an extra package to break the cache and it rebuild the underlay workspace, that clearly didn't have a rebuild of ROS2 master. From looking at the results, it seems like ROS2 nightly comes from the docker image in stage 1 of circleCI. 

That's generated from an automated build from dockerhub every time we push to master but since the `BT.CPP` and `gazebo11` issue, those builds are failing so we're not seeing latest ROS2. 

Is that correct? 

Therefore steps to fix are 
- Fix gazebo11 and BT.CPP
- Let dockerhub rebuild an image when we push that to master
- rerun jobs

Correct?

**Comment by SteveMacenski** [comment]
@shivaang12 I think step 1 is to fix the issues with BT.CPP and update to the latest master branch per #1686 . Unfortunately, I'm not going to be in front of a computer for tonight (on phone). That would unblock Ruffin's PR that if it works would then probably stand everything else back up in a day or so.

**Comment by shivaang12** [comment]
Sounds good!

**Comment by SteveMacenski** [comment]
I keep going through this back and forth of forgetting how our CI is set up. I think it would be really nice if @ruffsl would write up a page for navigation.ros.org about how the CI system works. Some reference for people working with it (like me) that can't remember things apparently or new people that will eventually need to get up to speed about this because of the bus test.

**Comment by SteveMacenski** [comment]
@shivaang12 remove OMPL and rerun after these 2 build succeed

https://hub.docker.com/repository/registry-1.docker.io/rosplanning/navigation2/builds/b42c2d4c-625f-46a9-90df-bc240981afe9

https://hub.docker.com/repository/registry-1.docker.io/rosplanning/navigation2/builds/cc40b985-b302-4d5f-b0b5-492805bff625

It should work then

**Comment by SteveMacenski** [comment]
First build succeeded, second in progress

**Comment by shivaang12** [comment]
Somehow I can't see if the build has ended. Let me know that status so I will push the changes.

**Comment by SteveMacenski** [comment]
https://hub.docker.com/repository/registry-1.docker.io/rosplanning/navigation2/builds/cc40b985-b302-4d5f-b0b5-492805bff625

You can't see this link?

**Comment by shivaang12** [comment]
This takes me to homepage https://hub.docker.com/r/rosplanning/navigation2

**Comment by ruffsl** [comment]
@shivaang12 , please reminder to rebase onto current master to ensure your using the latest changes to the CI and codebase.

**Comment by SteveMacenski** [comment]
@shivaang12 its ready

**Comment by shivaang12** [comment]
I will do it in the morning, if that's okay?

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/issues/1717

This has some test issues with cppcheck now, which is interesting

**Pull request merged**
