### PR TITLE
Add dynamic parameters do Costmap2DROS

### PR DESCRIPTION
**Pull request by doisyg**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/956  and https://github.com/ros-planning/navigation2/issues/2566 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Wyca Elodie |

---

## Description of contribution in a few bullet points

As discussed https://github.com/ros-planning/navigation2/issues/2566, this PR makes dynamic the parameters that were in ros1: https://github.com/ros-planning/navigation/blob/noetic-devel/costmap_2d/cfg/Costmap2D.cfg

Only `update_frequency` was left out as it requires `std::thread * map_update_thread_` to be reinit, but this can be debated.
I tried to reproduce the priority order of what sets the footprint : from topic > footprint string > robot_radius, hence the messy change callback.
The `std::vector<geometry_msgs::msg::Point> ` from the topic needs to be saved when it is set in order to be able to apply a changing `footprint_padding` on it.

Side notes not directly related to this PR:

- With the current implementation, applying padding on a round footprint distorts it to a rounded square
- Default value of `footprint_padding` is 0.0 in the code and 0.01 in the documentation

#### For Maintainers: 
- [x] Check that any new parameters added are updated in navigation.ros.org
- [x] Check that any significant change is added to the migration guide
- [x] Check that any new functions have Doxygen added
- [x] Check that any new features have test coverage
- [x] Check that any new plugins is added to the plugins page
- [x] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by doisyg** [comment]
>  All of the costmap_2d parameters that could be changed (non-plugin)?

For completeness, list of parameters that are currently NOT dynamic (they could theoritically be made dynamic too but it requires some re-initialization of objects):

- `always_send_full_costmap` -> needs costmap_publisher_ reinit
- `global_frame` -> needs layered_costmap_  costmap_publisher_ tf_buffer_ reinit
- `lethal_cost_threshold` , `map_topic` , `observation_sources` , `trinary_costmap` , `unknown_cost_value` , `clearable_layers` -> not used in costmap2DROS itself but in pluggins
- `plugins` -> needs layered_costmap_ reinit
- `filters` -> needs layered_costmap_ reinit
- `robot_base_frame` -> needs tf_buffer_ reinit
- `rolling_window` -> needs layered_costmap_ reinit
- `track_unknown_space` -> needs layered_costmap_ reinit

As for tests, any suggestions ?

**Comment by SteveMacenski** [comment]
@mergifyio refresh

**Comment by SteveMacenski** [comment]
Feel free to ignore the mergify stuff, I was just testing that everything was set up correctly. It now is

**Comment by moritzboeker** [comment]
@doisyg and @SteveMacenski , thank you for implementing your solution! This is very useful since I was looking for a way to dynamically set the footprint of our articulated robot comprising a front and rear carriage with an articulated joint in between them. Unfortunately, I am forced to use ROS melodic or noetic. So I started to take your changes and implement them into a **ROS1 navigation fork, but realized that I cannot depend on rcl_interfaces. Is there a way to get this running also on ROS1?**

Kind regards,
Moritz

**Pull request merged**
