### PR TITLE
[WIP] Adding components of ROS1 base_local_planner needed by TEB.

### PR DESCRIPTION
**Pull request by yathartha3**
---

## Basic Info

| Info | Ported a subset of base_local_planner that the TEB local planner would require. |
| ------ | ----------- |

---

## Description of contribution in a few bullet points

---

### CODE REVIEW

**Comment by orduno** [comment]
@yathartha3 The coding style changed a bit from ROS1. You can run the linters to see the places that need to be fixed:

```
$ ament_cpplint
$ ament_uncrustify
```

**Comment by SteveMacenski** [comment]
I see that you added the nav core local planner abstract class, that probably shouldn't be in this package. 

See discussion here about the interfaces or plugins: https://github.com/ros-planning/navigation2/issues/943

**Comment by mkhansen-intel** [comment]
@yathartha3 - I believe this is still work in progress, so adding the [WIP] to the title for now. When it's ready for review, please remove that

**Comment by mkhansen-intel** [comment]
Any update? Is this still WIP or should we close it?

**Comment by yathartha3** [comment]
Closing it since the other interface PR that I am working on will address this issue.

**Pull request closed without merging**
