### PR TITLE
nav2_bringup reorder

### PR DESCRIPTION
**Pull request by sathak93**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | (Ubuntu) |
| Robotic platform tested on |  gazebo simulation of turtlebot |

---

## Description of contribution in a few bullet points
This is follow  up PR to PR<https://github.com/ros-planning/navigation2/pull/2473>. 
It reorder the nav2_bringup directory since Nav2_gazebo_spawner  pkg in it was deleted <https://github.com/ros-planning/navigation2/pull/2473#discussion_r691751336>

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
```
]0;colcon build [21/23 done] [0 ongoing]Starting >>> nav2_bringup
--- stderr: nav2_bringup
CMake Error: The source directory "/opt/overlay_ws/src/navigation2/nav2_bringup/bringup" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [Makefile:222: cmake_check_build_system] Error 1
---
Failed   <<< nav2_bringup [0.58s, exited with code 2]
```

Not quite building?

**Comment by sathak93** [comment]
does the ci clear the cache of nav2_bringup pkg build and install

**Comment by sathak93** [comment]
@SteveMacenski  colcon clean does not remove the build and install of invalid pkgs see before  <https://app.circleci.com/pipelines/github/ros-planning/navigation2/5901/workflows/ac3ab9c9-c19a-433c-8a49-afa51242ea7e/jobs/21667?invite=true&invite=true#step-117-136> and after the clean command
<https://app.circleci.com/pipelines/github/ros-planning/navigation2/5901/workflows/ac3ab9c9-c19a-433c-8a49-afa51242ea7e/jobs/21667?invite=true#step-117-153>

**Comment by SteveMacenski** [comment]
@ruffsl is that your assessment too from these results? If so, when we merge this into nav2 will things come back up OK?

**Comment by ruffsl** [comment]
On the road, so can't debug, but one can always force flush the cash by ratcheting up the version number. E.g. just change `v1` to `v2` in the cache key string in the config file:

https://github.com/ros-planning/navigation2/blob/4e45ad3675efb1c8f64419d6129f6af1d41529ce/.circleci/config.yml#L36

https://github.com/ros-planning/navigation2/blob/4e45ad3675efb1c8f64419d6129f6af1d41529ce/.circleci/config.yml#L61

**Comment by SteveMacenski** [comment]
@sathak93 please try

**Comment by sathak93** [comment]
changing v1 to v2  doesn't work it builds all pkgs but produce same error.
I found a way, 
by adding ``--cmake-clean-cache`` arg to colcon build, it builds successfully the invalid pkgs.
is it okay ?

**Comment by SteveMacenski** [comment]
That proves the point that it works to my satisfaction. I'm just wondering now how to merge this in to keep CI up and running. Please remove that clean cache and leave it in that state. I'll merge it. If it fails after merging over, then I'll clean the caches and then have it rerun a couple of times before removing it again.

**Comment by ruffsl** [comment]
> changing v1 to v2 doesn't work it builds all pkgs but produce same error.

You need to find and replace all the v1 cache key strings, including the fallback cache key to restore from. Looks like this was missed. Others wise it would it could still restore from an older cache, which looks to have happened from that commit's job log.

https://github.com/ros-planning/navigation2/blob/2ffd46b0868084d1b1ff31080b3ad1b7821c6a3f/.circleci/config.yml#L41

**Comment by ruffsl** [comment]
> by adding --cmake-clean-cache arg to colcon build, it builds successfully the invalid pkgs.
is it okay ?

This does provide more sterile builds, but nurfs or nullifies much of point in our caching the colcon build workspace, for cmake packages at least.

**Comment by SteveMacenski** [comment]
@sathak93 please follow Ruffin's suggestions

**Comment by ruffsl** [comment]
Remember, given the v2 cache for this PR was cross contaminated from the v1 cache, you'd then need to bump the cache key again, now to v3, to bust the cache completely.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Fabulous, thank you!

**Pull request merged**
