### PR TITLE
Add unit tests for spin, wait, and backup action BT nodes

### PR DESCRIPTION
**Pull request by naiveHobo**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #1810 |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | TurtleBot3 Gazebo Simulation |

---

## Description of contribution in a few bullet points

* Add header files for spin, wait, backup BT action nodes
* Add unit tests for spin, wait, backup BT action nodes

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@naiveHobo looks like a warning went to error https://github.com/colcon/colcon-mixin/commit/14905bd934512363b9b842b4be43e21907314720. @ruffsl did you set those up or was that someone at intel? Its not immediately clear to me why those are necessary.

**Comment by SteveMacenski** [comment]
No issue merging this, but it seems to only test the IO and setting of recovery variables rather than actually seeing if it correctly spun the robot. We have the integration level recovery tests that I think are fine as testing that, but I think that leaves a gap of BT -> recoveries test (we have recovery server call tests, and now BT tests, but nothing that does BT -> recovery server). 

How hard would it be to test that the action server is actually called with some valid response in these unit tests? I don't think you need to test that it actually completes the task successfully, but test that it actually calls the server with the goal and gets a "cool, goal accepted" on the `send_goal_async` to make sure the connection between the BT and recovery servers is working

**Comment by naiveHobo** [comment]
Do you think that is something we should do in a unit test? I've written these unit tests such that a BT node can be tested against a minimal action server. The BT node communicates with this test server and there are checks to ensure if the action server successfully received a goal in addition to the tests for IO and recovery variables.

It shouldn't be too difficult to add the tests you mentioned but I'm not sure if that's something we should do in a unit test. We would want the unit test to be independent of the other units in the system, right? I'm all for adding BT -> recovery server checks but I think that should be done somewhere else (though not sure where exactly).

**Comment by SteveMacenski** [comment]
Thats a good question. You have the backup/spin/wait https://github.com/ros-planning/navigation2/pull/1831/files#diff-e4ef1e9df119c9976142e4c88298bfddR26 test servers, as long as the string action topic name is the same as the `nav2_recoveries` action topic names, then it should be good to go. I think we just need to add a test then to add a bool for "received request" to just explicitly show it connected to the test action servers. 

Keeping these in line with the actual `nav2_recoveries` is important then

**Comment by SteveMacenski** [comment]
Also this would be nice to get in before the first release of foxy, but not required

**Comment by SteveMacenski** [comment]
Rebase / pull in master to fix the mixin CI problem. Fixed in #1835

**Comment by naiveHobo** [comment]
> I think we just need to add a test then to add a bool for "received request" to just explicitly show it connected to the test action servers.

The lines below have check if the current goal being executed by the server is in fact the goal sent by the BT node by checking the individual field values. Should be enough right?
https://github.com/ros-planning/navigation2/pull/1831/files#diff-e4ef1e9df119c9976142e4c88298bfddR148-R150

> as long as the string action topic name is the same as the nav2_recoveries action topic names

Yup, the test action server advertise the same action names as `recoveries_server`

**Comment by SteveMacenski** [comment]
yes that works, thanks.

I think you just need to get CI passing (at least 1 of the test builds needs to pass, but ideally both so that we can get a coverage report)

**Pull request merged**
