### PR TITLE
add namespaced params sample

### PR DESCRIPTION
**Pull request by yzprofile**
make sample launch file easy to use.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@yzprofile can you give us context behind this PR? You're removing capability to have 2 robots with 2 separate configurations. I'm not sure why that's beneficial.

**Comment by yzprofile** [comment]
these sample parms files are used for new users of nav2 like me, 
and i think make it can start more than 2 robots easily is more important than only start two different robots.

**Comment by SteveMacenski** [comment]
This is example code for multi-robot use-cases anyhow. My feeling is that this is actually taking away functionality rather than enabling more since there's then not an example for how to run  heterogeneous robot fleets. 

@shivaang12 what do you think?

**Comment by shivaang12** [comment]
I think I agree with @SteveMacenski here. Well for starters, these params file are here to exemplify possible implementation but don't let them stop you to achieve some thing more simple or complex. But as long as I understand, this example of multi-robot shows a way to run multi-robot heterogeneously just as @SteveMacenski said.

One way this approach can help someone (whether or not he/she is new to multi-robot) is by writing some documentation of it under multi-robot system, which I don't think we have yet.

@SteveMacenski do you think we should add multi-robot thing to our documentation? It will help some folks who are willing to contribute in the area.

Again, I am not saying your approach is wrong but replacing it with some other approach is what I have problem with.

**Comment by SteveMacenski** [comment]
Agreed, I think this PR should be closed. If you need to run `N` of the same robots, you're totally welcome to make a new package with your own launch files. `nav2_bringup` is a toy example of how to use the navigation2 stack and applied to a common platform. For your own company / platform, its common to have a `<robot name>_bringup` package that contains these things but for your specific application.

There isn't any docs on the multirobot bringup / navigation as far as I know. Its not been a focus and I more or less agree that it shouldn't be (plenty of fleet management systems around, using something like that we propose isn't good for hardware, but great for simulation / testing). I'd be fine with adding some docs on running the multi-robot examples.

**Comment by yzprofile** [comment]
thanks for your reply, pr closed.

and thanks for your great work!

**Comment by SteveMacenski** [comment]
Thanks for the PR, sorry it didn't work out!

**Pull request closed without merging**
