### PR TITLE
Fix costmap publishing loop

### PR DESCRIPTION
**Pull request by crdelsey**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |   |
| Primary OS tested on | Ubuntu |
| Primary platform tested on | gazebo simulation of Turtlebot |

--- 

## Description of contribution in a few bullet points

* The code to determine when to publish a new costmap was using ROS time. This caused the costmap to never get published if we changed to sim_time after the `last_publish_` value had been set. I changed it use std::chrono time instead. This way, the costmap always gets published at a regular interval, even if the simulation is paused, which IMHO is desirable.
* Fixed a bug in the logic that checks whether there are subscribers to the costmap topic before publishing. The logic was reversed.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
> the costmap always gets published at a regular interval, even if the simulation is paused

**Comment by crdelsey** [comment]
> This would defeat the purpose then of pausing a simulation and make the results for debugging not longer deterministic as its publishing without marching forward in time.

The `rclcpp::Rate` object uses `std::chrono` clocks under the hood rather than `rclcpp::Clock`. The result is that these types of loops throughout the ROS code base continue processing, even though the simulator is paused. I expect the intention is that they should make no substantive change to the state of the system if no new work has come in.

I believe that this was the case in ROS 1 as well.

So the question is "does publishing the current costmap count as a substantive change to the system?"

For debugging, it seemed useful to me to be able to pause the simulation, go over to rviz and enable the display of the costmap. Because it gets published even when the simulation is stopped, rviz would be able to display it right away.

If there are other nodes in the system that take action based on costmap messages, then maybe this is not the right way to deal with the problem.

I believe this wasn't an issue in ROS 1 because you were supposed to have the `use_sim_time` variable set before the node came up. You weren't supposed to change it at run time, but that seems less convenient under ROS 2.

**Comment by crdelsey** [comment]
This needs unit tests still. I'll add them before merging.

**Comment by SteveMacenski** [comment]
I think the work flow changes to support not doing this would be simple: just have rviz open before you pause the simulation so that the displays are still up. I can't think of many situations where an edge case would occur that something made a human stop a simulation, then need to open rviz to debug because they couldn't have had it open in the first place.

There are frequent times when actions are taken based off of costmap updates for other higher-level primitives to do work for behaviors, safety, and inferences, which will make the state of a robotic system non-deterministic in simulations if we stop, or the simulation clock runs at a different speed (which is common). Any differentiation between real world and simulation results should be avoided at nearly all costs. 

Moreover, this node (and package, and stack) makes use of rclcpp Time [throughout it](https://github.com/ros-planning/navigation2/blob/e81a5d0be21fa84a5a9639833dec3f3cc24c2d80/nav2_costmap_2d/src/costmap_2d_publisher.cpp#L148), so in mixing them, its sending mixed signals and what's appropriate where and why, overall making the maintainability of the node harder and greatly more nuanced. 

Your comment on rclcpp::Rate is a fair point, but you're not replacing any code in this PR that was at one point represented as a rclcpp::Rate object. I would also expect that if there were reasons to change back to rclcpp::Clock, that might still happen as ROS2 is still under active development.

**Comment by crdelsey** [comment]
All good points. I guess I was thinking that since the loop ran independently of the simulation clock, then the action it was taking should as well, but that's not generally the case in ROS. I'll fix.

**Pull request merged**
