### PR TITLE
robot_base_frame parameter for planner_server

### PR DESCRIPTION
**Pull request by daisukes**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation |

---

## Description of contribution in a few bullet points

- this allows you to change the link where the planned path starts

---

## Future work that may be required in bullet points

N/A

### CODE REVIEW

**Comment by SteveMacenski** [comment]
The PR fails all of the integration tests - there's something wrong here causing the robot not to navigate

**Comment by daisukes** [comment]
Sorry, it was my bad. Now it works.

**Comment by SteveMacenski** [comment]
Can you update the planner server to call the costmap2d get robot pose method (like the controller server does)? It will have the same effect without adding a new parameter because it’ll get it from the costmap.

**Comment by daisukes** [comment]
Thank you for the suggestion!

**Comment by SteveMacenski** [comment]
Thanks for your attention to detail!

**Pull request merged**
