### PR TITLE
Smart to navfn

### PR DESCRIPTION
**Pull request by SteveMacenski**
Addressing https://github.com/ros-planning/navigation2/issues/325

### CODE REVIEW

**Comment by orduno** [comment]
@SteveMacenski I've added some comments to #325. Can we discuss this before merging?

**Comment by SteveMacenski** [comment]
And that package could be logically named smart_planner :-)

**Comment by orduno** [comment]
> Lets talk on that ticket, but it seems like most folks are aligned unless I’m misinterpreting someone’s position.
> 
> I think this goes in line with not over optimizing early- once there’s interest/effort being put in to develop new planners to live inside this stack, we can always circle back and change names and organization. I’m all for a general planning package with many implementations, however if you’d like to orchestrate them together, that by itself is novel enough to be spun out as a separate package even if the server executables all live in one

OK, you've convinced me. Approved!

**Comment by mkhansen-intel** [comment]
@SteveMacenski - I was about to merge this but I guess it has merge conflicts, can you resolve and re-push? Thanks

**Comment by SteveMacenski** [comment]
Oh sorry, this slipped my mind. I'll handle this in the morning.

**Comment by SteveMacenski** [comment]
@mkhansen-intel done. Letting CI run and then merging.

**Pull request merged**
