### PR TITLE
Waypoint nav markers

### PR DESCRIPTION
**Pull request by fmrico**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #803  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation of Tally |

---

## Description of contribution in a few bullet points

* I added visualization markers to show the waypoints in the navigation waypoint mode

---

## Future work that may be required in bullet points

* I think we could use a .dae model (I used a road cone), but I tried and I got some error opening the file. Maybe I could try again in the future

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @SteveMacenski,

I reverted the undesired changes in rviz config. I don't know why rviz2 makes these changes. I had to revert it editing manually the file.

Best

**Comment by mlherd** [comment]
waypoints

@fmrico I just tested it. I have two questions.

Should the waypoint markers start from 1 instead of 0?
Would it look nicer if we get rid of wp_ and use only numbers on the green markers?

Otherwise, it looks good to me.

**Comment by fmrico** [comment]
Hi @mlherd 

It can start from 1, and remove the "wp_", of course.

Give me a minute

**Comment by SteveMacenski** [comment]
@mlherd @fmrico 

I'd prefer the `wp_X`, it helps make it clear its a waypoint when you have a bunch of markers around.

I think starting at `1` though is fine

**Comment by fmrico** [comment]
A @SteveMacenski suggested, I maintained the `wp_X` , but now it starts from 1.

**Comment by mlherd** [comment]
@fmrico @SteveMacenski 
> I'd prefer the `wp_X`, it helps make it clear its a waypoint when you have a bunch of markers around.

The user needs to clicks on the waypoint mode button before placing any markers, so in my opinion, they should know it is a waypoint.

I am not sure if it is beyond the scope of this PR but, Can we use the same marker for Navigation2 goal as well?

**Comment by SteveMacenski** [comment]
> The user needs to clicks on the waypoint mode button before placing any markers, so in my opinion, they should know it is a waypoint.

You're assuming they don't have anything else on the screen. Its possible there are other markers from other programs on screen

**Comment by fmrico** [comment]
> Congrats, for your first PR! 👍

@mlherd Thanks very much!! :)

I will use the same marker for the Navigation2 goal button in another PR. I prefer to close this one.

Thank you very much for your help, and especially to @SteveMacenski for developing the waypoints mode navigation.

**Comment by SteveMacenski** [comment]
No worries @fmrico 

Looking forward to your preempt on approach PR :wink:

**Pull request merged**
