### PR TITLE
Fix InflationLayer resource locking problem (#1931)

### PR DESCRIPTION
**Pull request by daisukes**
I resubmit this PR because of the merging issue.
https://github.com/ros-planning/navigation2/pull/1936#issuecomment-675092401

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #1931  |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | tb3 |

---

## Description of contribution in a few bullet points

* fix resource locking problem of InflationLayer

## Description of documentation updates required from your changes

N/A

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Pull in main, you have the tree too close to master, its pulling the wrong images

**Comment by SteveMacenski** [comment]
@daisukes please pull in main, we need some of these to pass to merge it ;-)

**Comment by daisukes** [comment]
@SteveMacenski 
Is this what you mean?

**Comment by SteveMacenski** [comment]
Well... you forced pushed so I can't see what you did, but basically I was asking you to pull in origin main to get all the latest changes. Your force push might have been from a rebase which has the same effect. Just needing to get things to be up to date on your branch.

**Pull request merged**
