### PR TITLE
Update CI for ROS2 Foxy

### PR DESCRIPTION
**Pull request by ruffsl**
Fixes: https://github.com/ros-planning/navigation2/issues/1627

### CODE REVIEW

**Comment by ruffsl** [comment]
Looks like navigation2 is using some deprecated API from `BehaviorTree.CPP`. That'll need fixing to make the CI pass, or we can revert to the previous used tag and ignore declarations (not suggested).

``` Dockerfile
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build \
      --symlink-install \
      --mixin $UNDERLAY_MIXINS \
      --cmake-args \
        --no-warn-unused-cli \
        -DCMAKE_CXX_FLAGS=" \
          -Wno-deprecated-declarations"
```



<details>

```Step 33/36 : RUN . $UNDERLAY_WS/install/setup.sh &&     colcon build       --symlink-install       --mixin $OVERLAY_MIXINS     || touch build_failed &&     if [ -f build_failed ] && [ -n "$FAIL_ON_BUILD_FAILURE" ]; then       exit 1;     fi
 ---> Running in 0dd8bbd22e7f
[connext_cmake_module] Warning: The location at which Connext was found when the workspace was built [[/opt/rti.com/rti_connext_dds-5.3.1]] does not point to a valid directory, and the NDDSHOME environment variable has not been set. Support for Connext will not be available.
Starting >>> nav2_common
Starting >>> nav_2d_msgs
Starting >>> nav2_gazebo_spawner
Finished <<< nav2_gazebo_spawner [0.91s]
Finished <<< nav2_common [1.30s]
Starting >>> nav2_msgs
Starting >>> nav2_voxel_grid
Finished <<< nav_2d_msgs [14.3s]
Starting >>> dwb_msgs
Finished <<< nav2_voxel_grid [16.2s]
Finished <<< dwb_msgs [23.4s]
Finished <<< nav2_msgs [53.8s]
Starting >>> nav2_util
Finished <<< nav2_util [23.1s]
Starting >>> nav_2d_utils
Starting >>> nav2_behavior_tree
Starting >>> nav2_lifecycle_manager
Starting >>> nav2_map_server
Starting >>> nav2_amcl
Starting >>> nav2_waypoint_follower
Finished <<< nav_2d_utils [8.92s]
Finished <<< nav2_lifecycle_manager [19.3s]
Starting >>> nav2_rviz_plugins
Finished <<< nav2_waypoint_follower [19.9s]
--- stderr: nav2_behavior_tree
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/decorator/rate_controller.cpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::RateController::tick()’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/decorator/rate_controller.cpp:89:52: error: ‘void BT::TreeNode::setStatus(BT::NodeStatus)’ is protected within this context
   89 |         child_node_->setStatus(BT::NodeStatus::IDLE);
      |                                                    ^
In file included from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/decorator_node.h:4,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/decorator/rate_controller.cpp:21:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/tree_node.h:166:10: note: declared protected here
  166 |     void setStatus(NodeStatus new_status);
      |          ^~~~~~~~~
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/decorator/rate_controller.cpp:95:52: error: ‘void BT::TreeNode::setStatus(BT::NodeStatus)’ is protected within this context
   95 |         child_node_->setStatus(BT::NodeStatus::IDLE);
      |                                                    ^
In file included from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/decorator_node.h:4,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/decorator/rate_controller.cpp:21:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/tree_node.h:166:10: note: declared protected here
  166 |     void setStatus(NodeStatus new_status);
      |          ^~~~~~~~~
make[2]: *** [CMakeFiles/nav2_rate_controller_bt_node.dir/build.make:63: CMakeFiles/nav2_rate_controller_bt_node.dir/plugins/decorator/rate_controller.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/nav2_rate_controller_bt_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/round_robin_node.cpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::RoundRobinNode::tick()’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/round_robin_node.cpp:49:23: error: ‘void BT::ControlNode::haltChildren(size_t)’ is deprecated: deprecated: please use explicitly haltChildren() or haltChild(i) [-Werror=deprecated-declarations]
   49 |         haltChildren(0);
      |                       ^
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/round_robin_node.cpp:17:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:49:10: note: declared here
   49 |     void haltChildren(size_t first);
      |          ^~~~~~~~~~~~
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/round_robin_node.cpp:53:23: error: ‘void BT::ControlNode::haltChildren(size_t)’ is deprecated: deprecated: please use explicitly haltChildren() or haltChild(i) [-Werror=deprecated-declarations]
   53 |         haltChildren(0);
      |                       ^
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/round_robin_node.cpp:17:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:49:10: note: declared here
   49 |     void haltChildren(size_t first);
      |          ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_round_robin_node_bt_node.dir/build.make:63: CMakeFiles/nav2_round_robin_node_bt_node.dir/plugins/control/round_robin_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/nav2_round_robin_node_bt_node.dir/all] Error 2
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::PipelineSequence::tick()’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp:85:23: error: ‘void BT::ControlNode::haltChildren(size_t)’ is deprecated: deprecated: please use explicitly haltChildren() or haltChild(i) [-Werror=deprecated-declarations]
   85 |         haltChildren(0);
      |                       ^
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp:18:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:49:10: note: declared here
   49 |     void haltChildren(size_t first);
      |          ^~~~~~~~~~~~
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp:109:17: error: ‘void BT::ControlNode::haltChildren(size_t)’ is deprecated: deprecated: please use explicitly haltChildren() or haltChild(i) [-Werror=deprecated-declarations]
  109 |   haltChildren(0);
      |                 ^
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp:18:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:49:10: note: declared here
   49 |     void haltChildren(size_t first);
      |          ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_pipeline_sequence_bt_node.dir/build.make:63: CMakeFiles/nav2_pipeline_sequence_bt_node.dir/plugins/control/pipeline_sequence.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:517: CMakeFiles/nav2_pipeline_sequence_bt_node.dir/all] Error 2
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/recovery_node.cpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::RecoveryNode::tick()’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/recovery_node.cpp:91:31: error: ‘void BT::ControlNode::haltChildren(size_t)’ is deprecated: deprecated: please use explicitly haltChildren() or haltChild(i) [-Werror=deprecated-declarations]
   91 |                 haltChildren(0);
      |                               ^
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/recovery_node.cpp:19:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:49:10: note: declared here
   49 |     void haltChildren(size_t first);
      |          ^~~~~~~~~~~~
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/recovery_node.cpp:114:29: error: ‘void BT::ControlNode::haltChildren(size_t)’ is deprecated: deprecated: please use explicitly haltChildren() or haltChild(i) [-Werror=deprecated-declarations]
  114 |               haltChildren(1);
      |                             ^
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/control/recovery_node.cpp:19:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:49:10: note: declared here
   49 |     void haltChildren(size_t first);
      |          ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_recovery_node_bt_node.dir/build.make:63: CMakeFiles/nav2_recovery_node_bt_node.dir/plugins/control/recovery_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/nav2_recovery_node_bt_node.dir/all] Error 2
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp:15:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp: In member function ‘void nav2_behavior_tree::BehaviorTreeEngine::haltAllActions(BT::TreeNode*)’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp:52:46: error: ‘void BT::TreeNode::setStatus(BT::NodeStatus)’ is protected within this context
   52 |     root_node->setStatus(BT::NodeStatus::IDLE);
      |                                              ^
In file included from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:18,
                 from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/controls/parallel_node.h:18,
                 from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/behavior_tree.h:17,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp:22,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp:15:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/tree_node.h:166:10: note: declared protected here
  166 |     void setStatus(NodeStatus new_status);
      |          ^~~~~~~~~
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp:15:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp: In lambda function:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp:58:47: error: ‘void BT::TreeNode::setStatus(BT::NodeStatus)’ is protected within this context
   58 |           node->setStatus(BT::NodeStatus::IDLE);
      |                                               ^
In file included from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/control_node.h:18,
                 from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/controls/parallel_node.h:18,
                 from /opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/behavior_tree.h:17,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp:22,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp:15:
/opt/underlay_ws/install/behaviortree_cpp_v3/include/behaviortree_cpp_v3/tree_node.h:166:10: note: declared protected here
  166 |     void setStatus(NodeStatus new_status);
      |          ^~~~~~~~~
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp: In member function ‘nav2_behavior_tree::BtStatus nav2_behavior_tree::BehaviorTreeEngine::run(BT::Tree*, std::function<void()>, std::function<bool()>, std::chrono::milliseconds)’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp:50:13: error: ‘class BT::Tree’ has no member named ‘root_node’; did you mean ‘rootNode’?
   50 |       tree->root_node->halt();
      |             ^~~~~~~~~
      |             rootNode
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/src/behavior_tree_engine.cpp:54:20: error: ‘class BT::Tree’ has no member named ‘root_node’; did you mean ‘rootNode’?
   54 |     result = tree->root_node->executeTick();
      |                    ^~~~~~~~~
      |                    rootNode
make[2]: *** [CMakeFiles/nav2_behavior_tree.dir/build.make:63: CMakeFiles/nav2_behavior_tree.dir/src/behavior_tree_engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:301: CMakeFiles/nav2_behavior_tree.dir/all] Error 2
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/reinitialize_global_localization_service.cpp:22:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::BtServiceNode<ServiceT>::check_future(std::shared_future<typename ServiceT::Response::SharedPtr>)’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:101:40: error: ‘using FutureReturnCode = enum class rclcpp::FutureReturnCode’ is deprecated: use rclcpp::FutureReturnCode instead [-Werror=deprecated-declarations]
  101 |     rclcpp::executor::FutureReturnCode rc;
      |                                        ^~
In file included from /opt/ros/foxy/include/rclcpp/executor.hpp:34,
                 from /opt/ros/foxy/include/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:21,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:145,
                 from /opt/overlay_ws/install/nav2_util/include/nav2_util/node_utils.hpp:19,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:22,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/reinitialize_global_localization_service.cpp:22:
/opt/ros/foxy/include/rclcpp/future_return_code.hpp:48:7: note: declared here
   48 | using FutureReturnCode [[deprecated("use rclcpp::FutureReturnCode instead")]] = FutureReturnCode;
      |       ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_reinitialize_global_localization_service_bt_node.dir/build.make:63: CMakeFiles/nav2_reinitialize_global_localization_service_bt_node.dir/plugins/action/reinitialize_global_localization_service.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:220: CMakeFiles/nav2_reinitialize_global_localization_service_bt_node.dir/all] Error 2
In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/clear_costmap_service.cpp:22:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::BtServiceNode<ServiceT>::check_future(std::shared_future<typename ServiceT::Response::SharedPtr>)’:
/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:101:40: error: ‘using FutureReturnCode = enum class rclcpp::FutureReturnCode’ is deprecated: use rclcpp::FutureReturnCode instead [-Werror=deprecated-declarations]
  101 |     rclcpp::executor::FutureReturnCode rc;
      |                                        ^~
In file included from /opt/ros/foxy/include/rclcpp/executor.hpp:34,
                 from /opt/ros/foxy/include/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:21,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:145,
                 from /opt/overlay_ws/install/nav2_util/include/nav2_util/node_utils.hpp:19,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:22,
                 from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/clear_costmap_service.cpp:22:
/opt/ros/foxy/include/rclcpp/future_return_code.hpp:48:7: note: declared here
   48 | using FutureReturnCode [[deprecated("use rclcpp::FutureReturnCode instead")]] = FutureReturnCode;
      |       ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/nav2_clear_costmap_service_bt_node.dir/build.make:63: CMakeFiles/nav2_clear_costmap_service_bt_node.dir/plugins/action/clear_costmap_service.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:598: CMakeFiles/nav2_clear_costmap_service_bt_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< nav2_behavior_tree	[ Exited with code 2 ]
Aborted  <<< nav2_rviz_plugins
Aborted  <<< nav2_map_server
Aborted  <<< nav2_amcl

Summary: 10 packages finished [1min 52s]
  1 package failed: nav2_behavior_tree
  3 packages aborted: nav2_amcl nav2_map_server nav2_rviz_plugins
  2 packages had stderr output: nav2_behavior_tree nav2_rviz_plugins
  15 packages not processed
The command '/bin/sh -c . $UNDERLAY_WS/install/setup.sh &&     colcon build       --symlink-install       --mixin $OVERLAY_MIXINS     || touch build_failed &&     if [ -f build_failed ] && [ -n "$FAIL_ON_BUILD_FAILURE" ]; then       exit 1;     fi' returned a non-zero code: 1
```

**Comment by SteveMacenski** [comment]
Can you file tickets for the BT API library and reverting gazebo 11 once done? Anything else cause you problems?

I'm somewhat surprised to hear about the BT.CPP given we had @facontidavide playing around here not long ago. Are we just behind? Any way we can just use the latest from apt when Davide releases so that we can fail sooner on master branch?

**Comment by ruffsl** [comment]
> Can you file tickets for the BT API library and reverting gazebo 11 once done?

* https://github.com/ros-planning/navigation2/issues/1686
* https://github.com/ros-planning/navigation2/issues/1687

> Anything else cause you problems?

Was trying to test things in https://github.com/ros-swg/turtlebot3_demo/pull/34 , but haven't gotten to updating the launchfiles.

> Are we just behind? Any way we can just use the latest from apt when Davide releases so that we can fail sooner on master branch?

I think we are. The nightly image doesn't have released apt sources to install from. We could target our `.repos` file at a branch instead of a tag. Not sure @facontidavide uses distro branch names.

**Comment by facontidavide** [comment]
I can release the newest version BT.CPP **today**, if needed... actually, I will.
I am not using branch names, because the same branch should support simultaneously all the distros.

I can help you fixing anything that brakes (very few things, overall)

**Comment by SteveMacenski** [comment]
@ruffsl but BT.CPP is released via rosdistro so we should be able to just install the latest released version from rosdep keys and remove it from the repos file entirely, no?

**Comment by ruffsl** [comment]
@SteveMacenski the nightly images explicitly prevent rosdep from resolving released ROS distro packages to avoid accidentally polluting the system install with conflicting dependencies.

https://github.com/osrf/docker_images/pull/307

We could still install BT.CPP manually via apt, but that relies on the fact that it's been released for the linux distro the nightly image is targeting, and that itself doesn't rope any dependencies that would conflict/overwrite the extracted packages already installed from the nightly archive. Looking at it's package.xml, the later may not be much of an issue given the its dependencies footprint, but the former still is, as I don't think it been released into Focal. We could of course also switch FROM `osrf/ros2:nightly` to `ros:foxy`, but we'd no longer be testing agents ros2 master, plus foxy isn't even released. 

> I am not using branch names, because the same branch should support simultaneously all the distros.

We could just have the `.repos` file target the `master` branch instead if its not too unstable. That would also notify use of any breaking changes sooner.

**Comment by SteveMacenski** [comment]
Perhaps just bump up the version and we should watch the repo more carefully, I turned on notifications. I'd rather not run master in nightly. Frankly the Cyclone and Connext have been failing for so long on the nightly the circle emails go to spam. If those broke even more than just test failures, I'd never notice (but master builds on PR/PRs themselves would make me notice). 

I'll yield to whatever you think is best.

**Comment by ruffsl** [comment]
> Perhaps just bump up the version and we should watch the repo more carefully

We track `ros2` branches, or the functionally equivalent to master everywhere else, so I think doing so here would also be fine. We can roll back to a release tag if we get to much noise here.

> Frankly the Cyclone and Connext have been failing for so long on the nightly the circle emails go to spam.

Those being run-time failures vs. build-time failures, I think that's a different issue than here. Is there an existing ticket we could at least ping the Cyclone maintainers. They may appreciate the early testing and real world examples provided by the navigation2 packages in preparing for Foxy.

**Comment by SteveMacenski** [comment]
Ok, do it. 

>  we could at least ping the Cyclone maintainers

I have, I pinged @joespeed over email on this and I don't think anyone at ADLINK looked into it at all. Fast-RTPS right now is the only DDS provider that works with system testing.

(I think that last sentence might fire @joespeed up :wink: )

**Comment by SteveMacenski** [comment]
@ruffsl how do you feel about dropping support for Connext and only running Cyclone / Fast-RTPS. I have heard near-zero chatter about using connext and there's some evidence of dropping down to Tier 2 after Foxy. It reduces our nightly builds by a bunch.

Also, we're currently running debug build + test, which will be Fast-RTPS. Can we remove those 2 builds and just leave release build + Fast-RTPS so we're not running essentially the same job 2x?

**Comment by ruffsl** [comment]
> how do you feel about dropping support for Connext and only running Cyclone / Fast-RTPS.
> It reduces our nightly builds by a bunch.

I feel lukewarm about it, but I know we don't have as much manpower on the project post Intel. I'd like to at least see how the migration to contexts in foxy may help in this regard, but we could comment it out for the time being.

> I have heard near-zero chatter about using connext and there's some evidence of dropping down to Tier 2 after Foxy.

I was using Connext heavily, as its the only rmw vendor the fully implements the DDS Security Specification. I think there are also a lot more performance improvements in connext v6, but its a shame it didn't make this LTS. I originally upgraded our CI as I was frustrated that not all rmw's where working smoothly with fundamental ROS2 stacks (even with shared memory or over local loopback, regardless of wifi that you pointed out), but it doesn't seem to have had much effect on the rmw maintainers given navigation2 is outside the scope of the ros2 buildfarm OR focuses on.

> Also, we're currently running debug build + test, which will be Fast-RTPS. Can we remove those 2 builds and just leave release build + Fast-RTPS so we're not running essentially the same job 2x?

You want to remove the debug jobs from the nightly workflow? Our code coverage for master will then only update upon pushed commits to master branch. If that's fine with you, we could do that.

**Comment by SteveMacenski** [comment]
> I feel lukewarm about it, but I know we don't have as much manpower on the project post Intel. I'd like to at least see how the migration to contexts in foxy may help in this regard, but we could comment it out for the time being.

We don't use components though. Lifecycle - Components don't play at all together _still_. If things were working with these nightly builds and it was occasionally failing for flaky reasons, that would be one thing. But we're failing constantly and without anyone to look after it, I'd rather buckle down on things that we can either get support from (Cyclone, maybe) and default behaviors (Fast-RTPS) that happen to be mostly working. I'm not sure I care about the extra job running as much as I care about the extra stress of even more things failing without time to fix them. Plus the aforementioned "potentially on the way out the door anyway". Their licensing also doesn't make me want to jump up and down and help them, either. 

> You want to remove the debug jobs from the nightly workflow? Our code coverage for master will then only update upon pushed commits to master branch. If that's fine with you, we could do that.

Ah. I don't necessarily see that as a problem in my eyes (if nothing changed, then... nothing changes), but I understand from best practices we should keep that. Maybe we should remove the explicit fast-rtps jobs then? We're running
- debug build 
- debug test (fast rtps implicit)
- release build
- release test fast rtps

Just seems like we can remove at least 1.

**Comment by SteveMacenski** [comment]
@ruffsl do we need all 3 of the Dockerfiles in the root of the directory? I think the ones in `.dockerhub` are required for dockerhub (obviously) of which the debug and release both point to the root `Dockerfile`. 

`release_branch.Dockerfile`  still has `dashing` as the image, which makes me suspect we can get rid of it. I see that they were used in the pre-release checklist, but I can say that we haven't used them for that purpose for some time now. I think that was more of a problem circa-bouncy

**Comment by SteveMacenski** [comment]
@ruffsl lets revert the BT version for now deal with the ticket afterwards. I might be able to get one of the folks in the navigation2 slack to take a look at this.

**Comment by ruffsl** [comment]
@SteveMacenski , I made a commit to roll back the BT.CPP branch and add a no-error flag for deprecation warnings so this could be merged to stand the CI back up. We'll want to revert in the same PR that seeks to updated API usage of the current BT.CPP version. See 0162718

**Comment by SteveMacenski** [comment]
@ruffsl rebase on master, I just added the BT.CPP updates that should unblock this PR

**Comment by ruffsl** [comment]
> do we need all 3 of the Dockerfiles in the root of the directory?

I use that release Dockerfile from time to time with the ARG option to select the FROM image, so I've never needed committed a version bump. I updated it with some nice experimental features to have it build even faster on rebuilding for development use, but I can't get the tests to run it. Seems like naviagtion2 is not declaring all its testing time dependencies. Take a look when you get the change. We could move them into the tools folder or something.

**Comment by ruffsl** [comment]
> @ruffsl rebase on master, I just added the BT.CPP updates that should unblock this PR

Oh, sure. Tell me after I waited so patiently for the CI to bake my current rebasing. :P

**Comment by SteveMacenski** [comment]
> We could move them into the tools folder or something.

That would work for me

**Comment by SteveMacenski** [comment]
> Oh, sure. Tell me after I waited so patiently for the CI to bake my current rebasing. :P

I don't understand. I also don't see the rebase - your version in the repos file is not master like I changed it too in master

**Comment by ruffsl** [comment]
I still get a build error after refactoring ontop of master with https://github.com/ros-planning/navigation2/pull/1714 :

<details>

```
#26 105.2 --- stderr: nav2_behavior_tree
#26 105.2 In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/clear_costmap_service.cpp:22:
#26 105.2 /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::BtServiceNode<ServiceT>::check_future(std::shared_future<typename ServiceT::Response::SharedPtr>)’:
#26 105.2 /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:101:40: error: ‘using FutureReturnCode = enum class rclcpp::FutureReturnCode’ is deprecated: use rclcpp::FutureReturnCode instead [-Werror=deprecated-declarations]
#26 105.2   101 |     rclcpp::executor::FutureReturnCode rc;
#26 105.2       |                                        ^~
#26 105.2 In file included from /opt/ros/foxy/include/rclcpp/executor.hpp:34,
#26 105.2                  from /opt/ros/foxy/include/rclcpp/executors/multi_threaded_executor.hpp:25,
#26 105.2                  from /opt/ros/foxy/include/rclcpp/executors.hpp:21,
#26 105.2                  from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
#26 105.2                  from /opt/overlay_ws/install/nav2_util/include/nav2_util/node_utils.hpp:19,
#26 105.2                  from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:22,
#26 105.2                  from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/clear_costmap_service.cpp:22:
#26 105.2 /opt/ros/foxy/include/rclcpp/future_return_code.hpp:48:7: note: declared here
#26 105.2    48 | using FutureReturnCode [[deprecated("use rclcpp::FutureReturnCode instead")]] = FutureReturnCode;
#26 105.2       |       ^~~~~~~~~~~~~~~~
#26 105.2 cc1plus: all warnings being treated as errors
#26 105.2 make[2]: *** [CMakeFiles/nav2_clear_costmap_service_bt_node.dir/build.make:63: CMakeFiles/nav2_clear_costmap_service_bt_node.dir/plugins/action/clear_costmap_service.cpp.o] Error 1
#26 105.2 make[1]: *** [CMakeFiles/Makefile2:598: CMakeFiles/nav2_clear_costmap_service_bt_node.dir/all] Error 2
#26 105.2 make[1]: *** Waiting for unfinished jobs....
#26 105.2 In file included from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/reinitialize_global_localization_service.cpp:22:
#26 105.2 /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp: In member function ‘virtual BT::NodeStatus nav2_behavior_tree::BtServiceNode<ServiceT>::check_future(std::shared_future<typename ServiceT::Response::SharedPtr>)’:
#26 105.2 /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:101:40: error: ‘using FutureReturnCode = enum class rclcpp::FutureReturnCode’ is deprecated: use rclcpp::FutureReturnCode instead [-Werror=deprecated-declarations]
#26 105.2   101 |     rclcpp::executor::FutureReturnCode rc;
#26 105.2       |                                        ^~
#26 105.2 In file included from /opt/ros/foxy/include/rclcpp/executor.hpp:34,
#26 105.2                  from /opt/ros/foxy/include/rclcpp/executors/multi_threaded_executor.hpp:25,
#26 105.2                  from /opt/ros/foxy/include/rclcpp/executors.hpp:21,
#26 105.2                  from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
#26 105.2                  from /opt/overlay_ws/install/nav2_util/include/nav2_util/node_utils.hpp:19,
#26 105.2                  from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp:22,
#26 105.2                  from /opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/action/reinitialize_global_localization_service.cpp:22:
#26 105.2 /opt/ros/foxy/include/rclcpp/future_return_code.hpp:48:7: note: declared here
#26 105.2    48 | using FutureReturnCode [[deprecated("use rclcpp::FutureReturnCode instead")]] = FutureReturnCode;
#26 105.2       |       ^~~~~~~~~~~~~~~~
#26 105.2 cc1plus: all warnings being treated as errors
#26 105.2 make[2]: *** [CMakeFiles/nav2_reinitialize_global_localization_service_bt_node.dir/build.make:63: CMakeFiles/nav2_reinitialize_global_localization_service_bt_node.dir/plugins/action/reinitialize_global_localization_service.cpp.o] Error 1
#26 105.2 make[1]: *** [CMakeFiles/Makefile2:220: CMakeFiles/nav2_reinitialize_global_localization_service_bt_node.dir/all] Error 2
#26 105.2 make: *** [Makefile:141: all] Error 2
#26 105.2 ---
#26 105.2 Failed   <<< nav2_behavior_tree	[ Exited with code 2 ]
#26 106.7 Aborted  <<< nav2_rviz_plugins
#26 109.6 Aborted  <<< nav2_map_server
#26 112.4 Aborted  <<< nav2_amcl
#26 112.5 
#26 112.5 Summary: 10 packages finished [1min 51s]
#26 112.5   1 package failed: nav2_behavior_tree
#26 112.5   3 packages aborted: nav2_amcl nav2_map_server nav2_rviz_plugins
#26 112.5   2 packages had stderr output: nav2_behavior_tree nav2_rviz_plugins
#26 112.5   15 packages not processed
```

</details>

Do we still need to then no-error depredation warnings as in 44b19c2 ?

**Comment by SteveMacenski** [comment]
@ruffsl that's not a false error, that's a real error, we are behind on rclcpp because the docker builds weren't getting through to update the cache from the gazebo11 issues. 

https://github.com/ros-planning/navigation2/pull/1702 will resolve that, but for its CI to pass it needs an updated docker image to get through if my explanation in https://github.com/ros-planning/navigation2/pull/1702#issuecomment-626100120 is correct.

**Pull request merged**
