### PR TITLE
Added nav2_ prefix to smac_planner

### PR DESCRIPTION
**Pull request by tonynajjar**
Signed-off-by: Tony Najjar <tony.najjar.1997@gmail.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2092 |
| Primary OS tested on | Ubuntu 20.04|
| Robotic platform tested on | turtlebot simulation |

---

## Description of contribution in a few bullet points

* I added the prefix nav2_ to the smac_planner (I took navfn planner package as a model)

## Description of documentation updates required from your changes

* The smac_planner [Configuration page](https://navigation.ros.org/configuration/packages/configuring-smac-planner.html)
*The foxy -> galactic  [migration page](https://navigation.ros.org/migration/Foxy.html) - smac_planner section
---

### CODE REVIEW

**Review by SteveMacenski — COMMENTED** [review]
Did you test that you can set the parameter in planner_server that it loads correctly? Just need to verify that it actually works with the pluginlib updates.

On documentation:
- The smac planner change will need this change in the example XML file
- The foxy -> galactic migration page will need a new entry talking about this change

**Comment by tonynajjar** [comment]
Yes, in nav2_params.yaml I changed the plugin to `"nav2_smac_planner/SmacPlanner"` and the bringup_launch.py still loads correctly: `[planner_server-5] [INFO] [1605557674.092022633] [planner_server]: Created global planner plugin GridBased of type nav2_smac_planner/SmacPlanner`
 
Even tested the planner in a turtlebot3 gazebo simulation and it works. Let me know if I there is some way to test it further.

As far as documentation is concerned, here is the pull request for the first point: https://github.com/ros-planning/navigation.ros.org/pull/115

For your second point I'm assuming it should go in [here](https://github.com/ros2/ros2_documentation/blob/master/source/Releases/Release-Galactic-Geochelone.rst) under "Changes since the Foxy Release"? I'm not super sure what to add? A one-liner that the package name has changed? And what do you mean with "add nav_ to migrate". Will take me a moment to understand all the jargon :D

**Comment by SteveMacenski** [comment]
No, use the migration page on the nav2 doc website (under migration guides -> foxy). We have the entry for smac planner being a new addition, so you just need to change to use the `nav2_` header

**Comment by tonynajjar** [comment]
Pull request for linking our migration guides to ROS2's: https://github.com/ros2/ros2_documentation/pull/904

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
