### PR TITLE
Use different param name for slam_toolbox param_file

### PR DESCRIPTION
**Pull request by v-lopez**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2240|
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | simulated turtlebot |

---

## Description of contribution in a few bullet points

* Use renamed slam_toolbox param-file

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
Did you test that this works for both cases?

**Comment by v-lopez** [comment]
Yes, with default param file it will load the slam_toolbox parameters.

If I copy those contents into the nav2_bringup params, it loads the nav2_bringup params file.

**Comment by SteveMacenski** [comment]
@v-lopez main is A-OK for this and SLAM Toolbox. Still the other one I need to think more about with foxy-devel given the API change

**Comment by SteveMacenski** [comment]
@v-lopez I've managed to get my wires super crossed, were we talking about multiple goal checker plugins? I believe so, but for the life of me, I can't seem to find the PR / issue / discussion we were having on it.

**Pull request merged**
