### PR TITLE
[gazebo-migration] Make gazebo_ros_pkgs optional in nav2_system_tests

### PR DESCRIPTION
**Pull request by Ryanf55**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | N/A |
| Primary OS tested on |  Ubuntu 22|
| Robotic platform tested on | No |
| Does this PR contain AI generated software? | No |

---

## Description of contribution in a few bullet points

* Leverage common environment variable `GZ_VERSION` to control which gazebo is linked to in system_tests
* Add author warning when some system tests are disabled
* Making gazebo classic optional is one of the first things to help migration
* This allows users to build all of nav2 with new gazebo installed without any special flags
* Conditionally skip rosdep for gazebo classic based on the same environment variable
* This is backward compatible to `humble` and should not result in any change in behavior for existing CI
* Allow developers to use new gazebo binaries on their Ubuntu 22.04 OS, build nav2 from source, and not deal with the [dependency conflict](https://gazebosim.org/docs/garden/install_ubuntu#binary-installation-on-ubuntu).

## Description of documentation updates required from your changes

* If you like the proposal, I can add user docs

---

## Future work that may be required in bullet points

* Continue this pattern to make all of gazebo classic optional in NAV2
* Port user examples to new gazebo
* Port system tests to new gazebo
* Remove gazebo dependencies 11 entirely

## Screenshots of warnings when you are missing gazebo classic

These will show up on `colcon build` if you have the `GZ_VERSION` environment variable set to something other than an empty string.

image

image

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by Ryanf55** [comment]
I think it would be helpful to understand what the migration plan for ROS packages is when we have a dependency conflict. The oversight of whoever allowed gazebo classic into Ubuntu 22 and then let the new gazebo in and depend on a conflicting debian package is a  disaster. 

The PR here proposes a path for a smooth migration plan, but since you aren't a fan... it would be helpful to know how you plan to migrate to new gazebo on `rolling`.  I was expecting a `rolling platform shift` to Ubuntu noble, which does not come with gazebo classic, but that hasn't happened yet?
By January, 2024 - Rolling platform shift: https://docs.ros.org/en/rolling/Releases/Release-Jazzy-Jalisco.html#release-timeline

**Comment by SteveMacenski** [comment]
We have pending PRs for gazebo2 that are not yet complete. That's a stepping stone to get our bringup to use gazebo2 and use those changes as a model to update our tests. The gazebo and gazebo2 bringup files will exist in parallel in Jazzy and probably for the immediately foreseeable future, but the gazebo2 tests will be fully transitioned over once they are stable

**Comment by azeey** [comment]
> My understandign is that 24.04 will have gazebo classic binaries distributed by someone else, so there's no a step function where they instantly stop working

@SteveMacenski do you know who would be doing that? I'm not aware of any source for Gazebo classic binaries on 24.04 atm.

**Comment by SteveMacenski** [comment]
Canonical / Ubuntu is doing it I was told my OSRF folks a few times. I don't have first hand documentation of that, more general conversations with your team and mentioning frustration with that. Maybe I'm mistaken?

**Comment by azeey** [comment]
Yeah, it seems like there's some confusion. We've posted https://discourse.ros.org/t/gazebo-classic-end-of-life-ros-2-jazzy/36239 to hopefully clear things up. As stated there, **Gazebo Classic will not be available on Ubuntu 24.04**.

**Pull request closed without merging**
