### PR TITLE
prevent dwb controller from missing changes to the global path (#1160)

### PR DESCRIPTION
**Pull request by Jconn**
this fixes rare cases where my dwb controller isn't picking up changes to the global path.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@Jconn I think you have some uncrustify issues in your PR, can you fix so we can merge?

**Comment by Jconn** [comment]
Thanks! Is there documentation on the checklist I should go through before making a PR so I can do better with bigger changes?

**Comment by SteveMacenski** [comment]
Oh yeah, sorry, I dont think we do.

But `ament` has built in some tools that we rely on. `ament_cpplint` `ament_xmllint` `ament_uncrustify`. If you change things and it passes those, stylistically that should be fine, along with the usual naming nomenclature

**Comment by Jconn** [comment]
@SteveMacenski I looked at the release_test build and don't see` bt_action_node.hpp ` triggering crustify anymore

**Comment by SteveMacenski** [comment]
image

**Comment by Jconn** [comment]
I don't have write access to this wonderful project, but I am a-okay with this being merged at earliest convenience

**Pull request merged**
