### PR TITLE
Build using the tip of master

### PR DESCRIPTION
**Pull request by orduno**
Here are a few changes needed to build using the latest ROS2 code.

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
@orduno - this is failing because the library libyaml-cpp-dev isn't being installed yet. The Dockerfile needs to be updated in the 'apt-install' section to add that library.

**Comment by mkhansen-intel** [comment]
@orduno - correction, I can see that being installed. It's looking for yaml-cpp-vendor. Is that the right package name?

**Comment by orduno** [comment]
> @orduno - correction, I can see that being installed. It's looking for yaml-cpp-vendor. Is that the right package name?

Yes, however it's built together with ROS2 (master branch) and it [was recently renamed](https://github.com/ros2/yaml_cpp_vendor).  Travis is still looking for rviz_yaml_cpp_vendor instead of yaml_cpp_vendor.

**Comment by mkhansen-intel** [comment]
linking to #237 - when that passes we can merge this one

**Pull request merged**
