### PR TITLE
Fix cppcheck errors

### PR DESCRIPTION
**Pull request by naiveHobo**
Signed-off-by: Sarthak Mittal <sarthakmittal2608@gmail.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  #1717 |
| Primary OS tested on | Ubuntu 18.04 |

---

## Description of contribution in a few bullet points

* Fixed cpperror in ```nav2_system_tests``` and ```nav2_costmap_2d```
* ```nav2_costmap_2d``` errors were fixed by converting raw pointers to layer objects to smart pointers
* ```nav2_system_tests``` error is related to https://github.com/google/googletest/issues/1419

### CODE REVIEW

**Comment by naiveHobo** [comment]
Ah a small bug, writing a fix

**Comment by SteveMacenski** [comment]
Will merge if tests clear up. 

Thanks for jumping on this so quickly. Quirks this close to distribution releases always take up a bunch our time.

**Comment by naiveHobo** [comment]
@SteveMacenski should be good to go!

**Comment by SteveMacenski** [comment]
What about map server? 

I assumed that was related, it popped up with the rest

**Comment by naiveHobo** [comment]
I believe that's an unrelated flaky test. 

After the first couple of tests, the map server node doesn't get enough time to start up properly:
https://github.com/ros-planning/navigation2/blob/7addcb7f63643a44b652e4dfb8b3bc1ef8ef509b/nav2_map_server/test/component/test_map_server_node.cpp#L48-L56

And the tests are blocked waiting for the ```/map_server/load_map``` service which never shows up:
https://github.com/ros-planning/navigation2/blob/7addcb7f63643a44b652e4dfb8b3bc1ef8ef509b/nav2_map_server/test/component/test_map_server_node.cpp#L127-L128

**Comment by SteveMacenski** [comment]
I'm not sure its unrelated. I can say with high confidence that I've never seen that test casually fail. The usual flaky tests are waypoint follower, action utils, and on rare instances static layer tests. 

Can you make those updates?

**Comment by naiveHobo** [comment]
This commit is just a check to see if increasing the sleep time fixes the error on CI. I was able to fix it on my system by increasing the sleep time. I'm writing a proper fix, though.

**Comment by naiveHobo** [comment]
Good to go!

**Comment by SteveMacenski** [comment]
Great :-) Master build back up to par, dockerhub is turning over, we're back in the green

**Pull request merged**
