### PR TITLE
Run multi-robot tests on Travis

### PR DESCRIPTION
**Pull request by orduno**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #1308 |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | Gazebo simulation of TB3 |

---

## Description of contribution in a few bullet points

Addressing #1308, tests have been consistently passing on my machine so I think we can enable them.

### CODE REVIEW

**Comment by crdelsey** [comment]
We've already got the test running on CircleCI. I'm not sure we should add it to Travis as well. Travis is much more time constrained.

The way the CI has evolved, CircleCI is the main system and Travis is kind of a simplified backup.

Since we are limited in what we can do in Travis due to the time, I'm inclined to just keep Travis as it is, with just the minimal system test. Also, Travis takes such a long time to run, it might be better to not add extra long running tests.

**Comment by orduno** [comment]
I'm ok with not adding the multi-robot tests to CI. 

Steve, ok if we cancel the PR?

**Comment by SteveMacenski** [comment]
So it seems then only Travis uses the bash script. Then should we just delete the script & Travis if its just a back up? No need to waste resources building & maintaining it if theres not enough value add to justify full coverage

**Comment by crdelsey** [comment]
@orduno Let's go ahead and add this since you've made the change, and the PR is all approved.

We can discuss the future of Travis in a future WG meeting.

**Comment by SteveMacenski** [comment]
@crdelsey given Matt and I are in China, I'm not sure either of us will be in attendance (or at least me). 

I'll go with whatever you guys decide.

**Pull request merged**
