### PR TITLE
fix namespaces for bringup

### PR DESCRIPTION
**Pull request by padhupradheep**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #2796 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on |  |

---

## Description of contribution in a few bullet points

* Added the namespace parameter as part of the Node. 

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by padhupradheep** [comment]
This is a fix mainly for the people who wants to add a namespace and do the `navigation_launch.py` as a standalone.

**Comment by SteveMacenski** [comment]
How does this interact with using the bringup's push into namespace? https://github.com/ros-planning/navigation2/blob/galactic/nav2_bringup/bringup/launch/bringup_launch.py#L80-L82 that should be doing all the heavy lifting here. I think adding that there would apply a double namespace `/ns/ns/planner_server`. How can we make sure that doesn't occur?

**Comment by padhupradheep** [comment]
> that should be doing all the heavy lifting here. I think adding that there would apply a double namespace /ns/ns/planner_server

Nope, it's indeed not pushing twice. I can confirm that.

**Comment by SteveMacenski** [comment]
From `bringup` being set as `namespace` so its both being pushed in `bringup` and set in `navigation`'s Node() call? That's surprising behavior

**Comment by padhupradheep** [comment]
> From bringup being set as namespace so its both being pushed in bringup and set in navigation's Node() call?
Atleast with the tests from this PR, that's how it is working.

**Comment by padhupradheep** [comment]
I feel something like this is happening as shown in the below lines:

https://github.com/ros2/launch_ros/blob/835b40c47cfd84083a510baea510052148d3d406/launch_ros/launch_ros/utilities/namespace_utils.py#L59-L60

**Comment by SteveMacenski** [comment]
Where is the absolute namespace with the leading `/` in all of this? I don't see any arguments with that to get that potential outcome.
https://github.com/ros2/launch_ros/blob/d1c497878274a4ea6a1c1865fe74e395b961ba1f/test_launch_ros/test/test_launch_ros/actions/test_push_ros_namespace.py#L61-L64

 this test case for the Push API in launch looks to me what's happening. We have a node namespace set in `Node()` and a Push namespace showing we should get both. Unless I'm misinterpreting what `node_ns` is supposed to be otherwise (what's defined in code?)

**Comment by padhupradheep** [comment]
> Just to verify you are also setting use_namespace to true along with setting the namespace too so the push + the namespace field in the Node() are used. 

Oops, I missed the `use_namespace` args. When I use it, I get a double namespace as you showed /ns/ns/planner_server . Damn, sorry for the confusion, I missed the above argument and wasted some time on it.

**Comment by SteveMacenski** [comment]
No worries at all, this is why we ask questions. I appreciate you taking a look at this issue to help find a solution! 🙂

sounds like we can close this unless you had another idea? Perhaps if we Push namespace we should set the namespace we pass to empty string? Or maybe do this outright and remove the use of Push? The major use of that is for the multirobot case

**Comment by padhupradheep** [comment]
> Perhaps if we Push namespace we should set the namespace we pass to empty string?

This can be an option for us, which leads us to the removal of `use_namespace` parameter in `nav2_bringup.`

**Comment by SteveMacenski** [comment]
OK, I think there's just 2 things you need to make sure works
- Setting namespace from CLI works
- Using the multirobot launch API, it continues to throw everything in the appropriate namespace

**Comment by padhupradheep** [comment]
On further research, removing `use_namespace` from the `nav2_bringup` will have a severe consequence on RViz launch for multi robot navigation. Especially here:

https://github.com/ros-planning/navigation2/blob/7f0e08746915b7ad64caf1e2c008c4109a981367/nav2_bringup/launch/rviz_launch.py#L57

 I would suggest, we keep the stones unturned.

**Comment by SteveMacenski** [comment]
OK - understood. Closing (unless you don't mean that, happy to reopen!)

**Pull request closed without merging**
