### PR TITLE
Use fastcov to speed up coverage for CI

### PR DESCRIPTION
**Pull request by ruffsl**
Make use of `fastcov` to speed up CI:
https://github.com/RPGillespie6/fastcov

### CODE REVIEW

**Comment by ruffsl** [comment]
A rather nice improvement... Not too shabby :P

## Before: 31m 25s
https://app.circleci.com/pipelines/github/ros-planning/navigation2/5455/workflows/625353dc-ec89-41b3-a554-4cb2f6dcecf2/jobs/19971/parallel-runs/0/steps/0-116

## After: 34s
https://app.circleci.com/pipelines/github/ros-planning/navigation2/5458/workflows/f65c0be8-e5c3-46ec-8a5b-d20e726f6f48/jobs/19985/parallel-runs/0/steps/0-117

**Comment by SteveMacenski** [comment]
When did that start taking 30 minutes? Looking back only a month it was taking about 2 minutes https://app.circleci.com/pipelines/github/ros-planning/navigation2/5301/workflows/1131a535-ce5b-4bc2-bd26-0b3af0a0836f/jobs/19546/steps

**Comment by ruffsl** [comment]
With the gap in CI runs from the galactic breakages, I could only narrow down the regression between theses workflow runs:

* Before regression:
  * https://app.circleci.com/pipelines/github/ros-planning/navigation2/5364/workflows/37e3f336-bec9-4250-916c-ae6a9178c1c3/jobs/19764
* After regression
  * https://app.circleci.com/pipelines/github/ros-planning/navigation2/5448/workflows/289167a7-9002-451d-a8e5-86696b4b4b08/jobs/19943/steps

I'm not sure what changed here though. Any guesses? Some of my guesses:

* Performance regression upstream in lcov package
* Increase or change in how we generate coverage with gcc

The coverage mixin hasn't changed for more than a year, so the cmake and python args wouldn't haven't changed.

https://github.com/colcon/colcon-mixin-repository/blob/master/coverage.mixin

**Comment by SteveMacenski** [comment]
https://github.com/ros2/rclcpp/commit/0251f70fe8a952fae242e6dcdc5b11bc4c11dc76 its also the date rclcpp released 11.0.0, so maybe something in the ROS2 stack was updated and got back up to us in compile flags? 

Only other thing I could think of it this commit https://github.com/ros-planning/navigation2/pull/2330 did something odd, but I don't see how that's possible

**Comment by ruffsl** [comment]
> I'm good with this change either way once you are

Codcov doesn't show any change in coverage for this PR, so I'll go ahead and merge.

https://codecov.io/github/ros-planning/navigation2/commit/dbc8153498f562961106f8876f5e88756b1e4ba7

I'm also going to open a ticket with `colcon-lcov-result` so ask if they've noticed the same performance regression, but at least this should resolve our issue in the meantime.

**Pull request merged**
