### PR TITLE
Adding the capability for the RRP to drive the robot backwards

### PR DESCRIPTION
**Pull request by padhupradheep**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #2327 |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | gazebo simulation of [Neobotix MPO-700](https://github.com/neobotix/neo_simulation2) |

---

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
Please read the discussion in https://github.com/ros-planning/navigation2/issues/2327, this would not be robust. You should be looking at the orientation vectors of the path to determine cusping to change directions. I'm also not sure how you solved the issue of it reversing too early if the carrot is a future-pose relative to the base location being where the cusp is. 

I'm also not sure why you remove rotation to path and reorg the apply constraints function. 

Can you show a gif or video of this working?

**Comment by SteveMacenski** [comment]
This should probably be re-worked -- maybe readded as a draft PR or resubmit a new PR at a later date?

**Comment by padhupradheep** [comment]
Sure, I will look into the points and do the re-work! I think a new PR will be a good idea!

**Comment by padhupradheep** [comment]
Well, I did not take the cusp into the consideration, rather just looked into the position of the carrot. After seeing this [image](https://github.com/leggedrobotics/se2_navigation/blob/master/pure_pursuit_core/doc/path_conventions.pdf), as you said I think my solution will not be robust.

**Pull request closed without merging**
