### PR TITLE
Add ignoring code cov any files named test_

### PR DESCRIPTION
**Pull request by SteveMacenski**
To deal with code cov still picking up:
- https://codecov.io/gh/ros-planning/navigation2/tree/master/nav2_map_server
- https://codecov.io/gh/ros-planning/navigation2/tree/master/nav2_recoveries
- https://codecov.io/gh/ros-planning/navigation2/tree/master/nav2_util/test

### CODE REVIEW

**Comment by shivaang12** [comment]
I think it would be wise to add for `*_test*` too.

**Comment by SteveMacenski** [comment]
We don't have any thing that that would cover. This is the last of it. Honestly I probably should have just renamed the 1 file that required that regex but this was easier at the moment.

**Comment by SteveMacenski** [comment]
I'm rerunning CI until all pass so I can look over the report from codecov to make sure everything's good

**Comment by shivaang12** [comment]
Sounds fair.

**Comment by SteveMacenski** [comment]
+0.04%....


Whatever. I'll take it.

**Pull request merged**
