### PR TITLE
Port costmap2d buffer + tf_sensor_msgs local port 

### PR DESCRIPTION
**Pull request by SteveMacenski**
tf2_sensor_msgs once merged into geometry2 should move back to their fork rather than mine which is identical except for this commit.

Deals with #132 as well as ports correctly the observation_buffer. This deals with elements needed to fully port obstacle layer

### CODE REVIEW

**Comment by SteveMacenski** [comment]
It looks like this job failed because the most recent image doesnt include the ros2.deps file items? Unsure. I added into the navstack_dependencies_ws (and vcs file) the geometry2 overlay containing this information. I dont see where the initialize script is called in Travis

**Comment by mkhansen-intel** [comment]
@SteveMacenski - Yes it looks like we have a hole in our CI here. I can submit a fix for the buildscript to make it accept a branch parameter for pulling in the new repos files from the branch. Right now it is always pulling in the repos file from the master branch.

I expect this to pass CI on the master branch when merged, so we don't have to gate this PR on CI.

**Comment by SteveMacenski** [comment]
Ok, @mkhansen-intel merge at your leisure. 

PS I've just been waiting for you all at Intel to merge my PRs. I can continue to do that or after 2 approvals and no more discussion do myself. I'll leave that up to you.

**Comment by mkhansen-intel** [comment]
@SteveMacenski - can you make your commit messages a little more clear? Generally I try to follow good commit message guidelines like this:
https://chris.beams.io/posts/git-commit/
I'm normally not too much of a stickler about this but when I saw 'commit 1' I had to request a change. I don't even care if there's no body to the commit as long as the title is self-explanatory.

I'll also review this with the team and see if we can't all improve in this area going forward.

**Comment by SteveMacenski** [comment]
Sure, I expect a squash commit on merge that contains the PR title so I usually don't think about each individual commit much.

**Comment by SteveMacenski** [comment]
OK squashed

**Comment by mkhansen-intel** [comment]
@SteveMacenski - thanks for squashing. We can do a squash and merge for your PRs in the future if you want, just specify that in the PR. I don't typically do that by default unless it's a large PR with a lot of commits. I like to see some history and also it makes it possible to revert a single commit if we need to in the future. 

As for the CI - I have a dockerfile change that pulls in the dependencies that I'll submit as a PR today, but I tested it on your branch yesterday and it failed. Take a look here:
https://travis-ci.org/ros-planning/navigation2/builds/445929027

It seems to be failing when building one of the tests for tf2_geometry_msgs. Can you take a look and see if you can fix it?

**Comment by SteveMacenski** [comment]
I see what the issue is -- I'll resolve just after lunch today.

**Comment by SteveMacenski** [comment]
Alright, worked through it -- not as bad as I thought. You can retry again

**Comment by mkhansen-intel** [comment]
@SteveMacenski - can you rebase to master please? I merged my Dockerfile change and I'd like to see if it fixed this.

**Comment by SteveMacenski** [comment]
rebased

**Pull request merged**
