### PR TITLE
[dwb_core] Never shortcut trajectory scoring

### PR DESCRIPTION
**Pull request by sloretz**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation of turtlebot waffle |

---

## Description of contribution in a few bullet points

* Removed short cut of trajectory scoring from `dwb_core` because it often leads to worse overall trajectories being chosen

## Description of documentation updates required from your changes

* Removed documentation of parameter that optionally disabled short cut taking

---

## Future work that may be required in bullet points

* an ABI compatible patch to Eloquent could be done by always passing `-1` for `best_score` to `scoreTrajectory()`

## Long description
When evaluating trajectories, dwb will stop running critics as soon as
the trajectory's score is better than the best trajectory seen so far.
It looks like this often leads to worse trajectories being chosen as the
overall best.

Consider 3 trajectories and 2 critics:

1. t1 is scored by both critics and gets scores [0.5, 0.0] for a total
score of 0.5
1. t2 is scored by the first critic and gets a score of 0.6. Since
it's better than the best so far, the scoring gets cut short. If it
hadn't been cut short, t2's scores would have been [0.6, 0.5] for a
total of 1.1
2. t3 is scored by both critics for scores [0.4, 0.4] for a total of
0.8. t3 is chosen as the best trajectory even though it's total score of
0.8 is smaller than what t2's would have been if all critics had been
run on it.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
This was something done to sync up with the state of DWB in ROS1 in robot_navigation repo.

Is it so often "bad" that it causes serious issues such that it should be totally removed from existence? Or should the defaults just be set to false?

It seems to be an extreme move to remove capabilities

**Comment by shivaang12** [comment]
can you post some videos (short circuit v/s not short circuit) may be? if possible? Thanks!

**Comment by sloretz** [comment]
> Is it so often "bad" that it causes serious issues such that it should be totally removed from existence? Or should the defaults just be set to false?

Ah shoot; this is a failure to read on my part. I assumed higher scores were better, but actually lower scores are better. I'll close this.

**Comment by SteveMacenski** [comment]
No worries. If I had a nickel for every time I did that...





... I'd still be living in a shoebox apartment in San Francisco. This place is expensive.

**Pull request closed without merging**
