### PR TITLE
update tb3 mesh uri

### PR DESCRIPTION
**Pull request by ROBOTIS-Will**
Signed-off-by: Will Son <willson@robotis.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/159 |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | TurtleBot3 Simulation |

---

## Description of contribution in a few bullet points

* apply updated mesh uri revision in [turtlebot3_simulations](https://github.com/ROBOTIS-GIT/turtlebot3_simulations) package
* each TurtleBot3 model used to have its own directory with redundant mesh files, and this has been updated to share common mesh files in a single directory(e.g. turtlebot3_common/meshes/)

## Description of documentation updates required from your changes

* no change is necessary once turtlebot3_simulation binary is released.

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Has this update been reflected in ROS2 Rolling? Nav2 is based on Rolling so that would need to be released first before an update to Nav2 could be accepted

**Comment by SteveMacenski** [comment]
Pinging @ROBOTIS-Will

**Comment by SteveMacenski** [comment]
Closing from non responsive committer

**Comment by ROBOTIS-Will** [comment]
@SteveMacenski 
I'm sorry about the super delayed response.
This has not been released in Rolling yet so I'll request again after the release. 
The turtlebot3_simulation package is now completely separated from other TurtleBot3 packages and does not have a new dependency.

This update is applied to Rolling (ros2 branch) and pulled into the Galactic(galactic-devel branch), and I can also apply this to Foxy if it is preferred.

The turtlebot3_common meshes are under the models directory in turtlebot3_gazebo package.
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/tree/ros2/turtlebot3_gazebo/models/turtlebot3_common

Thank you!

**Comment by SteveMacenski** [comment]
>  This has not been released in Rolling yet so I'll request again after the release.

Got it!

**Pull request closed without merging**
