### PR TITLE
Don't pass rosdistro when using empty index

### PR DESCRIPTION
**Pull request by ruffsl**
Context: https://github.com/osrf/docker_images/pull/399

### CODE REVIEW

**Comment by SteveMacenski** [comment]
https://circleci.com/gh/ros-planning/navigation2/11551?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@ruffsl at least back to the connext error. Should we just remove these changes to begin with if they didn't impact the result?

**Comment by ruffsl** [comment]
The connext issue is unrelated to any of our changes here. It's most likely an upstream regression:
https://github.com/osrf/docker_images/issues/403

I re-ran the nightly CI after pushing images built from master, and the release build seems fine now:
https://circleci.com/workflow-run/44d09f51-0f2d-49fe-8a79-6b73c6a48352

**Comment by SteveMacenski** [comment]
So that should work until we push to master again?

**Comment by ruffsl** [comment]
> So that should work until we push to master again?

Yes. I just used the same build hook script, but locally. You can build exactly what DockerHub would build, only its sometimes quicker to do so on a 20 core workstation than it is to wait for DockerHub to finish it's job queue. I just cancel any pending builds before I push, so my pushed images don't get immediately overwritten with a commit it'll then already has an image for.

E.g.
https://github.com/ros-planning/navigation2/blob/master/.dockerhub/release/hooks/build'
https://github.com/ros-planning/navigation2/blob/master/.dockerhub/debug/hooks/build

One only needs to set the `IMAGE_NAME` env before running, then docker push the tag.

**Comment by SteveMacenski** [comment]
@ruffsl perhaps its worth we temporarily disabling auto-updating jobs on dockerhub (e.g. dont let it build on master pushes or on OSRF updates) until your ticket is closed.

**Comment by ruffsl** [comment]
We already worked around that issue by moving the release build away from `nightly-rmw-nightly`.
https://github.com/ros-planning/navigation2/pull/1746

Are you able to reproduce the connext issue in Docker using the current nav2 master branch?

**Comment by SteveMacenski** [comment]
I've been too busy the last 2 weeks just managing the explosion of people involved, I haven't had cycles to do much development.

**Pull request merged**
