### PR TITLE
Move CI from ROS2 master to Rolling

### PR DESCRIPTION
**Pull request by ruffsl**
Related: #2337

### CODE REVIEW

**Comment by SteveMacenski** [comment]
The build failed due to inability to find the packages commented out in the repos file

**Comment by ruffsl** [comment]
> The build failed due to inability to find the packages commented out in the repos file

That's because the Docker image on our Docker Hub repo that the CI is using is still built from the `osrf/ros2:nightly` parrent image. Once this merges, we'd want to retrigger docker hub daily job to rebuild the CI Docker Image using updated Dockerfile.

**Comment by SteveMacenski** [comment]
Got it, @ruffsl you're free to merge then, just make sure this stands back up in the next day or two. There's no pending PRs I see going anywhere in the immediate future and with the galactic release this week I'm closing up shop on `main` so this is as good of a time as any

**Comment by ruffsl** [comment]
The release tag is a lot smaller, but the debug is still hefty. We can shrink this more later. Images sizes for new rolling images:

## `osrf/ros2:nightly`


```
REPOSITORY               TAG                                   IMAGE ID       CREATED              SIZE
rosplanning/navigation2  main.debug                            651565815e31   1 days ago           14.3GB
rosplanning/navigation2  main.release                          60230fd0a678   1 days ago           10.3GB
```

## `ros:rolling`

```
REPOSITORY               TAG                                   IMAGE ID       CREATED              SIZE
rosplanning/navigation2  main.debug                            e3cebddf66e6   About a minute ago   10.8GB
rosplanning/navigation2  main.release                          4d5632bfc073   About a minute ago   4.41GB
```

I've manually pushed these local images built from rolling to Dockerhub to jumpstart nav2 CI so I can test this PR as well.

**Comment by ruffsl** [comment]
Build jobs are passing with rolling base images! Now merging.

**Pull request merged**
