### PR TITLE
Std::string doesn't have such constructor, therefore wrong exception happens when waiting for action server is over

### PR DESCRIPTION
**Pull request by andriimaistruk**
---

## Basic Info

| Info | Correct exception message when action server is not up within a specified interval |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/3331 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | custom |

---

## Description of contribution in a few bullet points

* fixed using non-existent std::string constructor

## Description of documentation updates required from your changes

* None

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
CI is complaining about linting errors. Can you take a look and resolve the styling disputes?

**Comment by SteveMacenski** [comment]
Any update?

**Comment by andriimaistruk** [comment]
added code styles changes, will see whether they fix it

**Comment by andriimaistruk** [comment]
the code style is ok now as I can see from circleci logs, some nav2_behavior_tree tests fail now. I don't see how my exception message changes would make that happen.

**Pull request merged**
