### PR TITLE
Allow for node_name change during initialization

### PR DESCRIPTION
**Pull request by austin-InDro**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | `None` |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | InDro Robotics - Sentinel |

---

## Description of contribution in a few bullet points
If you were to spawn up multiple Simple Commanders, you will receive a `Publisher already registered for provided node name`. This would allow you to have different nodes that can log separately.

## Description of documentation updates required from your changes
- Possibiliy mention this is now an option for users?

---

## Future work that may be required in bullet points
- None

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — COMMENTED** [review]
Please retarget to the main branch and I’ll merge. We want to make sure this is reflected in all new distributions as well

**Comment by austin-InDro** [comment]
@SteveMacenski done. I can close this and open another pull if you don't want the current Humble changes in the main branch just yet?

**Comment by SteveMacenski** [comment]
God damn mergify...

**Comment by austin-InDro** [comment]
I'm going to just close this an open another pull request from main instead. Definately the fastest method.

**Pull request closed without merging**
