### PR TITLE
Update Dockerfiles

### PR DESCRIPTION
**Pull request by ruffsl**
- Fixes typos
- Simplifies Dockerhub config
- Optimizes source build with more multi staging
  - folding between install and build stages
  - parallel testing of workspaces

This doesn't affect much of the current build time, given how front loaded the build dependencies are with most of ROS2, but will help with consecutive rebuilds/tests, or if our underlay dependencies grow.

* Source build before
  * 39m54.422s w/ `--no-cache`
* Source build after
  * 37m6.997s w/ `--no-cache`

### TODO:
- [ ]  Update Dockerfile path in automated build config on Dockerhub after merging.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@ruffsl is this potentially related? https://app.circleci.com/pipelines/github/ros-planning/navigation2/3806/workflows/edb0b21b-7d8b-4a41-b1a7-c69c7c07582a/jobs/14777 Started around the time we updated this.

**Comment by ruffsl** [comment]
The only change to the Dockerfile used for CI was the optional test snippet, and is not invoked by Docker Hub:

https://github.com/ros-planning/navigation2/pull/1995/files#diff-3254677a7917c6c01f55212f86c57fbf

Looks like it's a c++ error uncovered by upstream changes in the nightly build, coincidental with the timing of this PR is my guess:

```
/opt/overlay_ws/src/navigation2/nav2_waypoint_follower/src/waypoint_follower.cpp:168:87: error: no match for ‘operator=’ (operand types are ‘rclcpp_action::Client&lt;nav2_msgs::action::NavigateToPose&gt;::GoalResponseCallback’
...
```

**Comment by SteveMacenski** [comment]
Yeah, that's what I assumed as well, just checking

**Comment by ruffsl** [comment]
Looks like 182d3b3 still builds FROM `ros:foxy` and `ros:rolling` : 

<details>

```
$ docker build -t nav2:latest --build-arg=FROM_IMAGE=ros:foxy .
[+] Building 923.8s (26/26) FINISHED                                                                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.1s
 => => transferring dockerfile: 3.01kB                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.1s
 => => transferring context: 224B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/ros:foxy                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                             0.7s
 => => transferring context: 72.28MB                                                                                                                                                                          0.6s
 => [cacher 1/8] FROM docker.io/library/ros:foxy                                                                                                                                                              0.1s
 => => resolve docker.io/library/ros:foxy                                                                                                                                                                     0.0s
 => [cacher 2/8] WORKDIR /opt/underlay_ws/src                                                                                                                                                                 0.1s
 => [builder 2/14] RUN apt-get update && apt-get install -q -y       ccache       lcov     && rosdep update     && rm -rf /var/lib/apt/lists/*                                                               23.9s
 => [cacher 3/8] COPY ./tools/underlay.repos ../                                                                                                                                                              0.1s
 => [cacher 4/8] RUN vcs import ./ < ../underlay.repos &&     find ./ -name ".git" | xargs rm -rf                                                                                                             3.2s
 => [cacher 5/8] WORKDIR /opt/overlay_ws/src                                                                                                                                                                  0.1s
 => [cacher 6/8] COPY ./ ./navigation2                                                                                                                                                                        0.6s
 => [cacher 7/8] WORKDIR /opt                                                                                                                                                                                 0.1s
 => [cacher 8/8] RUN mkdir -p /tmp/opt &&     find ./ -name "package.xml" |       xargs cp --parents -t /tmp/opt &&     find ./ -name "COLCON_IGNORE" |       xargs cp --parents -t /tmp/opt || true          0.7s
 => [builder 3/14] WORKDIR /opt/underlay_ws                                                                                                                                                                   0.1s 
 => [builder 4/14] COPY --from=cacher /tmp//opt/underlay_ws ./                                                                                                                                                0.1s 
 => [builder 5/14] RUN . /opt/ros/foxy/setup.sh &&     apt-get update && rosdep install -q -y       --from-paths src       --skip-keys "         slam_toolbox         "       --ignore-src     && rm -rf /  208.6s 
 => [builder 6/14] COPY --from=cacher /opt/underlay_ws ./                                                                                                                                                     0.3s 
 => [builder 7/14] RUN . /opt/ros/foxy/setup.sh &&     colcon build       --symlink-install       --mixin release ccache       --event-handlers console_direct+     || ([ -z "True" ] || exit 1)            257.3s 
 => [builder 8/14] WORKDIR /opt/overlay_ws                                                                                                                                                                    0.0s 
 => [builder 9/14] COPY --from=cacher /tmp//opt/overlay_ws ./                                                                                                                                                 0.1s 
 => [builder 10/14] RUN . /opt/underlay_ws/install/setup.sh &&     apt-get update && rosdep install -q -y       --from-paths src         /opt/underlay_ws/src       --skip-keys "         slam_toolbox       39.3s 
 => [builder 11/14] COPY --from=cacher /opt/overlay_ws ./                                                                                                                                                     0.6s 
 => [builder 12/14] RUN . /opt/underlay_ws/install/setup.sh &&     colcon build       --symlink-install       --mixin release ccache     || ([ -z "True" ] || exit 1)                                       370.7s 
 => [builder 13/14] RUN sed --in-place       's|^source .*|source "$OVERLAY_WS/install/setup.bash"|'       /ros_entrypoint.sh                                                                                 0.4s 
 => [builder 14/14] RUN if [ -n "$RUN_TESTS" ]; then         . install/setup.sh &&         colcon test &&         colcon test-result           || ([ -z "True" ] || exit 1)     fi                            0.5s 
 => exporting to image                                                                                                                                                                                       21.6s 
 => => exporting layers                                                                                                                                                                                      21.5s 
 => => writing image sha256:5e3ee1f822932bb6bf2170c3e3ce82a00e93108f2ac44ea40259aac85433eb8f                                                                                                                  0.0s 
 => => naming to docker.io/library/nav2:latest 
```

```
docker build -t nav2:latest --build-arg=FROM_IMAGE=ros:rolling .
[+] Building 925.7s (26/26) FINISHED                                                                                                                                                                               
 => [internal] load .dockerignore                                                                                                                                                                             0.1s
 => => transferring context: 35B                                                                                                                                                                              0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.1s
 => => transferring dockerfile: 38B                                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/ros:rolling                                                                                                                                                1.4s
 => [internal] load build context                                                                                                                                                                             0.1s
 => => transferring context: 61.67kB                                                                                                                                                                          0.1s
 => [cacher 1/8] FROM docker.io/library/ros:rolling@sha256:b3d59052bf5aa6ff39cfbf91b675f5c5fc9aa3d0d2947ef2d7fecf63e4f7c88a                                                                                  13.3s
 => => resolve docker.io/library/ros:rolling@sha256:b3d59052bf5aa6ff39cfbf91b675f5c5fc9aa3d0d2947ef2d7fecf63e4f7c88a                                                                                          0.0s
 => => sha256:b3d59052bf5aa6ff39cfbf91b675f5c5fc9aa3d0d2947ef2d7fecf63e4f7c88a 549B / 549B                                                                                                                    0.0s
 => => sha256:70dd5c5d7ac88cbd1920bf73a4ac9b0e3e759f43566ea6fe7869ec43c9654288 7.26kB / 7.26kB                                                                                                                0.0s
 => => sha256:295deae1499b75745f88e8e8fe279724f5e40f6774db3c6bdea8010f9bd88743 119.29MB / 119.29MB                                                                                                            2.9s
 => => sha256:96540f5ca02d4ea3af9919875e57c207f7b6d5eb4e6f83f7e14f152c725af321 3.04kB / 3.04kB                                                                                                                0.0s
 => => sha256:f72732fc2b062a35d766fe52f713a21ea53b4e805c8eabbb5e1d3e8deda04bdf 195B / 195B                                                                                                                    0.3s
 => => sha256:c1e22f799f4b3375517daed48011be12413233d9f09cc99a8369f847f3d7bc97 66.58MB / 66.58MB                                                                                                              1.9s
 => => sha256:03e9b1b30d496929de95e872f6d922b3cff405f677119d38fb2436fcc103ce01 187.91kB / 187.91kB                                                                                                            1.4s
 => => sha256:e3ac5c4bac57e4ea1bd6c9b63fe3f4a3690dca2d532594928867bf7bed26750c 1.97kB / 1.97kB                                                                                                                1.6s
 => => sha256:e80dd9e91f2a2f65c1a9450590508516bbe098718b3908752cf323b466e7df19 10.28MB / 10.28MB                                                                                                              3.7s
 => => extracting sha256:295deae1499b75745f88e8e8fe279724f5e40f6774db3c6bdea8010f9bd88743                                                                                                                     6.6s
 => => extracting sha256:f72732fc2b062a35d766fe52f713a21ea53b4e805c8eabbb5e1d3e8deda04bdf                                                                                                                     0.0s
 => => extracting sha256:c1e22f799f4b3375517daed48011be12413233d9f09cc99a8369f847f3d7bc97                                                                                                                     2.1s
 => => extracting sha256:03e9b1b30d496929de95e872f6d922b3cff405f677119d38fb2436fcc103ce01                                                                                                                     0.1s
 => => extracting sha256:e3ac5c4bac57e4ea1bd6c9b63fe3f4a3690dca2d532594928867bf7bed26750c                                                                                                                     0.0s
 => => extracting sha256:e80dd9e91f2a2f65c1a9450590508516bbe098718b3908752cf323b466e7df19                                                                                                                     0.7s
 => [builder 2/14] RUN apt-get update && apt-get install -q -y       ccache       lcov     && rosdep update     && rm -rf /var/lib/apt/lists/*                                                               21.5s
 => [cacher 2/8] WORKDIR /opt/underlay_ws/src                                                                                                                                                                 0.3s
 => [cacher 3/8] COPY ./tools/underlay.repos ../                                                                                                                                                              0.0s
 => [cacher 4/8] RUN vcs import ./ < ../underlay.repos &&     find ./ -name ".git" | xargs rm -rf                                                                                                             5.3s
 => [cacher 5/8] WORKDIR /opt/overlay_ws/src                                                                                                                                                                  0.0s
 => [cacher 6/8] COPY ./ ./navigation2                                                                                                                                                                        0.5s
 => [cacher 7/8] WORKDIR /opt                                                                                                                                                                                 0.1s
 => [cacher 8/8] RUN mkdir -p /tmp/opt &&     find ./ -name "package.xml" |       xargs cp --parents -t /tmp/opt &&     find ./ -name "COLCON_IGNORE" |       xargs cp --parents -t /tmp/opt || true          0.7s
 => [builder 3/14] WORKDIR /opt/underlay_ws                                                                                                                                                                   0.1s
 => [builder 4/14] COPY --from=cacher /tmp//opt/underlay_ws ./                                                                                                                                                0.1s 
 => [builder 5/14] RUN . /opt/ros/rolling/setup.sh &&     apt-get update && rosdep install -q -y       --from-paths src       --skip-keys "         slam_toolbox         "       --ignore-src     && rm -r  215.0s 
 => [builder 6/14] COPY --from=cacher /opt/underlay_ws ./                                                                                                                                                     0.4s 
 => [builder 7/14] RUN . /opt/ros/rolling/setup.sh &&     colcon build       --symlink-install       --mixin release ccache       --event-handlers console_direct+     || ([ -z "True" ] || exit 1)         256.4s 
 => [builder 8/14] WORKDIR /opt/overlay_ws                                                                                                                                                                    0.1s 
 => [builder 9/14] COPY --from=cacher /tmp//opt/overlay_ws ./                                                                                                                                                 0.1s 
 => [builder 10/14] RUN . /opt/underlay_ws/install/setup.sh &&     apt-get update && rosdep install -q -y       --from-paths src         /opt/underlay_ws/src       --skip-keys "         slam_toolbox       40.2s 
 => [builder 11/14] COPY --from=cacher /opt/overlay_ws ./                                                                                                                                                     0.6s 
 => [builder 12/14] RUN . /opt/underlay_ws/install/setup.sh &&     colcon build       --symlink-install       --mixin release ccache     || ([ -z "True" ] || exit 1)                                       354.0s 
 => [builder 13/14] RUN sed --in-place       's|^source .*|source "$OVERLAY_WS/install/setup.bash"|'       /ros_entrypoint.sh                                                                                 0.5s 
 => [builder 14/14] RUN if [ -n "$RUN_TESTS" ]; then         . install/setup.sh &&         colcon test &&         colcon test-result           || ([ -z "True" ] || exit 1)     fi                            0.4s 
 => exporting to image                                                                                                                                                                                       21.3s 
 => => exporting layers                                                                                                                                                                                      21.2s 
 => => writing image sha256:94e6c010052f18eec270a2b82beb3dc4f6836a2c0c65a7c9a91b348549c9e611                                                                                                                  0.0s 
 => => naming to docker.io/library/nav2:latest
```

**Comment by SteveMacenski** [comment]
What does that mean?

**Comment by ruffsl** [comment]
For triage: i.e. the breaking change hasn't yet been released into ros2 rolling, and it didn't originate first on our end.

**Comment by SteveMacenski** [comment]
Awesome, thanks!

**Pull request merged**
