### PR TITLE
fix some tests

### PR DESCRIPTION
**Pull request by wep21**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |

---

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
There's 1 linting error `copyright=Intel Corporation. (2018), Florian Gramss (2020), license=<unknown>` but otherwise the other 3 tests are usually flaky so I assume those are actually fine if everything else is working now!

Thanks for taking this on! What's the next steps here / changes you have in your fork that need to be made here to have CI turn over for Rolling?

**Comment by wep21** [comment]
@SteveMacenski Could you create a jammy based builder image like
`docker build . -t ghcr.io/ros-planning/navigation2:main-jammy --target builder` and push it because I don't have a write access to this organization? (How you tag the image is up to you.) I will change the base image after that.

**Comment by SteveMacenski** [comment]
@ruffsl should the user rebase? CI failing with gazebo/ros/dev/plugins and similar missing. I retriggered CI in case it was just an order thing

**Comment by wep21** [comment]
@SteveMacenski I fixed tests except for costmap filters, and I found out bt_navigator is never activated because

**Comment by SteveMacenski** [comment]
The issue I see in CI first is `Failed to load node 'controller_server' of type 'nav2_controller::ControllerServer' in container 'nav2_container': Component constructor threw an exception: parameter 'goal_checker_plugins' has invalid type: Wrong parameter type, parameter {goal_checker_plugins} is of type {string_array}, setting it to {string} is not allowed.`

Which is weird, some PR rebasing weirdness must have reverted that, AlexeyMerzlyakov  fixed that a few weeks ago. If you change 
- https://github.com/ros-planning/navigation2/blob/main/nav2_system_tests/src/costmap_filters/keepout_params.yaml#L112
- https://github.com/ros-planning/navigation2/blob/main/nav2_system_tests/src/costmap_filters/speed_global_params.yaml#L114
- https://github.com/ros-planning/navigation2/blob/main/nav2_system_tests/src/costmap_filters/speed_local_params.yaml#L114

to `goal_checker_plugins: ["goal_checker"]` that should handle the issue. Or maybe you need to pull in changes and your base branch is out of date? 

That could cause the lifecycle manager to fail bringup if the controller server can't be activated so it can't active the BT navigator server. If it did, somehow, get into the activate state, the `loadBehaviorTree` is called and could hang because we'd be infinitely waiting for the Controller Server to come up https://github.com/ros-planning/navigation2/blob/8a007c8eee054de3a91bddfe80e8c26e0b666fde/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp#L93 which it won't ever.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/2974 I opened this to see if that change fixes all of the issues, but I suspect it will

**Pull request merged**
