### PR TITLE
Prepare test results to only use junit/xunit schema

### PR DESCRIPTION
**Pull request by ruffsl**
To try and help CircleCI to parse the output file. 

- https://stackoverflow.com/a/70774733/2577586
- https://colcon.readthedocs.io/en/released/reference/verb/test.html#cmake-specific-arguments

Fixes: #3437

### CODE REVIEW

**Comment by ruffsl** [comment]
Looks like the generated `Test.xml` of test summary, enabled the default dashboard options in colcon, is written to disk after the optional junit file.

https://github.com/colcon/colcon-cmake/blob/8f1b92a190b2ad4289ecf837c3200d540c13fdd9/colcon_cmake/task/cmake/test.py#L73-L74

https://github.com/Kitware/CMake/blob/d6d847607c5f312c9b85605c8a4596377275a34b/Source/cmCTest.cxx#L2458-L2459

So perhaps I could just add to the `Copy Test Logs` run step in our CI to rename these `Testing/TAG/Test.xml` files to `Testing/TAG/Test.txt` to avoid the CI from trying to parse them as junit xml files.

**Comment by ruffsl** [comment]
For reference, as to why dashboard causes a `Test.xml` to be generated:

> When run as a [Dashboard Client](https://cmake.org/cmake/help/latest/manual/ctest.1.html#dashboard-client), CTest will include these custom measurements in the Test.xml file that gets uploaded to CDash.

https://cmake.org/cmake/help/latest/command/ctest_test.html#additional-test-measurements

**Comment by ruffsl** [comment]
@SteveMacenski , it looks like the junit files from ctest are finally being tracked here, although I'm not sure if this adds any duplication to test reporting. The test timing seems different from ctest, but some of the stdout is the same, but not all of it.

## Before

> Tests: 2 tests failed  out of **3167**
https://app.circleci.com/pipelines/github/ros-planning/navigation2/8912/workflows/2f9ce04f-74df-4aba-93cc-b37e48477ce8/jobs/29176

## After

> Tests: 6 tests failed  out of **3449**
https://app.circleci.com/pipelines/github/ros-planning/navigation2/8917/workflows/ecce15f8-8be6-45ef-914a-1a42fae1a065/jobs/29186/tests

**Comment by ruffsl** [comment]
@cottsay this PR for fixing CI seems a little hackish, is there a better way of doing this with cmake and colcon?

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
> although I'm not sure if this adds any duplication to test reporting

Looking at the actual failures, it does dual report them - if you look at the CI tests that failed, its actually 3 failures each reported twice. Once for the actual test failure and another for the summary. This is also how it looks from `colcon test-result --verbose` 

If that duplication is necessary to fix the issue, I'm OK with that

**Comment by SteveMacenski** [comment]
What's the story here?

**Comment by cottsay** [comment]
Can someone summarize what's actually in question here? CircleCI has a problem parsing...the default ctest output? I'm not sure what the goal is.

**Comment by ruffsl** [comment]
> What's the story here?

@SteveMacenski , I've been thinking, I kinda feel the duplication of test results is still really goofy. For contributors to see duplicate test results just seems unhelpful and confusing, particularly if you need to sort through a number of failures, or are just narrowing down the ones that are relevant to your PR or issue of interest. So perhaps we just forget the ctest junit output, and only upload the Test.xlm as artifacts instead, then prune them before uploading the rest of the xlm results.

> Can someone summarize what's actually in question here? CircleCI has a problem parsing...the default ctest output? I'm not sure what the goal is.

@cottsay , yeah. Looks like ctest has its own proprietary format, that doesn't conform to any standardized schema used by most other testing frameworks, like xunit/junit. It's kind of odd, so most CI services don't know how to ingest such obscure result formats. I'm guessing there is a plugin the build farm is using with Jenkins? Or are you all just tossing out the generated Test.xml files as well? Those files still seem to include some additional useful info, like compiler flags and versions used. But the junit files that ctest generates is devoid of all that detail, and just repeats the stdout already includes in linter/gtest junit test results, that I'm guessing ctest originally kicks off from cmake.

**Comment by SteveMacenski** [comment]
> So perhaps we just forget the ctest junit output, and only upload the Test.xlm as artifacts instead

What does the junit output contain? Is that the full logs from the run or the summary file? Having the full output logs even if the thing crashed is useful to know why to debug. 

E.g. which will be kept `test_single_trigger_node` or `test_behavior` that is reported in this output job for instance (or `test_costmap_publisher_exec` vs `test_costmap_publisher_exec.missing_result`)

**Comment by ruffsl** [comment]
BTW, while looking closer at the cppcheck testcase in the files above, I noticed:

```xml
<skipped type="skip" message="">
    ![CDATA[Test Skipped due to cppcheck 2.7 performance issues]]
</skipped>
```

``` xml
				<Measurement>
					<Value>-- run_test.py: invoking following command in '/opt/overlay_ws/src/navigation2/nav2_dwb_controller/costmap_queue':
 - /opt/ros/rolling/bin/ament_cppcheck --xunit-file /opt/overlay_ws/test_results/costmap_queue/cppcheck.xunit.xml --include_dirs /opt/overlay_ws/src/navigation2/nav2_dwb_controller/costmap_queue/include
cppcheck 2.7 has known performance issues and therefore will not be used, set the AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS environment variable to override this.
-- run_test.py: return code 0
-- run_test.py: verify result file '/opt/overlay_ws/test_results/costmap_queue/cppcheck.xunit.xml'
</Value>
				</Measurement>
```

Searching into `AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS` further reveals:

-  https://github.com/ament/ament_lint/pull/345
- https://github.com/space-ros/space-ros/issues/39

This would perhaps explain the sudden spike in skipped test from last year. It seem most folks packages in ROS are just skipping cppcheck now? :/

**Comment by SteveMacenski** [comment]
> Those all seem to be gtest specific. Nothing being proposed here would alter how we already handle or upload any of our <name>.gtest.xml test result files.

I suppose that's what I was talking about with respect to duplication - after these changes we have both sets show up in our CI test failure pop up results. I'm not sure what other duplication you mean, but if not that, use your best justement.

**Pull request merged**
