### PR TITLE
Use arrow markers for waypoints instead of circles

### PR DESCRIPTION
**Pull request by mlherd**
Using arrows instead of circles to shows the user robot's target pose (location and orientation)

This PR is a result of the conversation that I had with @yathartha3 a few weeks ago about how to use way point markers in a more efficient way.

arrow

PS: I guess I should have opened an issue about this first :)

### CODE REVIEW

**Comment by fmrico** [comment]
It looks nice :) I used spheres because the angle in the intermediate waypoints was not required, but using the arrows improves the visualization. Good idea :)

**Comment by yathartha3** [comment]
> the angle in the intermediate waypoints was not required

Just to understand better - the intermediate waypoints do have a 'pose' (position and orientation) correct? I am assuming, the robot would go to each waypoint (that particular position and orientation), and then go to the next one.
I am trying to understand what you mean by 'not required'

**Comment by fmrico** [comment]
Hi @yathartha3 

In the requirements section, in #803  it's written: 
> 2.2. The robot need only have the correct orientation of the final pose.
My comment was referring to this.

Right now, if I am not wrong, it is implemented as a sequence of `NavigateToPose` actions, so orientation is relevant, and this enhancement is useful and cool. If #803 is a guideline for a future new implementation, maybe orientation is not suitable, and perhaps it could be unavailable.

Best

**Comment by SteveMacenski** [comment]
My only issue is that if you use arrows, I think the waypoint should be in the middle of the arrow, not on a tip. I think that’s not a very intuitive visualization to have it at the end, even though that’s the easiest implementation solution

**Comment by yathartha3** [comment]
> waypoint should be in the middle of the arrow, not on the base.

@SteveMacenski  I think that is how it appears when you are giving the waypoints using RVIZ (at the base). So if we want to be consistent with how it appears in RVIZ while giving the goal, then we should keep it as it is.

**Comment by SteveMacenski** [comment]
Its not my first choice, but I’ll go with it

**Comment by mlherd** [comment]
Making it middle of the arrow will not be intuitive either. It complete depends on what an arrow means to the user. Not much I can do with the default markers, but here is another option.

ac

**Comment by SteveMacenski** [comment]
I like that as a compromise.

**Comment by SteveMacenski** [comment]
@mlherd you have 3 approvals, can this go in?

**Pull request merged**
