### PR TITLE
Added missing virtual destructor

### PR DESCRIPTION
**Pull request by VineetTambe**
## Basic Info

Added the missing empty virtual destructor which prevented package building of nav2_mppi_controller. 

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | - |
| Primary OS tested on | Ubuntu 22.04 
| Robotic platform tested on | ROS2 Humble + simulation setup used -> NeoBotix sim mp400 robot

---
Added the missing empty virtual destructor which prevented package building of nav2_mppi_controller. 
A simple enough one-liner fix which allowed for the package to build

## Description of documentation updates required from your changes
No documentation update required

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by VineetTambe** [comment]
PR from main to main as opposed to the wrong branch in [this PR](https://github.com/ros-planning/navigation2/pull/3812)

**Comment by SteveMacenski** [comment]
@VineetTambe heed the build failures.

**Comment by SteveMacenski** [comment]
@VineetTambe is it only missing in Humble (what about Iron)? 

If so, reopen the Humble (and Iron?) PR and I can merge. Sorry about the whiplash, I didn't know we already resolved this issue in Main :-)

**Comment by VineetTambe** [comment]
Closing this PR and re-opening the previous one.

**Comment by VineetTambe** [comment]
> @VineetTambe is it only missing in Humble (what about Iron)?
> 
> If so, reopen the Humble (and Iron?) PR and I can merge. Sorry about the whiplash, I didn't know we already resolved this issue in Main :-)

@SteveMacenski it's only missing in humble for some reason. It is there in iron.

**Pull request closed without merging**
