### PR TITLE
Cleaning up warnings and errors detected by clang.

### PR DESCRIPTION
**Pull request by crdelsey**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | NA |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | NA |
| Clang version | clang version 6.0.0-1ubuntu2 |

---

## Description of contribution in a few bullet points

* Fixing miscellaneous errors detected by clang. Many real defects. Some just unused variables.

### CODE REVIEW

**Comment by rotu** [comment]
@crdelsey looks like you removed the library nav2_util_core from nav2_util/CMakeLists.txt which is breaking the build for me. Accident or am I missing something? https://github.com/ros-planning/navigation2/blob/master/nav2_util/CMakeLists.txt

**Comment by crdelsey** [comment]
@rotu Thanks for pointing this out. Do you have a workaround or are you blocked right now?

**Comment by rotu** [comment]
@crdelsey My current workaround is to install cmake via pip. The [binary distribution on PyPi](https://pypi.org/project/cmake/) is version 3.14.4.

**Comment by corsaircpt** [comment]
causes issue https://github.com/ros-planning/navigation2/issues/856 . Is there another solution short of changing Cmake itself?

**Pull request merged**
