### PR TITLE
Remove code for DWA to DWB migration

### PR DESCRIPTION
**Pull request by wilcobonestroo**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #2026 |
| Primary OS tested on | Ubuntu |

---

## Description of contribution in a few bullet points
The file parameters.hpp contained the code to migrate from DWA to DWB. As this in not needed in ROS 2, the code can be removed. This also increases test coverage as the file was not fully covered.

### CODE REVIEW

**Comment by wilcobonestroo** [comment]
I thought that the code was used in other parts of Navigation 2, but it builds fine without the file.

**Comment by naiveHobo** [comment]
>  but it builds fine without the file.

`parameters.hpp` is being used in several of the DWB plugins. The header is probably available in the install directories from your previous builds on your system, a clean build will fail.

**Comment by wilcobonestroo** [comment]
I think it did not actually rebuild on my machine. There are other files using this one.


> > but it builds fine without the file.
> 
> `parameters.hpp` is being used in several of the DWB plugins. The header is probably available in the install directories from your previous builds on your system, a clean build will fail.

Yes, I noticed. I will look into it.

**Comment by SteveMacenski** [comment]
`searchAndGetParam` I  think is a legit used function. And all of these functions are used somewhere, yeah you'll need to remove the deprecated support functions that use these - which shouldn't be too hard to track down. I think they're all in the DWB local planner plugin file. But if you track down all the uses of these functions, it'll lead you recursively to all of them.

**Comment by wilcobonestroo** [comment]
So should only `loadParameterWithDeprecation` and `moveDeprecatedParameter` be removed and `moveParameter` and `searchAndGetParam` are ligit?

**Comment by SteveMacenski** [comment]
I don't know, look at the files where its used and see if they're used for normal purposes or in deprecation support.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/3dd5eec73bafd9232d066d6789b2eff2ac7c0af1/nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp#L254-L267

Take a deeper look into DWB and don't push updates until you remove all the deprecated parameter support. There's a bunch of other places doing this still.

**Comment by wilcobonestroo** [comment]
I am sorry. I am still working on it. I won't push updates until I think they are all gone.

**Comment by SteveMacenski** [comment]
@wilcobonestroo it just spins up CI every push you make which takes compute resources from other PRs that are trying to merge (we're limited to only 3-4 concurrent jobs) and I get notifications about every push :wink:

**Comment by wilcobonestroo** [comment]
I think this was the last one for this PR.

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
