### PR TITLE
Fix system_tests flaky issue

### PR DESCRIPTION
**Pull request by AlexeyMerzlyakov**
Testing PR for reproduce Issue No.1 from ticket #1585

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Rebase on master. Those have been fixed

**Comment by AlexeyMerzlyakov** [comment]
> Rebase on master. Those have been fixed

I've intentionally cherry-picked this commit from master in order to try to reproduce the problem on old branch. On latest master I've already tried unsuccessfully. Currently, I see the flaky test looks like disappeared in CI.

**Comment by SteveMacenski** [comment]
You intentionally want all the cppcheck issues and map server not returning a result?

**Comment by AlexeyMerzlyakov** [comment]
In this testing PR there is a lot of mess. I've tried both cases - to move `test-issue1` branch over latest master with enabling system testing back (commit ID: e2e8e70) and moving `test-issue1` branch over reference commit where timeout problem was actually detected. Here was required some back-port from master which you've seen previously. I've checked - both cases did not give me a positive result: testing of `test_planner_random` passes w/o timeouts we saw previously.
Returning back `test-issue1` branch over latest master to be consistent.

However, I've detected (and looks like fixed) another problem concerned with `test_planner_costmaps` failure on release testing only in Focal Fossa. I will describe it in the #1585 ticket since it will require some actions, I think.

**Comment by SteveMacenski** [comment]
OK, @AlexeyMerzlyakov you still have failures for linting. It doesn't look like it was from your changes but do you mind taking care of those here? 

I would like to have this test run 10x in a row without failing (except for the action utils, which is another subject altogether)

**Pull request merged**
