### PR TITLE
Getting Build Farm CI on track

### PR DESCRIPTION
**Pull request by SteveMacenski**
- adding missing rosdeps to package xmls
- dealing with failing costmap tests
- fixing tests in map server
- throttling while loops that dont need to be running at 100% core speed

@mkhansen-intel @mjeronimo @orduno @mhpanah @crdelsey  its super super important that anytime you add a find_package that is a rosdep key and not in the repo, you need to add it to the package.xml under the rosdep key name, for now the travis build system is set up and not isolated, this will not be testable in this repo but will create nightmares for me to release debians (and anger the kind folks at OSRF). I'm going to go right now through every file in every package to get them all in, but in the future its important for isolation builds the way the debians are generated

### CODE REVIEW

**Comment by SteveMacenski** [comment]
^ first build where PR builder succeeds :1st_place_medal: :yay:

**Comment by SteveMacenski** [comment]
Since we're running on bouncy docker images and a crystal image (or following the same bootstrap guides to make our own "crystal" image), these PRs may break travis CI, but then we should be able to rely on the ROS Build Farm PR Builder instead, which is a good step as it will run all the tests and and prep it like it was going to be deployed. 

I'd like to keep a functioning docker file / image about, but I'm not sure the best mechanics to do it. Any suggestions?

**Comment by SteveMacenski** [comment]
Builds are failing right now from fetching to the build farm - I think there's some serious load and the apt requests aren't getting through. Will try back tomorrow.

**Comment by SteveMacenski** [comment]
toggling CI

**Comment by SteveMacenski** [comment]
This is ready to go, please review tomorrow so I can get in and deploy a new release on Monday morning at noon as we discussed

**Comment by mkhansen-intel** [comment]
Merging

**Comment by SteveMacenski** [comment]
Boost is needed (was in the CmakeLists, if its not needed at all then CMake could reflect it) - the other items - yes there are some like gtest/launch I just put everywhere to future proof.

**Comment by nuclearsandwich** [comment]
[Build Status](http://build.ros2.org/job/Cdev__navigation2__ubuntu_bionic_amd64/14/) the devel job after this merge passed as well :confetti_ball:

**Comment by nuclearsandwich** [comment]
> Boost is needed (was in the CmakeLists, if its not needed at all then CMake could reflect it) - the other items - yes there are some like gtest/launch I just put everywhere to future proof.

:+1: In general I recommend any package that is explicitly required be added as a dependency even if it is pulled in by another depended-upon package as it insulates against future changes of that dependency.

**Comment by SteveMacenski** [comment]
@nuclearsandwich exactly. This is my philosophy as well. I also like to include basic things people frequently forget to include when enabling (test depends, launch for a new launch file, etc)

**Comment by SteveMacenski** [comment]
@mkhansen-intel my plan in to bump tags and re-run bloom at noon, if you need me to delay or have any questions, feel free to email or call

**Pull request merged**
