### PR TITLE
Reduce the number of tests run in Travis to just a single system test.

### PR DESCRIPTION
**Pull request by crdelsey**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | NA |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | CI |

---

## Description of contribution in a few bullet points

* Travis is frequently timing out due to the number of tests that have been added. This PR turns them all off except for Dynamic Obstacle. That test should cover the vast majority of the functionality that the others cover without being overly time consuming.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@crdelsey at this point, wouldn't it make sense just to run none of the integration tests?

**Comment by crdelsey** [comment]
> at this point, wouldn't it make sense just to run none of the integration tests?

What's the point of Travis now? I'd say it's purpose is to provide a second opinion if Circle CI is failing mysteriously. By keeping both a build and a test run in Travis, we get a second opinion on both those kinds of failures in Circle.

I can't remember though if we've had a pass in Travis but failures in Circle in a while though. I'm just trying to keep Travis going so long as it's easy, to give it a chance to prove it still has worth. :-)

**Comment by SteveMacenski** [comment]
We have had travis success on Circle failures before, yes. Usually when the caching is broken or the nightly build is broken

**Comment by crdelsey** [comment]
Closing this PR. I'll add it to #1340 instead.

**Pull request closed without merging**
