### PR TITLE
store shared files in share/{PROJECT_NAME} rather than share/

### PR DESCRIPTION
**Pull request by Jconn**
fixes: https://github.com/ros-planning/navigation2/issues/1480

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Can you submit this patch for Dashing and Eloquent for each of these repos? 

I’ll release new debians for all of them tomorrow.

**Comment by mikaelarguedas** [comment]
@SteveMacenski Is it possible to make a new release of these packages? it is still not possible to install them side by side even after the recent eloquent sync https://discourse.ros.org/t/new-packages-for-eloquent-elusor-2020-02-20/12895

**Comment by SteveMacenski** [comment]
I'll look at it today but its not clear to me what the last commit that was cherry picked over. @cdelsey might be able to make that clear to me so I can move forward.

At the moment, I'm at a stand still unless someone else can do it or make it clear to me where to start off

**Comment by mikaelarguedas** [comment]
thanks @SteveMacenski :+1:
If easier for you, is it possible to release `spatio_temporal_voxel_layer` and `nonpersistent_voxel_layer` regardless of when navigation2 get a new release? This would fix the fact that the packages are conflicting

**Comment by SteveMacenski** [comment]
I can do that - but it also doesn't solve the larger issue of my (apparent) inability to figure out how to cherry pick over to a branch looking at the current state of the branch. I'm inclined to try to solve the core problem than kicking the can down the road.

**Comment by SteveMacenski** [comment]
STVL: https://github.com/ros/rosdistro/pull/23864

NPVL: https://github.com/ros/rosdistro/pull/23865

Though note: the last Nav update moves the costmaps yaml file inside its own package. I think that makes it such that it can be in the same system as STVL since its still global. It would cause an issue if you had both of them, but otherwise shouldnt be an issue anymore.

**Pull request merged**
