### PR TITLE
Add ament_export_libraries to map_server

### PR DESCRIPTION
**Pull request by maxlein**
This pr would allow one to derive from map_server lib in another package to add custom functionality.

### CODE REVIEW

**Comment by maxlein** [comment]
Fixing also #1447

**Comment by SteveMacenski** [comment]
I think this would make bad lifecycle nodes timeout trying to transition. 

That could mask serious safety problems or configuration issues. In general I agree with adding timeouts to all calls, except lifecycle where I think its strictly required to succeed to bring up

**Comment by SteveMacenski** [comment]
I think perhaps lets do one thing at a time. Can we export the libraries so you can continue with that work while we discuss the game plan for handling missing lifecycle nodes?

**Comment by maxlein** [comment]
Removed service client refactoring

**Pull request merged**
