### PR TITLE
Changes to refresh crystal-devel branch

### PR DESCRIPTION
**Pull request by LeonJung**
This is the PR requested from @crdelsey in issue thread #682 

Also this seems related with what is mentioned in issue thread #728

# WARNING!!!!! USE JUST FOR LOOKING
**You must not pull this request to master branch**, since this PR used the modified master branch source pulled PREVIOUSLY in 05/16/2019 Korean time. Pulling this source will mess up your entire workstream

You should use this PR JUST FOR REFERENCING which is modified (only NodeOptions related stuffs were modified)... Other changes is come from master version difference.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Shouldn't this be targeting the crystal-devel branch if I read that ticket correctly?

**Comment by LeonJung** [comment]
@SteveMacenski

After my pull and modification, nav2 master branch was uploaded again, so you shouldn't.

**Comment by crdelsey** [comment]
@LeonJung Thanks for submitting this. I'll take this and update the crystal-devel branch.

**Comment by crdelsey** [comment]
Dashing release has been done. I'm closing this PR now. Crystal branch is going to be difficult to update due to the massive changes, so it's best if nobody uses that branch anymore.

**Pull request closed without merging**
