### PR TITLE
Use LLD linker

### PR DESCRIPTION
**Pull request by ruffsl**
To speed up CI builds.

cc @tylerjw

Related:

* https://github.com/colcon/colcon-mixin-repository/pull/28
* https://github.com/ros-planning/moveit2/pull/914

### CODE REVIEW

**Comment by SteveMacenski** [comment]
> colcon: error: Mixin 'lld' is not available for 'build'

**Comment by SteveMacenski** [comment]
Any update?

**Comment by tylerjw** [comment]
You are probably missing a `sudo apt-get install lld` somewhere.  We use industrial_ci so we specify that with a variable but you might add it to your builder docker image.

**Comment by ruffsl** [comment]
Below is a time comparison between LD and LLD for building nav2 from scratch with no caching:

| | LD Linker | LLD Linker |
|-|-|-|
| Debug Build | [50m 35s](https://app.circleci.com/pipelines/github/ros-planning/navigation2/6564/workflows/69b16047-04d6-4a82-9701-42ad9ce033de/jobs/24199) | [35m 1s](https://circleci.com/gh/ros-planning/navigation2/24489?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) |
| Release Build | [44m 39s](https://app.circleci.com/pipelines/github/ros-planning/navigation2/6564/workflows/69b16047-04d6-4a82-9701-42ad9ce033de/jobs/24200) | [31m 20s](https://circleci.com/gh/ros-planning/navigation2/24490?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) |

Note: Looks like just installing lld via apt changes the default linker used by the system, as the jobs from cbda05e didn't really change back the build times.

<details>

* https://circleci.com/gh/ros-planning/navigation2/24494
* https://circleci.com/gh/ros-planning/navigation2/24493

**Comment by tylerjw** [comment]
I didn't know that installing it via apt would change the default linker.  I'll see if I can reproduce that locally or find some evidence of that.

**Comment by scheunemann** [comment]
To test if LLC is used during build you can do `readelf --string-dump .comment install/<path_to_lib>` and check if LLC is mentioned.

**Pull request merged**
