### PR TITLE
change primitives to recoveries

### PR DESCRIPTION
**Pull request by SteveMacenski**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/691 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | CI |

---

## Description of contribution in a few bullet points

* Renamed the primitives to recoveries

---

### CODE REVIEW

**Comment by orduno** [comment]
Looks good, thanks for making the change.

**Comment by SteveMacenski** [comment]
@mkhansen-intel @mhpanah can I get a second review?

**Comment by SteveMacenski** [comment]
Can I get a second review for intent of renaming primitives with recoveries? @orduno @mjeronimo then I can fix the conflicts

**Comment by SteveMacenski** [comment]
Nice, ok will take care of this this afternoon. Next PR in this vein will be including a clear costmaps recovery. I know we have one defined in the tree, but that's different than having something supported in the now-recoveries package to encapsulate all those together.

**Comment by SteveMacenski** [comment]
@crdelsey merge conflicts resolved, waiting on CI then I'll ship

**Comment by crdelsey** [comment]
There is an expected CI failure at the moment -  #941. I'll leave it up to you if you want to merge if that is the only CI failure you see.

**Pull request merged**
