### PR TITLE
Enable Goal/PathAlign DWB critics, reduce forward_point_distance

### PR DESCRIPTION
**Pull request by jackpien**
Resolves ros-planning/navigation2#938

The forward_point_distance used in the GoalAlign and PathAlign critics projects the current pose forward a default 0.325 meters before scoring the trajectory. This can cause velocities that create sharp turns into obstacles to be chosen (reproducible with the Turtlebot3 simulation).

For TB3, which is small in size, 0.325 meters is too far. Instead, enable GoalAlign and PathAlign critics in the DWB controller and shorten the critics' forward_point_distance (how far the current pose is project given the current orientation before scoring the trajectory) from the default 0.325 meters to 0.1 meters which improves stability when running with TB3.

Signed-off-by: Jack Pien <jack@jackpien.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | 938 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | TB3 Simulation |

---

## Description of contribution in a few bullet points

* Enabled DWB GoalAlign critic by changing its scale factor from 0.0 to 24.0 in nav2_params.yaml
* Enabled DWB PathAlign critic by changing its scale factor from 0.0 to 32.0 in nav2_params.yaml
* Reduced the forward_point_distance from 0.325 (meters) to 0.1 (meters) in nav2_params.yaml to better tune for Turtlebot3's small size

## Description of documentation updates required from your changes

* For the GoalAlign and PathAlign critics, describe the forward_point_distance parameters (which defaults to 0.325 if not set in the YAML).

---

## Future work that may be required in bullet points

* Further fine tune the various DWB related (ie FollowPath) nav2_params.yaml for Turtebot3
* Look into doubling the scale of the BaseObstacle critic to compensate for the enabling of the GoalAlign and PathAlign critics.
* With forward_point_distance set back to its 0.325 default value where TB3 runs into an obstacle and raises a "no valid trajectory found" exception, bag the /evaluations topic to better understand why we get into this situation.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@jackpien I'm definitely not asking you to tune the controller, but I am asking "is behavior better with these new params than the old ones with it disabled?". Since you change the default configuration to enable this again, I'm just making sure that its better than when we had it shut off. 

Second question: What if the forward looking point is just 0.0 meters to be at the robot center, anything bad about that since its just the orientation critic? I think it may cause some slight instability in those critic results, but just verifying.

**Comment by jackpien** [comment]
> "is behavior better with these new params than the old ones with it disabled?".

Good questions - with the Goal and PathAlign critics, if weaving around obstacles, the velocities / trajectories taken should lead to an overall smoother, straighter path. This is primarily due to the projection forward of the current pose. 

> Second question: What if the forward looking point is just 0.0 meters to be at the robot center, anything bad about that since its just the orientation critic? I think it may cause some slight instability in those critic results, but just verifying.

With forward looking distance set to 0.0, we effectively have 2 GoalDist and 2 PathDist critics. The extra GoalDist vote might lead trajectories into obstacles, but the extra PathDist critic vote should pull the overall trajectory voted back on to the global planned path. As @shrijitsingh99 mentioned, it might be worth doubling the BaseObstacle critic scale. But given that I haven't seen any problems and I'm not too confident any of these variables are tuned for TB3 anyway, I didn't want to just tweak the other critic scales with some more extensive tests. But if you feel otherwise, I can definitely modify my PR to include a doubling of the Base Obstacle critic scale if that feel intuitively correct.

**Comment by SteveMacenski** [comment]
@jackpien I meant more in your gazebo testing anecdotally: would you say this is an improvement on the default behavior or not?

**Comment by jackpien** [comment]
> would you say this is an improvement on the default behavior or not?

Yes. For the test cases I ran in the TB3 simulation, the trajectories taken are shorter (yet still stable, ie does not run into obstacles), more direct versus curving around following along the global path which seems to me always maximizes the distance from obstacles.

As a thought exercise, I'm inclined to say yes as well, that the trajectories will be more optimal in all scenarios I can think of.

**Pull request merged**
