### PR TITLE
Trajectory visualizer namespaces

### PR DESCRIPTION
**Pull request by tonynajjar**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | N/A |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |

---

## Description of contribution in a few bullet points

* Added trajectory visualization namespaces. The computational-heavy one is the "Candidate Trajectories" but for me the useful one (most of the times) is the "Optimal Trajectory" so it would be nice to be able to choose from rviz

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Check CI: There are linting errors

**Comment by SteveMacenski** [comment]
hah my dyslexia totally missed that typo :laughing:

**Comment by tonynajjar** [comment]
seems like CI fail for another reason

**Comment by SteveMacenski** [comment]
I've not seen that before, maybe a test wasn't updated fully? Retriggering CI.

**Comment by doisyg** [comment]
Nice, I was actually about to do the same

**Pull request merged**
