### PR TITLE
Log level

### PR DESCRIPTION
**Pull request by jwallace42**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | None |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Gazebo |

---

## Description of contribution in a few bullet points
Adds ability to set log level for nodes that are launched. 

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
I think this misses some stuff, namely the composition nodes in localization / navigation / etc

**Comment by jwallace42** [comment]
So, 

you can't set the log level of individual components :( only the container that holds the components. I guess this makes sense but it would be nice to be able to set the log levels of each component.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@jwallace42 rerunning CI, an unusual failure occurred. I don't think its your fault, but want to just check again.

**Comment by SteveMacenski** [comment]
Can you rebase on main? I'm seeing that same error again which I'm not seeing on other PRs in some utils action server unit tests.

**Comment by SteveMacenski** [comment]
The PR got a little messed up, its showing a bunch of other commits.

**Comment by jwallace42** [comment]
So, 

I think this fixed it. I have to add a pr for some linting fixes that didn't get in on https://github.com/ros-planning/navigation2/pull/3114.

**Comment by tonynajjar** [comment]
What's the main reason to implement this? I'd imagine to see the debug logs? Running it in debug mode is unreadable because of all the "sub-loggers" like rcl

**Comment by SteveMacenski** [comment]
I didn’t ask, it seemed like a reasonable request to expose that as a CLI option

**Comment by tonynajjar** [comment]
Alright, to have useful readable debug logs only from Nav2, I'd recommend looking into changing the severity from individual loggers. It's available since galactic

https://docs.ros.org/en/galactic/Tutorials/Demos/Logging-and-logger-configuration.html

**Pull request merged**
