### PR TITLE
Rename AMCL parameters for global frame 

### PR DESCRIPTION
**Pull request by drhieu**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |

---

## Description of contribution in a few bullet points
- Update AMCL_node parameters to match other node parameters name for Frames (global, base, odom)
- Allows "Quote" or Unquote values to be use inside yaml config file.

## Description of documentation updates required from your changes

---

### CODE REVIEW

**Comment by SteveMacenski** [comment]
So a few things here:
- This looks good to me, but don't submit PRs directly to the distribution branches. We work on the main branch and then cherry pick commits to the distributions that should get those changes.
- This can't actually be rolled back to Foxy because you're breaking the ABI compatibility. For the `N` users using this in Foxy, this would break their configurations mid-distribution. We can only make API and ABI changes between distros so these changes would be represented in Galactic at earliest. 
- These changes need to be updated in the markdown file in this repo with all the parameters. It also needs to be update on the navigation website (navigation.ros.org) repo under ros-planning pages for AMCL's parameters & Galactic migration guide notification of change.

@ruffsl See the build errors in Circle `Error response from daemon: manifest for rosplanning/navigation2:master.debug not found`, did we update Dockerhub / CI appropriately? I know this is targeted to Foxy not main, so it might be an old config, but I don't know why the docker file wouldn't exist.

**Comment by ruffsl** [comment]
Each PR/Branch uses the CI config it self contains, not necessarily the one presently in the main default branch. The Dockerfile is still in the branch, but the docker image tag for master was cleared from DockerHub. We could add distro level docker image tags for release branches to CI from, that could derive from library/ros:<distro> rather than osrf/ros2:nightly archives.

**Comment by SteveMacenski** [comment]
OK, makes sense, I didn't know that we had cleared the old docker images. For already released distros, I'm also fine just using the PR builder as the main CI source since that's all setup correctly for it.

**Comment by drhieu** [comment]
Okay that makes sense, but do I need to do anything else on my end?. or
should i wait until Galactic and submit another PR? Should I open the issue
(#1945)?

**Comment by ruffsl** [comment]
I think @SteveMacenski is requesting you rebase and retarget this PR to the `main` development branch instead, and to include appropriate updates to the documentation here, as well as a respective PR to migration page in the website repo.

**Comment by SteveMacenski** [comment]
Exactly

**Comment by SteveMacenski** [comment]
Pinging @drhieu

**Comment by drhieu** [comment]
there is another PR now on the main branch and main branch of navigation-ros-org

**Comment by SteveMacenski** [comment]
OK, closing this then

**Pull request closed without merging**
