### PR TITLE
added nav2_common

### PR DESCRIPTION
**Pull request by jwallace42**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | NONE |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | NONE |

---

## Description of contribution in a few bullet points
Added nav2_common into the navigation2 package to keep cmake lists consistant. 

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Essentially every system test is failing in this PR

**Comment by jwallace42** [comment]
> Essentially every system test is failing in this PR

I just ran it locally with no issues. :( I would be kind of surprised it this change would would cause any tests to fail.

**Comment by SteveMacenski** [comment]
I retriggered it already but I can try again.

**Comment by jwallace42** [comment]
alright... well I am to close this then

**Pull request closed without merging**
