### PR TITLE
Add parallel planning and obstacle layer.

### PR DESCRIPTION
**Pull request by crdelsey**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | NA |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Turtlebot 3 |

---

## Description of contribution in a few bullet points

* Switches the default navigator to bt_navigator with the parallel replan configuration
* Enables obstacle layer in both global and local costmaps. This part duplicates what's in #630.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
A brief aside not to hold up this PR: why are local and global costmaps in nested namespaces?

ie
```
global_costmap:
  global_costmap:
    params: value
```

**Comment by crdelsey** [comment]
> A brief aside not to hold up this PR: why are local and global costmaps in nested namespaces?

The first `global_costmap` you see there is the namespace; the second is the node name. So, for instance, the costmap topic shows up as `/global_costmap/costmap`, not `/global_costmap/global_costmap/costmap`

**Comment by SteveMacenski** [comment]
Ah ok, I was confused because it didnt seem like `DwbController` or `map_server` had that.

**Comment by crdelsey** [comment]
DwbController and map_server and the others are just in the root namespace, so only the node name is listed for them.

The costmaps were put into namespaces since there are two otherwise identical instances and we didn't want them to conflict. We might have been able to leave them in the root namespace and rename all the topics they published so they wouldn't conflict, but it is not so clear how to do that for all the parameters they need to read. Those also can conflict, at least if you want to dynamically update them.

**Pull request merged**
