### PR TITLE
Get the costmap in the navfn constructor instead of inline

### PR DESCRIPTION
**Pull request by mjeronimo**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #540 |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | gazebo |

---

## Description of contribution in a few bullet points

Moves the code in navfn that calls the costmap service to get the costmap. Now, instead of calling this service inline every time a there is a request to generate a global plan, the call is made in the constructor. The code also now waits for the service to be available since otherwise, there is a race condition - the service request could be sent before the service is available and would never be received. 

---

## Future work that may be required in bullet points

* With the coming lifecycle changes, the navfn node will read the costmap in the on_configure callback. Changing the map will simply require bringing the relevant nodes to the unconfigured state, setting the new parameters, and reconfiguring.

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
What if the costmap is changing regularly? The map could be updated, thus updating the costmap, meaning that navfn will now have an inaccurate costmap.

**Comment by mjeronimo** [comment]
Yeah, that's why I moved the call inline to begin with. Unfortunately, with the service call inline there are occasional stalls due to the service call. We could change the code to have a map listener, but this won't be necessary with the new lifecycle code coming. With lifecycle nodes, the service call to get the costmap is in the on_configure method. Then, dynamically updating the map is straightforward - bring the nodes to a configurable state, update the parameters (like the map to use) and reconfigure. 

So, I recommend taking this change (short-term fix for the occasional stall) and waiting for the lifecycle node branch OR living with this defect until we integrate the lifecycle code at which point we won't have the stall and we'll have a methodology for updating all node parameters.

**Comment by mkhansen-intel** [comment]
> We could change the code to have a map listener, but this won't be necessary with the new lifecycle code coming. With lifecycle nodes, the service call to get the costmap is in the on_configure method. Then, dynamically updating the map is straightforward - bring the nodes to a configurable state, update the parameters (like the map to use) and reconfigure.

I think it's going to be a problem in lifecycle nodes also. The map can be changing dynamically, for example if Cartographer or another SLAM package is being used to generate it as the robot moves around. It won't be possible (or desirable) to keep reconfiguring the NavFn node each time, as that could be happening many times / second. 

So I think either:
1) We need to root cause the reason the service takes so long and see if it's a bug that can be fixed, or if it's a latency due to the data structure of the costmap or something that can't change
2) We need to change NavFn to getting the costmap from the topic instead. 

I'm open to other ideas if there's another, better way

**Comment by mkhansen-intel** [comment]
OK, one other option:
3. Same as option 2 except we add a parameter to NavFn to 'use_costmap_topic' so we can configure which one it is using at launch time. I think AMCL has a similar param for getting maps via either the service or topic. 

Option 3 get's my vote.

**Comment by SteveMacenski** [comment]
To give some outside perspective, I think its a good assumption through out your development to *assume* the map is changing at 1hz. This is representative of SLAM, but also the general trend towards continuous life-long SLAM implementations and away from static map localization techniques like AMCL.

**Comment by mkhansen-intel** [comment]
@SteveMacenski - thanks for the input

**Comment by mjeronimo** [comment]
Yes, I definitely want to get at the root cause of the service latency issue. Even so, I'm open to other fixes for this particular issue, such as getting the map from a topic instead of service.

**Comment by crdelsey** [comment]
Another possibility:
4. Put costmap back into navfn for now so it doesn't need to call a service.

The delay this PR is addressing is not a critical bug yet, so we could defer this change until 1. above is fixed.

**Comment by crdelsey** [comment]
Incompatible with SLAM so closing

**Pull request closed without merging**
