### PR TITLE
Add getFootprint() overload that returns time stamp

### PR DESCRIPTION
**Pull request by sloretz**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on |  |

---

## Description of contribution in a few bullet points

* Documents `FootprintSubscriber:getFootprint()`
  * is this documentation correct?
* Add overloaded method that returns time
  * Without the time stamp, I'm uncertain about how to get the footprint in the base frame. If I un-orient using the latest position, the result would be incorrect if the robot has moved since the footprint was published.

---

## Future work that may be required in bullet points

* I haven't actually tried to build this patch. This PR is both a contribution and a question to make sure I understand the footprint subscriber.

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
@sloretz - I see the benefit in adding this, but only if it's being used somewhere. Is there an package you want to use this in?

**Comment by SteveMacenski** [comment]
@mkhansen-intel low hanging fruit would be 

```
Footprint CollisionChecker::getFootprint(const geometry_msgs::msg::Pose2D & pose)
{
  Footprint footprint;
  if (!footprint_sub_.getFootprint(footprint)) {
    throw CollisionCheckerException("Footprint not available.");
  }

  Footprint footprint_spec;
  unorientFootprint(footprint, footprint_spec);
  transformFootprint(pose.x, pose.y, pose.theta, footprint_spec, footprint);

  return footprint;
}
```

adding a check that its within some timeout threshold of new

**Comment by mkhansen-intel** [comment]
@SteveMacenski - I understand there are places in our stack where this *could* be used, but the PR isn't adding any uses of the new getFootprint() method. Usually if someone submits a new method, they have at least one place they want to use it in that same PR.

**Comment by SteveMacenski** [comment]
Oh sorry, what I meant by that is if this is merged, I'll add it there. Re-reading that I totally did not make that clear.

**Comment by IanTheEngineer** [comment]
@mkhansen-intel do you see any changes that should happen before merging? 

I think this PR is particularly useful for those using `nav2_costmap_2d` as a library, in order to gauge the "stale-ness" of a given footprint before making a planning decision. That is in addition to the potential use-case that @SteveMacenski pointed out.

**Comment by mkhansen-intel** [comment]
Are you still interested in getting this merged or should we close it? It was failing lint checks last I knew.

**Comment by SteveMacenski** [comment]
I'll take care of this now and rebase with a new PR

**Comment by SteveMacenski** [comment]
@mkhansen-intel @sloretz successor https://github.com/ros-planning/navigation2/pull/1190

**Pull request closed without merging**
