### PR TITLE
remove angles again - in rosdep [waiting on next Crystal sync]

### PR DESCRIPTION
**Pull request by SteveMacenski**
Addresses https://github.com/ros-planning/navigation2/issues/345

Needs to wait for the next Crystal sync to be in main (out of shadow-fixed)

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Yup, I'll be watching planet ros for the first crystal release - it should come out with that.

**Comment by SteveMacenski** [comment]
@mkhansen-intel @mjeronimo do you know if the Build Farm CI runs on shadow-fixed or main?

**Comment by mkhansen-intel** [comment]
Fixed conflict

**Comment by mkhansen-intel** [comment]
This passed on the build farm, which is great, so I restarted Travis

**Comment by SteveMacenski** [comment]
Travis will still fail which is fine

**Comment by mkhansen-intel** [comment]
@SteveMacenski - Can you rebase this one so we can see if it passes Travis? Or when do you expect the rosdep keys to be updated for Crystal?

**Comment by SteveMacenski** [comment]
There still hasnt been an update in shadow-fixed, no reason to expect it to work yet

**Comment by mkhansen-intel** [comment]
@SteveMacenski - any update on this? I would think with a rebase this should now pass?

**Comment by SteveMacenski** [comment]
lets see

**Comment by SteveMacenski** [comment]
@mkhansen-intel we need to be using the official ROS2 docker container I think

**Comment by SteveMacenski** [comment]
Eh, let's just leave it. this isn't worth the cycles right now.

**Pull request closed without merging**
