### PR TITLE
add clear area method for plugins

### PR DESCRIPTION
**Pull request by SteveMacenski**
#1290 

This PR gives control to costmap_2d plugins to clear sections of its own area. This also helps by letting a plugin override this method if it also needs to clear out sections of its own internal data structure separate of the costmap_2d projected costmap.

Nothing uses this right now but it is necessary as more things are ported to ROS2

### CODE REVIEW

**Comment by SteveMacenski** [comment]
This PR should be squash merged

**Comment by mkhansen-intel** [comment]
> 
Nothing uses this right now but it is necessary as more things are ported to ROS2
>
I don't understand why you want to add this if nothing uses it yet? Can you point to an issue this will fix?

**Comment by SteveMacenski** [comment]
This is the original PR to navigation 
https://github.com/ros-planning/navigation/pull/877

Which was just accepted, so it's also making it feature parity with the ROS1 stuff.

This project: https://github.com/SteveMacenski/spatio_temporal_voxel_layer is starting to get ported to ROS2 by a user and this is a necessary element so I can clear not only the costmap but my own internal data structure for the 3d information.

The issue this will patch is the ability to port this 3D layer to ROS2. There's not a ticket in particular I can point to because most of this correspondence is over email.

**Comment by mkhansen-intel** [comment]
Thanks for the detailed explanation, I understand now. I don't usually like to approve code that "might be needed someday" which is why I asked. Since you have a clear reason, I'm good with it!

**Pull request merged**
