### PR TITLE
A patch to fix BT navigator nullptr error or no /behavior_tree_log problem

### PR DESCRIPTION
**Pull request by daisukes**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Tturtlebot |

---
Bugfix of BT navigator

- symptoms: nullptr error or no `/behavior_tree_log` topic
- problem: `tree_` is replaced after making a topic logger

How to reproduce
```
# launch TB3 and give an initial position
Terminal 1 $ ros2 launch nav2_bringup tb3_simulation_launch.py

# send a goal to navigate_to_pose with a non default bt tree (different from the last loaded)
Terminal 2 $ ros2 action send_goal /navigate_to_pose nav2_msgs/action/NavigateToPose '{"pose":{"header":{"stamp":{"sec":0,"nanosec":0},"frame_id":"map"},"pose":{"position":{"x":1,"y":1,"z":0},"orientation":{"x":0,"y":0,"z":0,"w":1}}},"behavior_tree":"/opt/overlay_ws/src/navigation2/nav2_bt_navigator/behavior_trees/navigate_w_replanning_speed.xml"}'

# echo topic
Terminal 3 $ ros2 topic echo /behavior_tree_log
```

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@fmrico please review

**Comment by SteveMacenski** [comment]
@fmrico thoughts? I'm OK with this but wanted your OK too

**Comment by fmrico** [comment]
Hi @daisukes @SteveMacenski 

Good catch. I have reproduced the bug, and this PR fixes it. `loadBehaviorTree` can change `tree_`, and it is needed to create `topic_logger`, so it must be called before.

LGTM.

**Comment by SteveMacenski** [comment]
Thanks for the contribution!

**Pull request merged**
