### PR TITLE
[foxy] Enable System Tests on Windows

### PR DESCRIPTION
**Pull request by seanyen**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | N/A |
| Primary OS tested on | Windows |
| Robotic platform tested on | Gazebo simulation |

---

## Description of contribution in a few bullet points

* Enable System Tests to be able to build and run on Windows.
* Most of the changes are related:
  1. Normalize the test file path to use forward slash `/` since many of the Nav2 components are expecting this convention.
  2. Add `python.exe` in front of any Python script execution. On Windows, the script is not an executable and one needs to prepend `python.exe` to run. Hope the convention is portable and won't disrupt the tests on Linux.
  3. Use more portable `M_PI` macros.
  4. Adding the missing dependency (angles) to  nav2_costmap_2d.

## Description of documentation updates required from your changes

N/A

---

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Can this be closed until its ready for review, or do you need the CI pipeline to test?

**Comment by seanyen** [comment]
@SteveMacenski Yes, I was trying to use the CI to ensure I didn't break the Linux side.

**Comment by SteveMacenski** [comment]
Your build is failing because you need to pull in `main`. The 'master' images don't exist. I think you want to retarget the PR to `main` since that's where all the new code is that will be cut into new releases.

**Comment by seanyen** [comment]
@SteveMacenski Hi, sorry to bother you on this CI problem, but I am struggling to figure out the CircleCI failures. I kept seeing there are failures at `Install Dependencies | /opt/overlay_ws` and I don't know how to correlate it back to my changes. Do you have any ideas what might cause the issue? Thanks!

**Comment by SteveMacenski** [comment]
I'm not 100% sure, but that looks like just a cache mess up. I just retriggered CI from scratch, so I think that should fix it. If it happens again, let me know and we can debug further.

**Comment by seanyen** [comment]
Hmm, it seemed still to fail at the same place. I am closing this pull request and create a new one to see if it helps..

**Pull request closed without merging**
