### PR TITLE
Cleanup CircleCI config

### PR DESCRIPTION
**Pull request by ruffsl**
Avoid duplicate colcon tests, and update/optimize CI config.
Context: https://github.com/ros-planning/navigation2/pull/1284#issuecomment-671636246

### CODE REVIEW

**Comment by SteveMacenski** [comment]
What's the tl;dr on these changes? Any new or removed jobs for CI/nightlies?

**Comment by ruffsl** [comment]
The commit comments speak for themselves, but this doesn't add or remove jobs.

**Comment by SteveMacenski** [comment]
@ruffsl please squash merge your pull requests. It really messes with cherry picking and general maintenance if I can't isolate a commit to a PR.

**Comment by ruffsl** [comment]
I wanted to maintain the line-level blame history for the CI changes, as it makes it easier to revert individual commits. Although commits to the default branch config.yaml shouldn't need to be cherry picked, 4c9b43f9922f42afdbca8d8fc982f3488d0e948f seems to map to the PR. I think as long as we don't push directly to the default branch but go through GH PRs, there will always be  hyperlinks between squash/merge commits and originating PRs.

**Comment by SteveMacenski** [comment]
Well its really messed things up while trying to realign the 2 branches. I think its completely busted now and just needs to be redone. Please don’t do that in the future.

**Comment by SteveMacenski** [comment]
I have no idea how to fix this now, I did not expect there to be merge commits in the range and the output is really strange. Origin main I don’t think is repairable without hours of work. If you have 1 squashed commit that changes from master to main this would be easy to fix but I don’t see that anywhere in the history to pull from.

**Pull request merged**
