### PR TITLE
Adding launch_testing_ros dep on nav2 utils to install to fix dump tests

### PR DESCRIPTION
**Pull request by SteveMacenski**
https://github.com/ros-planning/navigation2/issues/2433

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@ruffsl are we missing an apt update or something? CI failed with

```
E: Unable to locate package ros-rolling-launch-testing-ros
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y -qq ros-rolling-launch-testing-ros] failed
```

I see it though in rosdistro https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L1221and the  builds in build.ros2.org are successful and should be released months ago

**Comment by ruffsl** [comment]
> are we missing an apt update or something?

The `install_dependencies` step in CI already updates with the apt repos prior to rosdep install:

https://github.com/ros-planning/navigation2/blob/2af052cf716f6caf0eb55cbaa540e3848040318d/.circleci/config.yml#L98


However, it does look like the package is listed in the apt repo:
http://packages.ros.org/ros2/ubuntu/dists/focal/main/binary-amd64/Packages

```
Package: ros-rolling-launch-testing-ros
Version: 0.14.2-1focal.20210630.161615
Architecture: amd64
Maintainer: Jacob Perron <jacob@openrobotics.org>
Installed-Size: 70
Depends: ros-rolling-launch-ros, ros-rolling-launch-testing, ros-rolling-rclpy, ros-rolling-ros-workspace
Priority: optional
Section: misc
Filename: pool/main/r/ros-rolling-launch-testing-ros/ros-rolling-launch-testing-ros_0.14.2-1focal.20210630.161615_amd64.deb
Size: 11524
SHA256: 8c9c75330e560f15f7c4f997178713749a02b15a3d7472c50ebdc19e39b1aaaa
SHA1: 4a647e0a2273c9adc323b779bf71a6c57d9601e8
MD5sum: 69fd00cfc1b8c296f8d01b336b72e908
Description: A package providing utilities for writing ROS2 enabled launch tests.
```

Locally, I can install `ros-rolling-launch-testing`, but not `ros-rolling-launch-testing-ros`. I don't know why.


```
# apt search ros-rolling-launch-testing
Sorting... Done
Full Text Search... Done
ros-rolling-launch-testing/focal,now 0.18.0-1focal.20210706.175625 amd64 [installed]
  A package to create tests which involve launch files and multiple processes.

ros-rolling-launch-testing-ament-cmake/focal,now 0.18.0-1focal.20210706.175652 amd64 [installed]
  A package providing cmake functions for running launch tests from the build.
```

**Comment by SteveMacenski** [comment]
I ran into an issue like that for ompl with rosdep a couple of months ago where rosdep couldn't find `ros-rolling-ompl` but if I just typed it into a terminal to install with `apt` it worked fine. Weird, maybe there's something buggy in the ROS indexing software, but honestly I don't know much about that to even speculate.

I am able to install ros-rolling-launch-testing-ros on my computer though (did you apt update or update the index from the security breach a couple of months ago?) maybe the index these are using is still the old one and its not being updated?

**Comment by ruffsl** [comment]
> did you apt update or update the index from the security breach a couple of months ago?

That was resolved back in May I believe:
https://github.com/osrf/docker_images/pull/538

> maybe the index these are using is still the old one and its not being updated?

rosdep update is also invoked for each job:

https://github.com/ros-planning/navigation2/blob/2af052cf716f6caf0eb55cbaa540e3848040318d/.circleci/config.yml#L98-L99

I restarted the CI job, and it seems to be installing now. Perhaps we caught the apt repo mirror in the middle of a sync.

**Comment by SteveMacenski** [comment]
How odd, thanks for that, I would have gone a completely different (and overly complex) direction!

**Pull request merged**
