### PR TITLE
fix ObstacleLayer not working due to #2489

### PR DESCRIPTION
**Pull request by gezp**
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #3014) |
| Primary OS tested on | (Ubuntu22.04) |
| Robotic platform tested on | (gazebo simulation of turtlebot3) |

---

## Description of contribution in a few bullet points

Obstacle Layer not working (the scan data isn't subscribed by Obstacle Layer),  becasue `observation_subscribers_->subsciber()` failed when `ObstacleLayer::activate()` is called since #2489

* use `active_` flag instead of `subscibe()` and `unsubscibe()`  (refer to https://github.com/ros-planning/navigation2/blob/main/nav2_amcl/src/amcl_node.cpp#L614)

i'm not sure the side effect of this change, maybe we could have a better solution.

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by gezp** [comment]
CC @jwallace4

**Comment by gezp** [comment]
CC @jwallace42

**Comment by SteveMacenski** [comment]
If callback groups aren't being respected, how does bypassing the unsubscribe help? Per rclcpp issue thread

**Comment by gezp** [comment]
> If callback groups aren't being respected, how does bypassing the unsubscribe help? Per rclcpp issue thread

maybe I don't get your meaning，the problem is caused by `subscribe()`, not related to `unsubscribe()` .

**Comment by SteveMacenski** [comment]
https://github.com/ros2/rmw_fastrtps/pull/619 supposedly fixes it and is merged!

**Comment by dcconner** [comment]
Humble binaries as of 18-Oct still have this issue.  Switching to Cyclone seems to fix.  Just commenting here for others that might be trying to track down issue

**Pull request closed without merging**
