### PR TITLE
Revert CI image to build from osrf/ros2:testing

### PR DESCRIPTION
**Pull request by ruffsl**
Reverts parts of: https://github.com/ros-planning/navigation2/pull/2348
Depends on: https://github.com/osrf/docker_images/pull/542

### CODE REVIEW

**Comment by ruffsl** [comment]
Builds are passing now when building from rolling-testing repo!

**Comment by ruffsl** [comment]
No longer having to build a huge underlay and use rolling-testing really cut down on the image build time, wow:

image

**Comment by wilcobonestroo** [comment]
All repos in the `tools/underlay.repos` file are commented now. If you follow the [steps to build the Nav2 Dependencies](https://navigation.ros.org/build_instructions/index.html#build-nav2-dependencies), you don't get the dependecies when you do the `vcs import`. Should there be a separate file for CI and one for manually building? Anyway, the steps described at the Build and Install page should be updated.

**Comment by ruffsl** [comment]
We've been migrating our CI and development to build from rolling testing. This avoids the need to build a large amount of packages within your underlay, and can save us all a lot of build time. The underlay repo file is still there so if people do need to submit PRs that built against custom versions of dependencies in transit, they still have a way to configure the CI to do that. I've only commented out the repos so

**Comment by wilcobonestroo** [comment]
I am not sure if I completely understand it right at the moment. I think you are referring to the CI and I was referring to the description how to build Nav2 on your local machine.  The steps to [manually build the Nav2 Dependencies](https://navigation.ros.org/build_instructions/index.html#build-nav2-dependencies) describe the following commands to perform:
```
source ros2_ws/install/setup.bash
mkdir -p ~/nav2_depend_ws/src
cd ~/nav2_depend_ws
wget https://raw.githubusercontent.com/ros-planning/navigation2/main/tools/underlay.repos
vcs import src < underlay.repos
rosdep install -y -r -q --from-paths src --ignore-src --rosdistro <ros2-distro>
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
```
If you follow these steps, you don't get the repos at the vcs import command, unless you uncomment the repos in the file.

Is the solution to add a description that you should look into the underlay.repos file and uncomment the lines that you need? As far as I understand, I needed all lines to be able to build Nav 2. Is that correct? Or is there another way for me to get the rolling dependencies on my development machine?

**Pull request merged**
