### PR TITLE
removing extraneous visualization from tests that have been removed

### PR DESCRIPTION
**Pull request by SteveMacenski**
There's some extraneous visualizations for `endpoints` that were added for a system test that was later removed, I'm now removing the visualization as it doesn't really provide any benefit

### CODE REVIEW

**Comment by orduno** [comment]
I kind of found the path endpoints markers useful and  easier to view than the full path marker.  For example, when visualizing plan updates, viewing robot progress towards the goal pose and during preemption. What does the rest think?

**Comment by SteveMacenski** [comment]
It leaves this "heatmap" like trail behind the robot, not the current state of the path endpoint (as I saw it). I think if we want a heatmap of robot poses over time that's another feature that's interesting but doesn't belong in the planner. 

I could make a ticket for something to track the state of the robot for leaving temporary markers, but this implementation has a static amount of markers so we'd have to make an expiration time parameter and/or a number to expire parameter and we're then starting to make functionality that doesnt directly depend on the planner, inside the planner, with a bunch of configurations.

Thoughts?

**Comment by crdelsey** [comment]
The markers do come in handy at times, but, I agree, it seems wrong for the planner to be remembering old data in this way.

> I could make a ticket for something to track the state of the robot for leaving temporary markers

Any thoughts of how to do this? It seems to me like navfn should still publish the current endpoint markers (though maybe factored out of the core planner). The "heatmap" part seems like it should be part of the rviz plugin

**Comment by SteveMacenski** [comment]
I dont think RVIZ is the right place for that, because you're assuming they're operating closely together, and if the robot pose info doesn't load for awhile you'll drop markers from TF failing to transform.

I'd just make a trivial little server in the background that at some regular rate gets the robot pose and publishes a marker array with a ring buffer of `N` size (or decay after `M` seconds, whatever)

This is pretty much the definition of a debug utility, so I don't think it should go in the "core" tools unless its useful for a given tool's tuning/configuration, like DWB's debug visualizations. This doesn't seem to me to help actually tune anything, its just a neat graphic

**Comment by SteveMacenski** [comment]
Either way, I think we agree to remove it from here, can we merge this and I'll file a ticket for an rviz display?

**Comment by SteveMacenski** [comment]
@crdelsey thoughts? 

Fixed merge conflict

**Comment by SteveMacenski** [comment]
I feel like we can do better if this was an rviz display type to begin with. Have the path shown and have some coloring for the PF covariances, more frequent sampling, etc

**Pull request merged**
