### PR TITLE
removing kinematic limiting from RPP

### PR DESCRIPTION
**Pull request by SteveMacenski**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2621 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | seasony bot |

---

## Description of contribution in a few bullet points

* Removing kinematic limiting in RPP after finding it creates discontinuities
* This should be handled by a lower level velocity smoother anyway 

## Description of documentation updates required from your changes

- [x] Update migration docs that params are gone
- [x] Update docs with parameters out of RPP config guide

---

#### For Maintainers: 
- [x] Check that any new parameters added are updated in navigation.ros.org
- [x] Check that any significant change is added to the migration guide
- [x] Check that any new functions have Doxygen added
- [x] Check that any new features have test coverage
- [x] Check that any new plugins is added to the plugins page
- [x] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Comment by vinnnyr** [comment]
+1 for this change. These parameters were causing issues in our robot. Specifically the issues were related to selecting parameters to help RPP overcome a deadband region in our machine controller, while not gunning the acceleration, which was incredibly difficult to do.

**Comment by doisyg** [comment]
Docs should be updated to reflect that change, I got confused believing accel limits were still in place:
- https://github.com/ros-planning/navigation2/blob/main/nav2_regulated_pure_pursuit_controller/README.md

**Comment by doisyg** [comment]
What's the rational behind removing the linear accel limits and not the angular limit ?

**Comment by doisyg** [comment]
Last spam on this merge. For a robot with a very little linear decel capability, how to not overshoot the goal position ? By playing with the `lookahead_dist` and scaling params ?

**Comment by SteveMacenski** [comment]
I updated the readme.

> For a robot with a very little linear decel capability, how to not overshoot the goal position ? By playing with the lookahead_dist and scaling params ?

Perhaps, yeah the scaling parameters would be good. This had not considered much robots having unusually low decel capabilities, so perhaps there are modifications that can be made to support. https://github.com/ros-planning/navigation2/issues/2815 and its complimentary PR have some such change that I haven't gotten to reviewing yet, but may be of interest?

**Comment by doisyg** [comment]
Thanks for the pointer, the PR addresses precisely my needs. I may end up testing it very soon on a heavy platform (~500kg). However only on straight line paths. Will report directly there https://github.com/ros-planning/navigation2/issues/2815

**Comment by SteveMacenski** [comment]
OK. I don't have an issue with their general idea, its the scale of changes due to the new library I'm not super familiar with that I'm a little weary about. And where else we should maybe be leveraging that.

**Pull request merged**
