### PR TITLE
Fix finding Codecov config for CI

### PR DESCRIPTION
**Pull request by ruffsl**
The codecove orb was running from the wrong working directory to find the `codecov.yml` config file, i.e. the root of the overlay workspace instead of the root of the navigation2 git repo. This just swaps out the orb with the command it generates and adds the needed `-R` root dir argument to specify the path to the navigation2 git repo. It also cleans up the root of the project dir by moving the config file into the CI dot folder, given the codecov bash script can find it there anyhow:

https://github.com/codecov/codecov-bash/blob/9d9a1b61c04e8aea9ebb8c200d1fbc399eb6cc99/codecov#L963-L968

Fixs: https://github.com/ros-planning/navigation2/issues/2006

### CODE REVIEW

**Comment by SteveMacenski** [comment]
It doesn't appear to trigger Codecov now

**Comment by ruffsl** [comment]
> It doesn't appear to trigger Codecov now

It does, my fork doesn't trigger this repo's github bot for posting the codecov links in the PR comment thread.
See the link it created from the CI:

https://codecov.io/github/ruffsl/navigation2/commit/55781ef431ccd7c411885021f1b0a799b00b5a90

 This is because I've enabled CI for my fork, so codecov results are using my codecov tokens for my forked repo.

**Comment by SteveMacenski** [comment]
I don't think that works then, because most PRs are going to be from random peoples' forks when they submit patches. Only a very small number of people can push branches to the main copy.

**Comment by ruffsl** [comment]
> I don't think that works then, because most PRs are going to be from random peoples' forks when they submit patches. Only a very small number of people can push branches to the main copy.

Not sure what your saying. That's just how cloud CI providers work, regardless of what changes we make to the configs in this repo. If I push commits to my fork, and I have CI enabled/integrated for my github fork, then the CI will run using my account's tokens.

I could temporarily disable CI for my fork and show you, no one else seems to enable it for personal forks given I'm the only one experimenting with the CI, so it isn't much an issue. Merely that the reports are filed under my codecov fork. See here: https://github.com/ruffsl/navigation2/pull/5

We could look into it further later to see if codecov can be told to cross talk across PR for commit events.

**Comment by SteveMacenski** [comment]
Can you push this branch to `ros-planning` and open a PR on that? Just to make sure that things are working as expected and its just your fork.

**Comment by SteveMacenski** [comment]
The codecov/project is failing in the same way :/

**Comment by ruffsl** [comment]
> The codecov/project is failing in the same way :/

As this PR doesn't improve the code coverage percentage by adding more tests, it seems to be failing correctly, for the same reason that the base commit for this PR from the project failed:

https://github.com/ros-planning/navigation2/pull/2005

> Its been failing after 1s of running and fails to produce results causing PRs to not be all green.

* https://github.com/ros-planning/navigation2/runs/1099675360
* https://github.com/ros-planning/navigation2/pull/2007/checks?check_run_id=1196129774

Isn't the project coverage report supposed to fail if it doesn't monotonically increase?
Total project coverage is still down from where it was historically from it's previous high with b04af1c1988e4a0b1f2423f8703475bccaeff43d .

**Comment by SteveMacenski** [comment]
Ah, I read the failed after `1s` to be a "I'm failing in setup not actually getting to try", not a "I tried and failing because too low of coverage taking only 1s".

We can validate that to be the case if we go into the bash script in tools and remove `nav2_amcl` temporarily from the coverage results. That's < 90% so if we remove it, it'll push the average up and then this should pass from the higher coverage. If that works, we then know that to be the case.

**Comment by ruffsl** [comment]
> We can validate that to be the case if we go into the bash script in tools and remove `nav2_amcl` temporarily from the coverage results. That's < 90% so if we remove it, it'll push the average up and then this should pass from the higher coverage. If that works, we then know that to be the case.

I added a such a test commit to the branch pushed to ros-planning 6905a80b89cd6ef796e982a6fdd0dc7e9d7b9185 , and it all passes codecov:

image

**Comment by SteveMacenski** [comment]
Sweet, thanks!

**Pull request merged**
