### PR TITLE
[WIP] Checking line coverage in codecov

### PR DESCRIPTION
**Pull request by shivaang12**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  #1709 |
| Primary OS tested on |  |
| Robotic platform tested on |  |

---

I am changing some options here to see if it makes any difference to current branch coverage.

### CODE REVIEW

**Comment by shivaang12** [comment]
I don't know if this even working. I haven't found any proper docs to handle this.

**Comment by shivaang12** [comment]
May be I was wrong about lcov and gcov thing. GCOV is graphical thing while LCOV is not. My bad!

**Comment by shivaang12** [comment]
This line in `collect code coverage` section is causing the branch coverage to appear

`+ lcov --capture --initial --directory build --output-file lcov/initial_coverage.info --rc lcov_branch_coverage=1`

We need to remove this option `lcov_branch_coverage=1` and I am clue less about it.

**Comment by shivaang12** [comment]
So line coverage (or whatever it is) is roughly about 64%.

**Comment by SteveMacenski** [comment]
I'm just going to run tests until they all pass so I can see the diff report from codecov. I'll go through a sampling of the repo and make sure it looks reasonable. 

64%.... not bad. Not bad.

**Comment by SteveMacenski** [comment]
I'm happy with this. @mkhansenbot @crdelsey any reason we should not move to line coverage? Its also what OSRF uses for rclcpp and in the example requirements for the quality standard. C++ exceptions cause branching and even simple 5 line `main()` functions show up as partial misses because of the infinite number of exceptions that can be thrown.

**Comment by SteveMacenski** [comment]
@shivaang12 you can move this into a full PR.

**Comment by shivaang12** [comment]
I agree!

**Comment by SteveMacenski** [comment]
@wjwwood for the quality standard, I see an example of having 90% coverage using line coverage as a metric for L1. Is line coverage the recommended method of tracking code coverage or do you recommend branch coverage but knocking down the coverage rate? 

With all the branches from STL exceptions, we have many lines that aren't branching due to a conditional but rather just to due `rclcpp::init(...)` or `vector_name.push_back("string");`. We've shown here a ~39% branch coverage and ~65% line coverage. I'd like to follow along and set our goals with best practices.

**Comment by SteveMacenski** [comment]
We can revert this later if we feel this is bad. From chatting with a bunch of people no one has a particular reason why not.

**Comment by wjwwood** [comment]
The idea behind the REP is to have you come up with a policy, document it, and justify it. So either of the two you suggested is fine I think as long as you motivate it.

For the ROS 2 developer guide we use 95% line coverage, but allow for other goals if justified:

https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage

**Comment by SteveMacenski** [comment]
Awesome, that helps. Thanks

**Pull request merged**
