### PR TITLE
Add ament_export_libraries to map_server

### PR DESCRIPTION
**Pull request by maxlein**
This Pr would allow one to derive from map_server lib in another package to add custom functionality.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Please change the target branch to master

**Comment by maxlein** [comment]
Sorry, don't make pull requests that often.  
Do you mean to make another pull request to master?  
Because I don't know how I can change the target of this one here. 😢

**Comment by SteveMacenski** [comment]
If you go to the top and hit the “edit” button, you can change the branch from eloquent-devel to master. 

It changes were you’re proposing the changes to. The devel branches are for deployment and CM, but all new developments that aren’t exclusive to a distribution should be merged into master. Then occasionally we cherrypick the commits over to the devel branch for release

**Comment by SteveMacenski** [comment]
I tried to update this for you but there was too much deviations from the master branch.

You will need to rebase your branch from eloquent-devel to master and apply that commit.

**Comment by maxlein** [comment]
Ah, thank you!
> I tried to update this for you but there was too much deviations from the master branch.  

Saw that coming.
Is ist a problem to just add these 3 lines to master and make a new pull request?  
It would save me some manual merging tasks

**Comment by SteveMacenski** [comment]
Sure, that works

**Pull request closed without merging**
