### PR TITLE
Remove simple navigator

### PR DESCRIPTION
**Pull request by SteveMacenski**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | N/A |
| Primary OS tested on | N/A |
| Robotic platform tested on | N/A |

---

## Description of contribution in a few bullet points

The simple navigator is no longer default, nor is it uniquely used in CI. Given that we now have BT running in real-life, I think its time to deprecate it where the default XML is "similiar enough" to the simple navigator logic that it all works out. 

I started to refactor the simple navigator and about half way through I realized it really didn't need to be around anymore, as the default is BT now, we have a couple BT trees that we like, and this piece of code isn't under active development / use. If we're going to point people to the repo to test it out, we should point them to the thing we want them to actually use. 

I think keeping the simple navigator was a smart move when this project was started, but given recent developments, we can safely remove it and make sure we don't have people looking left when we want them to look right. It took me personally a few weeks to get on-board with the behavior tree base implementation, but now that I understand more, I think it's worth not confusing others by giving the option.

This is also in theme of my PRs this month of trying to "simplify" the repo to new users. 

Let me know what you think. I dont expect this to be merged out of the gate, but a catalysis for discussion.  

---

### CODE REVIEW

**Comment by mjeronimo** [comment]
Yes, I agree: the simple navigator has been useful, but it's now time to move on. The BT navigator is the default and there's really no value in keeping the simple navigator around. It's not that useful as an example either, since it's really just a container for a couple action clients. Agree that we should also try to simplify the source tree as well. I have a couple PRs planned in that vein.

**Comment by SteveMacenski** [comment]
Got it. @mkhansen-intel let me know what you think makes most sense. It has 2 approvals now so it can go as needed.

**Comment by mhpanah** [comment]
Nice. We were just talking about opening a new issue to remove the simple navigator.

**Comment by mkhansen-intel** [comment]
@mjeronimo - I'd like to merge this unless you think it will make your lifecycle branch rebase more difficult. Since it's removing code, I would hope it would make it easier. You decide.

**Comment by mjeronimo** [comment]
@mkhansen-intel It's fine with me to merge now. It won't cause any difficulties since it's removing a directory.

**Pull request merged**
