### PR TITLE
[CostmapLayer] Fix clearArea invert param logic

### PR DESCRIPTION
**Pull request by doisyg**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/issues/2770 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Wyca Elodie |

---

## Description of contribution in a few bullet points

As discussed here https://github.com/ros-planning/navigation2/issues/2770

## Description of documentation updates required from your changes

Mention in migration guide update

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
LGTM, I just need an updated section to the migration guide so that people know explicitly this was inverted

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
I know its not from this PR, but can you fix the linting error. I'm not sure how / why that is appearing here.

```

--- src/dump_params.cpp
+++ src/dump_params.cpp.uncrustify
@@ -237 +237 @@
-      (param_descriptors[i].read_only ? "True" : "False") << "\n";
+        (param_descriptors[i].read_only ? "True" : "False") << "\n";
@@ -290 +290 @@
-      (param_descriptors[i].read_only ? "True" : "False");
+        (param_descriptors[i].read_only ? "True" : "False");
```

just to get the CI green to merge?

**Comment by doisyg** [comment]
I could but I cannot reproduce it locally (ros-galactic-ament-uncrustify 0.10.6-1focal.20210507.020634):

> ~ws/src/submodules/navigation2/nav2_util$ ament_uncrustify 
> No code style divergence in file 'include/nav2_util/clear_entirely_costmap_service_client.hpp'
> 
> No code style divergence in file 'include/nav2_util/costmap.hpp'
> 
> No code style divergence in file 'include/nav2_util/execution_timer.hpp'
> 
> No code style divergence in file 'include/nav2_util/geometry_utils.hpp'
> 
> No code style divergence in file 'include/nav2_util/lifecycle_node.hpp'
> 
> No code style divergence in file 'include/nav2_util/lifecycle_service_client.hpp'
> 
> No code style divergence in file 'include/nav2_util/lifecycle_utils.hpp'
> 
> No code style divergence in file 'include/nav2_util/line_iterator.hpp'
> 
> No code style divergence in file 'include/nav2_util/node_thread.hpp'
> 
> No code style divergence in file 'include/nav2_util/node_utils.hpp'
> 
> No code style divergence in file 'include/nav2_util/occ_grid_values.hpp'
> 
> No code style divergence in file 'include/nav2_util/odometry_utils.hpp'
> 
> No code style divergence in file 'include/nav2_util/robot_utils.hpp'
> 
> No code style divergence in file 'include/nav2_util/service_client.hpp'
> 
> No code style divergence in file 'include/nav2_util/simple_action_server.hpp'
> 
> No code style divergence in file 'include/nav2_util/string_utils.hpp'
> 
> No code style divergence in file 'src/costmap.cpp'
> 
> No code style divergence in file 'src/dump_params.cpp'
> 
> No code style divergence in file 'src/lifecycle_bringup_commandline.cpp'
> 
> No code style divergence in file 'src/lifecycle_node.cpp'
> 
> No code style divergence in file 'src/lifecycle_service_client.cpp'
> 
> No code style divergence in file 'src/lifecycle_utils.cpp'
> 
> No code style divergence in file 'src/node_thread.cpp'
> 
> No code style divergence in file 'src/node_utils.cpp'
> 
> No code style divergence in file 'src/odometry_utils.cpp'
> 
> No code style divergence in file 'src/robot_utils.cpp'
> 
> No code style divergence in file 'src/string_utils.cpp'
> 
> No code style divergence in file 'test/test_actions.cpp'
> 
> No code style divergence in file 'test/test_execution_timer.cpp'
> 
> No code style divergence in file 'test/test_geometry_utils.cpp'
> 
> No code style divergence in file 'test/test_lifecycle_cli_node.cpp'
> 
> No code style divergence in file 'test/test_lifecycle_node.cpp'
> 
> No code style divergence in file 'test/test_lifecycle_utils.cpp'
> 
> No code style divergence in file 'test/test_node_utils.cpp'
> 
> No code style divergence in file 'test/test_odometry_utils.cpp'
> 
> No code style divergence in file 'test/test_robot_utils.cpp'
> 
> No code style divergence in file 'test/test_service_client.cpp'
> 
> No code style divergence in file 'test/test_string_utils.cpp'
> 
> No problems found

**Comment by SteveMacenski** [comment]
Maybe a change to Rolling’s linter profiles? Are you up to date on rolling?

If you are and still not seeing it locally I’ll merge and deal with this later.

**Comment by doisyg** [comment]
Sorry for the delayed answer, different timezone.
I just tried with `ros-rolling-ament-*` latest bins, same results

**Pull request merged**
