### PR TITLE
Update Dashing ros2_dependencies.repos

### PR DESCRIPTION
**Pull request by rotu**
Switch dependencies to dashing branches

### CODE REVIEW

**Comment by rotu** [comment]
Looks like CI is broken for other reasons. Why is it trying to build this against eloquent?

https://travis-ci.org/ros-planning/navigation2/builds/596715576?utm_source=github_status&utm_medium=notification
```
Step 19/31 : RUN . /opt/ros/$ROS_DISTRO/setup.sh &&     apt-get update && rosdep install -q -y       --from-paths src       --ignore-src     && rm -rf /var/lib/apt/lists/*
606 ---> Running in 16f8dcf33bb0
607Traceback (most recent call last):
608  File "/opt/ros/eloquent/_local_setup_util.py", line 314, in <module>
609    main()
610  File "/opt/ros/eloquent/_local_setup_util.py", line 65, in main
611    args.additional_extension
612  File "/opt/ros/eloquent/_local_setup_util.py", line 184, in get_commands
613    package_dsv_path, prefix, primary_extension, additional_extension)
614  File "/opt/ros/eloquent/_local_setup_util.py", line 243, in process_dsv_file
615    additional_extension=additional_extension)
616  File "/opt/ros/eloquent/_local_setup_util.py", line 243, in process_dsv_file
617    additional_extension=additional_extension)
618  File "/opt/ros/eloquent/_local_setup_util.py", line 218, in process_dsv_file
619    type_, remainder, prefix)
620  File "/opt/ros/eloquent/_local_setup_util.py", line 283, in handle_dsv_types_except_source
621    assert False, 'Unknown environment hook type: ' + type_
622AssertionError: Unknown environment hook type: set
```

**Comment by crdelsey** [comment]
The underlying docker files that our CI uses are based on ROS 2 master. None of our CI config files are set up to distinguish between building the master branch and the dashing-devel branch. 

It hasn't been a big enough issue to be worth fixing so far, since our dashing-devel branch is a limited-use branch. Instead, I've been manually testing the dashing-devel branch extensively when I do a backport

The OSRF PR builder does work on this branch, but it doesn't actually make use of this repos file. Instead, it uses rosdep (or the equivalent) to pull in the dashing build dependencies.

@rotu Do you use this file to use ros2 dashing latest? Or were you just trying to get CI to pass?

**Comment by rotu** [comment]
@crdelsey I was just trying to get CI to pass. My expectation is that if a PR fails automatic checks, either the PR or CI is broken. I think the build checks and/or CI may need to be fixed.

**Comment by crdelsey** [comment]
> I think the build checks and/or CI may need to be fixed.

I absolutely agree. CI on the dashing-devel branch has been a low priority so far, though, since it doesn't have that much activity. This is a step in the right direction, but there are a few other pieces that need to be done before it will start to pass.

I'm OK with integrating this, as is, since this gets us closer to the goal. 

Additional work that needs to be done:
 -  Make the travis and circle CI config files aware of the target branch.
 -  Modify those config files to use a dashing based docker contain for building
 -  Modify the build to pull dashing branches for all dependencies. (This addresses part of it. ROS 2 is the other part)
 -  Fix the failing tests in OSRF build.

**Comment by mkhansen-intel** [comment]
It may not work, but I think all we'd have to do is change this line:
https://github.com/ros-planning/navigation2/blob/2ba8f44fe485afff8a07554169e6bdf5cfc6886a/Dockerfile#L9

To pull from the `osrf/ros2:dashing` docker image instead.

@rotu - do you want to try that by pushing that change to this branch?

**Comment by rotu** [comment]
@mkhansen-intel done

**Comment by SteveMacenski** [comment]
toggling PR builder

**Comment by rotu** [comment]
Looks like it's still trying to build against Eloquent rclcpp

**Comment by SteveMacenski** [comment]
@rotu unless there's something wacky on the build farm side, it seems to be to be dashing. We dont even release into Eloquent so the PR builder from the ROS build farm is with dashing. It looks like it built fine but unstable on test failures.

Travis is failing on BT versions which I see you changed.

CircleCI I cant comment on, that might be the case

**Comment by rotu** [comment]
Yeah I was looking at the Circle CI failures

`Looking for packages in '/opt/ros/eloquent/share'... using matcher with tags [eloquent, ubuntu, bionic]`
...
```
--- stderr: nav2_dynamic_params
/opt/overlay_ws/src/navigation2/nav2_dynamic_params/src/dynamic_params_validator.cpp: In constructor ‘nav2_dynamic_params::DynamicParamsValidator::DynamicParamsValidator(rclcpp::Node::SharedPtr, bool)’:
/opt/overlay_ws/src/navigation2/nav2_dynamic_params/src/dynamic_params_validator.cpp:29:10: error: ‘using element_type = class rclcpp::Node {aka class rclcpp::Node}’ has no member named ‘register_param_change_callback’; did you mean ‘set_on_parameters_set_callback’?
   node_->register_param_change_callback(
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          set_on_parameters_set_callback
make[2]: *** [CMakeFiles/nav2_dynamic_params.dir/src/dynamic_params_validator.cpp.o] Error 1
make[1]: *** [CMakeFiles/nav2_dynamic_params.dir/all] Error 2
make: *** [all] Error 2
```

https://circleci.com/gh/ros-planning/navigation2/4609?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SteveMacenski** [comment]
I'd just focus on getting the ones we know are actually running dashing first

**Comment by rotu** [comment]
Travis is not failing on BT - those are just build warnings. It *is* hanging on the build of gazebo_plugins for some unknown reason.

**Comment by crdelsey** [comment]
I've noticed the gazebo_plugins build occasionally take a while on my machine. On travis, it's bound to be even slower. It's not unreasonable to think that, sometimes, it takes more than 10 minutes to build.

I'm not sure how to fix that, except find some colcon build option that causes it to pass through all the build output.

**Comment by ruffsl** [comment]
> Make the travis and circle CI config files aware of the target branch.

@crdelsey , I think we talked about this before, but couldn't find it. Could you open a ticket, and I'll explain what feature is missing from CircleCI to achieve this (that I've grown a little tired of waiting for).

**Comment by SteveMacenski** [comment]
IMO if someone (other than rotu, for 3rd party validation) does this locally and it works, just merge it. 

This is the PR builder, the CI for the dashing branch should be right

**Comment by mkhansen-intel** [comment]
If anyone can cherry-pick 72221ba1e7feda486405b12731e6cef22878f0af and push it to this branch that should fix the timeout issue (already fixed on master).

**Comment by mkhansen-intel** [comment]
I tried to do it but couldn't push to the branch

**Comment by rotu** [comment]
@mkhansen-intel done

**Comment by SteveMacenski** [comment]
@rotu what's the status of this?

**Comment by rotu** [comment]
This PR is done and awaiting merge.

**Pull request merged**
