### PR TITLE
Enable retest until passing with limit

### PR DESCRIPTION
**Pull request by ruffsl**
Context: https://github.com/ros-planning/navigation2/issues/1271

I'm not sure what retry value would be preferred. I just copied what was used in:

https://github.com/ros-planning/navigation2/blob/67a92be87f8a00470313c232b1462d45379273e8/tools/run_test_suite.bash#L22

### CODE REVIEW

**Comment by ruffsl** [comment]
I added a commit to not retest linters, given liters shouldn't be flaky. But I'm not confident about it.

https://github.com/ros-planning/navigation2/blob/67a92be87f8a00470313c232b1462d45379273e8/tools/run_test_suite.bash#L13-L14

**Comment by SteveMacenski** [comment]
Not a big deal, but I think the way we've agreed to run this repo has us fork it and branch on our separate forks vs creating new branches (well, intentionally, I do accidentally all the time) in the main project. For future things it'd be great if you forked :+1:

**Comment by ruffsl** [comment]
> it'd be great if you forked

Opps, missed that memo.
Perhaps we should include that notice in the repo's [contributing](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file) file.

**Comment by SteveMacenski** [comment]
Fair enough, though only about 6 people have push rights to even do it ;-)

**Comment by crdelsey** [comment]
We should probably hold off merging this until we fix #1283. Otherwise it's just going to take us longer to fail and waste extra CircleCI CPU time.

**Comment by ruffsl** [comment]
@crdelsey . per your https://github.com/ros-planning/navigation2/issues/1271#issuecomment-545654248 , I've added 07c52ea , please check CI logs if its addressed.

> (well, intentionally, I do accidentally all the time)

I'll admit I've accidentally fat-fingered a push to master,
could we enable master and distro branched protected/PR-only?

**Comment by crdelsey** [comment]
> I'll admit I've accidentally fat-fingered a push to master,

No big deal. I'd vote to leave the protection off unless it turns out to be a problem. We can always revert a PR if needed.

Being able to push directly to master is kind of handy when "just fixing things" or bumping version numbers for a release and such stuff.

**Comment by ruffsl** [comment]
@SteveMacenski , this change is what is leading to the retesting of the entire package noted from https://github.com/colcon/colcon-core/issues/368#issuecomment-671626761 . Perhaps we could also unset `RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED` to reduce the line nose thanks. @crdelsey, from https://github.com/ros-planning/navigation2/issues/1271#issuecomment-545654248 , is this still an issue?

**Comment by SteveMacenski** [comment]
This wasn't something I was super involved in, I'll follow your judgement

**Pull request merged**
