### PR TITLE
Rolling ci with repos

### PR DESCRIPTION
**Pull request by wep21**
https://github.com/ros-planning/navigation2/pull/2339 without removing unreleased packages from repos.

### CODE REVIEW

**Comment by ruffsl** [comment]
> #2339 without removing unreleased packages from repos.

Everything but `ompl` has indeed been released into rolling, no?

http://packages.ros.org/ros2/ubuntu/dists/focal/main/binary-amd64/Packages

The `.repos` file in #2339 does produce a building Dockerfile.

**Comment by SteveMacenski** [comment]
@ruffsl I agree that it looks like they're release, are we not calling rosdep in the right place now that the underlay workspace isn't needed for those? That is odd, maybe need to apt update?

**Comment by ruffsl** [comment]
> are we not calling rosdep in the right place now that the underlay workspace isn't needed for those? That is odd, maybe need to apt update?

Not sure what your asking. Are you asking if there are still unresolved dependencies? By commenting out the source repos of released rolling packages from the underlay's `.repos` file, the RUN directive invoking rosdep for the overlay workspaces will now instead be the layer where most of nav2's external dependencies will be installed.

**Comment by SteveMacenski** [comment]
@wep21 I appreciate the PR and help, but I think Ruffin's got this one. He knows the CI system for nav2 the best of anyone and is underway.

**Comment by SteveMacenski** [comment]
Closing - Ruffin's PR is merged and building, thanks for the help @wep21!

**Comment by ruffsl** [comment]
@wep21 , could you include 7d8afb2 in a new PR to fix linting. I'd like to see if CI is caching as expected after merging https://github.com/ros-planning/navigation2/pull/2343 .

**Comment by wep21** [comment]
@ruffsl Sure. https://github.com/ros-planning/navigation2/pull/2346

**Pull request closed without merging**
