### PR TITLE
Refactor plugins to use double colons for consistency

### PR DESCRIPTION
**Pull request by alanxuefei**
Tested in Gazobo world. 
The turtle bot runs as normal.

The CI/CD process fails due to the `rosdep` issue during the Docker build stage. I encountered the same issue on my local PC and resolved it by using `apt install`.

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
dwb_msgs: No definition of [rosidl_default_runtime] for OS version [jammy]
costmap_queue: No definition of [rclcpp] for OS version [jammy]
nav2_behaviors: No definition of [pluginlib] for OS version [jammy]
nav2_common: No definition of [rclpy] for OS version [jammy] 
```
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #4194) |
| Primary OS tested on | (Ubuntu,) |
| Robotic platform tested on | (gazebo simulation of turtlebot) |
| Does this PR contain AI generated software? | (No) |

---

## Description of documentation updates required from your changes

N.A.

---

## Future work that may be required in bullet points

N.A.

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
Please update the docs with the updated consistency (tutorials/config guide/navigation plugins list/etc) + add to the migration guide since this is a breaking change

**Comment by alanxuefei** [comment]
> Please update the docs with the updated consistency (tutorials/config guide/navigation plugins list/etc) + add to the migration guide since this is a breaking change

Ok will create a pull request in https://github.com/ros-planning/navigation.ros.org

**Comment by alanxuefei** [comment]
> Please update the docs with the updated consistency (tutorials/config guide/navigation plugins list/etc) + add to the migration guide since this is a breaking change

A pull request is created at https://github.com/ros-planning/navigation.ros.org/pull/539

**Comment by alanxuefei** [comment]
The following files only appeared on the [Nav2 website](https://github.com/ros-planning/navigation.ros.org), not in [Nav2 Codes](https://github.com/ros-planning/navigation2). Therefore, there is no need to factor them in this PR. The Nav2 website has been updated accordingly.

- nav2_sms_behavior/SendSms 
- nav2_gradient_costmap_plugin/GradientLayer
- nav2_straightline_planner/StraightLine

**Comment by alanxuefei** [comment]
> **DCO ** — DCO

DCO passed. The signature is added.

**Comment by SteveMacenski** [comment]
@alanxuefei minor clarification is needed in the docs PR, then will merge the pair, thanks!

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Actually, please pull in `main`, CI should be back online again and I want to see that we didn't miss anything here

**Comment by SteveMacenski** [comment]
Docs approved, just need to have main pulled in to run CI and make sure nothing glaring is failing

**Comment by SteveMacenski** [comment]
> By the way, should we fix the failed tests?

Yes! I just haven't gotten to it yet. I only fixed CI with the Rolling transient issues on Friday. If you wanted to take a few moments to look over the system tests to see what's wrong, that would be greatly appreciated!

**Comment by alanxuefei** [comment]
> > By the way, should we fix the failed tests?
> 
> Yes! I just haven't gotten to it yet. I only fixed CI with the Rolling transient issues on Friday. If you wanted to take a few moments to look over the system tests to see what's wrong, that would be greatly appreciated! Only so many hours in the day unfortunately for myself :(


I'll try to fix some tests in my spare time. Thanks for the clarification. I thought that some failures might be due to the randomness inherent in the robotic algorithm. Unfortunately, or fortunately, everyone has only 24 hours in a day.

**Comment by SteveMacenski** [comment]
I actually fixed them already :-) 

The spin/backup tests are flaky and I've gone over and fixed and refixed them now a dozen times. I'm at really half a mind just to delete them and restart :laughing:

**Pull request merged**
