### PR TITLE
Patch codecov

### PR DESCRIPTION
**Pull request by ruffsl**
Looks like the `-R` root flag is implicitly the root of the repo, and the rest of the codecov pipeline has other assumptions that the script is executed within that same directory.
 
Fixes: https://github.com/ros-planning/navigation2/issues/2019

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I'm not sure how this managed to run all of CI in 7 minutes? But the links in codecov are really odd, they're private so I can't view them. Also codecov passes, but it should fail because it should be dropping coverage by about 4.5% due to tests no longer being covered

**Comment by ruffsl** [comment]
I think codecov login authentication is down. I can't login at all; I just get an empty page with this text:

```
upstream request timeout
```

**Comment by SteveMacenski** [comment]
Either way, it should not have passed, codecov should have failed if it dropped coverage %

**Comment by ruffsl** [comment]
> Either way, it should not have passed, codecov should have failed if it dropped coverage %

Yes, I know. But without being able to login, we can't check if it's actually using the yaml config file to filter, or if it thinks coverage has still increased given there still doesn't seem to be any coverage history for the main branch, e.g. x > 0%.

**Comment by ruffsl** [comment]
Looks like codecov is encountering a partial outage: https://status.codecov.io/incidents/2l81qhg5pr90

**Comment by ruffsl** [comment]
> Either way, it should not have passed, codecov should have failed if it dropped coverage %

Looks like codecov is working as intended, with both front and backend finding the `codecov.yml` file.

**Pull request merged**
