### PR TITLE
adding navigation2 new diagram

### PR DESCRIPTION
**Pull request by SteveMacenski**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #111  |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |

---

## Description of contribution in a few bullet points

* Diagram for navigation overview
* Adding to base readme
---

### CODE REVIEW

**Comment by crdelsey** [comment]
You've got the link between the recovery server and BT navigator as an action when it's really a service. It's also unnamed, unlike FP and CP, which seems a bit inconsistent.

**Comment by SteveMacenski** [comment]
> recovery server and BT navigator as an action when it's really a service

Those are actions. Its not named because each recovery hosts its own action server so that list long

**Comment by SteveMacenski** [comment]
@crdelsey is that right?

**Comment by mlherd** [comment]
@SteveMacenski I don't know what tool you used to create this diagram, but if there is any modifiable diagram file other than the png image, can you upload it  maybe somewhere in the docs?

**Comment by crdelsey** [comment]
> Those are actions. Its not named because each recovery hosts its own action server so that list long

Oh, yeah. That's right. I was thinking about ClearCostmap which is a service; forgot about spin and wait.

**Comment by SteveMacenski** [comment]
Its google drive so... no, not really

**Pull request merged**
