### PR TITLE
Add nav2_behavior_tree tests

### PR DESCRIPTION
**Pull request by naiveHobo**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #1810 |
| Primary OS tested on | Ubuntu 18.04 |
| Robotic platform tested on | TurtleBot3 Gazebo Simulation |

---

## Description of contribution in a few bullet points

* Improve `nav2_behavior_tree` test framework
* Add tests for `nav2_behavior_tree` plugins
* Added header files for behavior tree plugins

### CODE REVIEW

**Comment by naiveHobo** [comment]
@SteveMacenski I have started writing some tests for `nav2_behavior_tree` plugins, you can track the progress here.

**Comment by SteveMacenski** [comment]
Lets make sure to have bite sized PRs rather than having `N` new tests in 1 PR. I'd rather `N` PRs adding a test for each plugin so that reviewing is more practical

**Comment by naiveHobo** [comment]
Right, makes sense. Let's leave this PR for the header file addition that's needed for tests, then? I'll add the updated test framework and new tests on additional PRs.

**Comment by naiveHobo** [comment]
Actually, I'd rather leave this one as it is. This PR mainly just adds headers and some new changes in the testing framework, along with a test for `GoalReached` condition.

**Comment by naiveHobo** [comment]
I do see your concerns though, I just noticed it's 52 files changed already! I'll close this one and do about 3 plugins in the next PRs.

**Comment by SteveMacenski** [comment]
yeah, its 1,100 changes I need to look around at. Having just the file changes in 1 PR could be doable, I just wouldn't want all the file reformat **and** changes in the same PR. If there's no changes I can just glance at it. If there are changes, I have to be really vigilant

**Pull request closed without merging**
