### PR TITLE
nav2_ompl_planner plugin for Navigation2

### PR DESCRIPTION
**Pull request by shivaang12**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | #1646 |
| Primary OS tested on |  |
| Robotic platform tested on |  |

---

## Description of documentation updates required from your changes

---

### Roadmap
- [x] Add base code or boilerplate (0th draft)
- [x] Add basic implementation (1st darft)
- [ ] Work on feedback from the 1st draft
- [ ] Update dependency for ompl (eloquent or foxy release)
- [ ] Test on willogarage's map (Steve you know this!)
- [ ] Final touches
- [ ] Update documentation

## Feature tracker
- [ ] Take into account costmap
- [ ]  Create somewhat smoothish paths
- [ ] Take into account robot footprint
- [ ] Have some defensible use-case for addition
- [ ] Use OMPL/sampling-based planner best practices
- [X] Have a roadmap

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Closing PR since there's no content here. @shivaang12 what's your goal here? This is just boilerplate.

**Comment by shivaang12** [comment]
I am still working on this. I am currently experimenting before pushing changes so need some time.

**Comment by shivaang12** [comment]
@SteveMacenski I am wondering where would I find `double getFootprintcost(pose)` sort of functionality in Costmap2d? I looked around and it's looks like I have to create costmap_subscriber and footprint_subscriber, using them I have to create collision_checking object. Which I think would be overkill for offline collison checking.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/master/nav2_costmap_2d/src/collision_checker.cpp#L110

In the collision checker. You are right you have to make a new object, which I'm not a fan of. Optionally, make a new constructor using a footprint and a costmap so there's no subscribers (which should 100% be avoided). Look at DWB and see what it does for collision checking, since it will need to as well and that's not been refactored from the ROS1 APIs.

Push come to shove: I don't have a particular objection with having that logic in the state validity checker in the OMPL plugin. Though it should be a separate object we can merge into costmap 2d for use.

**Comment by shivaang12** [comment]
I think it would be efficient to port some changes rather than augmenting those in the planner.

I think at least this class would be much helpful for this operation

https://github.com/ros-planning/navigation/blob/9368db28b2d60e86ad1d55d4ae91b5f54a235a5c/base_local_planner/include/base_local_planner/costmap_model.h#L50

**Comment by SteveMacenski** [comment]
@shivaang12 can we close this PR and just link your branch in the ticket? There's not really a whole lot of reason to have this as a draft PR.

**Pull request closed without merging**
