### PR TITLE
Fixing system tests in CI

### PR DESCRIPTION
**Pull request by SteveMacenski**
#1475 #1341 Working through fixing the CI tests for system tests. This is going to probably be a long task but need to see how the workers react to changes. 

- [x] recoveries with 0% failure rate
- [x] action tests with 0% failure rate (but now reduced to ~25% and on a deterministic place in the last test). Failures are from https://github.com/ros2/rclcpp/issues/861, outside our scope as far as this PR is concerned.
- [x] system tests: planning
- [x] system tests: localization
- [x] system tests: bt nav with planners
- [x] system tests: bt nav with dynamic obj
- [x] system tests: multirobbot
- [x] system tests: updown
- [x] system tests: waypoint follower
- [x] crazy new linting for foxy
- [x] get CI to work with now functioning test suite

- [ ] CI working with planner system tests

All tests have a >90% success rate, except where mentioned above and an upstream documented issue. Per #1508, multirobot tests are too flaky for CI and it can be shown to work locally. I'm going to comment it out, while working, to speed up CI and increase liability as this is not a core feature.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
```
s.macenski@reese:~/Documents/nav/navigation2_ws$ colcon test 
Starting >>> nav2_common
Starting >>> nav_2d_msgs
Starting >>> nav2_gazebo_spawner
Finished <<< nav2_common [0.36s]                                                                         
Finished <<< nav_2d_msgs [0.35s]
Starting >>> nav2_msgs
Starting >>> nav2_voxel_grid
Starting >>> dwb_msgs
Finished <<< nav2_msgs [0.04s]                                                                                               
Starting >>> nav2_util
Finished <<< dwb_msgs [0.04s]
Finished <<< nav2_gazebo_spawner [1.20s]                                                                   
Finished <<< nav2_voxel_grid [2.21s]                                          
Finished <<< nav2_util [12.6s]             
Starting >>> nav_2d_utils
Starting >>> nav2_behavior_tree
Starting >>> nav2_lifecycle_manager
Starting >>> nav2_map_server
Starting >>> nav2_amcl
Starting >>> nav2_waypoint_follower                                                                                      
Finished <<< nav2_amcl [2.68s]                                                                                           
Finished <<< nav_2d_utils [3.10s]                                                                                        
Finished <<< nav2_lifecycle_manager [3.27s]                                                                                 
Starting >>> nav2_rviz_plugins
Finished <<< nav2_waypoint_follower [3.25s]
Finished <<< nav2_behavior_tree [3.83s]                                                                             
Starting >>> nav2_bt_navigator
Finished <<< nav2_rviz_plugins [2.39s]                                                                             
Finished <<< nav2_bt_navigator [2.38s]                                                  
Finished <<< nav2_map_server [10.0s]              
Starting >>> nav2_costmap_2d
Starting >>> slam_toolbox
Finished <<< slam_toolbox [0.17s]                                                  
Finished <<< nav2_costmap_2d [6.31s]             
Starting >>> nav2_core
Starting >>> costmap_queue
Starting >>> spatio_temporal_voxel_layer
Finished <<< spatio_temporal_voxel_layer [0.06s]                                                                   
Finished <<< nav2_core [1.86s]                                                
Starting >>> dwb_core
Starting >>> nav2_controller
Starting >>> nav2_navfn_planner
Starting >>> nav2_planner
Starting >>> nav2_recoveries
Finished <<< costmap_queue [2.11s]                                                                        
Finished <<< dwb_core [2.79s]                                                                                  
Starting >>> dwb_critics
Starting >>> dwb_plugins
Finished <<< nav2_controller [2.95s]                                                                               
Finished <<< nav2_planner [2.93s]
Finished <<< nav2_navfn_planner [3.46s]                                                                           
Finished <<< nav2_recoveries [4.33s]                                                                   
Finished <<< dwb_critics [2.59s]                                              
Finished <<< dwb_plugins [3.05s]             
Starting >>> nav2_dwb_controller
Finished <<< nav2_dwb_controller [0.06s]             
Starting >>> navigation2
Finished <<< navigation2 [0.09s]             
Starting >>> nav2_bringup
Finished <<< nav2_bringup [2.74s]             
Starting >>> nav2_system_tests
[Processing: nav2_system_tests]                          
[Processing: nav2_system_tests]                              
[Processing: nav2_system_tests]                               
[Processing: nav2_system_tests]                               
[Processing: nav2_system_tests]                               
[Processing: nav2_system_tests]                               
Finished <<< nav2_system_tests [3min 5s]                     

Summary: 31 packages finished [3min 46s]

```

Look at that beauty.

**Comment by SteveMacenski** [comment]
@shivaang12 I'm still working through fixing a test, but this branch fixes the `No trajectories...` error

**Comment by shivaang12** [comment]
Sounds good man. I've been trying since afternoon and couldn't find anything. Thanks for the hard work!

**Comment by SteveMacenski** [comment]
If you're so inclined to look at it too, that would be helpful. This is the last thing blocking CI / nightly builds from getting back to green. It clearly works functionally, so its something with the test itself...

**Comment by SteveMacenski** [comment]
Ticket #1512 discusses reenabling planner tests, I have disabled them so we can keep moving.

**Pull request merged**
