### PR TITLE
Clean .gcda files for invalidated package tests

### PR DESCRIPTION
**Pull request by ruffsl**
"Each time you run the program, the execution counts are summed into any existing .gcda files, so be sure to remove any old files if you do not want their contents to be included."
https://llvm.org/docs/CommandGuide/llvm-cov.html

Example:

<details>

```
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/test/CMakeFiles/test_node_utils.dir/test_node_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/odometry_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/node_thread.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/robot_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/lifecycle_node.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/lifecycle_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/string_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/lifecycle_service_client.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/node_utils.cpp.gcda:overwriting an existing profile data with a different timestamp
    libgcov profiling error:/opt/overlay_ws/build/nav2_util/src/CMakeFiles/nav2_util_core.dir/costmap.cpp.gcda:overwriting an existing profile data with a different timestamp
```

https://app.circleci.com/pipelines/github/ros-planning/navigation2/6480/workflows/e9f7aefe-808c-4465-bebb-d63c7136dade/jobs/23842

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Looks good - you may also want to add an exclusion for yourself here so mergify doesn't harass you as a maintainer https://github.com/ros-planning/navigation2/blob/main/.github/mergify.yml#L58

**Comment by SteveMacenski** [comment]
Wow, that might be the first codecoverage popup I've seen in a LONG time!

**Comment by ruffsl** [comment]
image

**Comment by SteveMacenski** [comment]
Next ROSCon talk, good meme :-)

**Pull request merged**
