### PR TITLE
Fix launch file to use the correct naming convention

### PR DESCRIPTION
**Pull request by crdelsey**
This allows tab completion to work when you run `ros2 launch`. The name should be `.` and then `launch.py` not `_`

### CODE REVIEW

**Comment by mkhansen-intel** [comment]
To me the fact that it won't tab complete without having the file name be *.launch.py is a bug in the auto-complete tool. I would like to understand why it can't complete to anything it finds that matches the given string like other tab completions do.

**Comment by crdelsey** [comment]
@mkhansen-intel I agree that not tab-completing against any file is kind of annoying, but I've run into this with other programs as well. I expect it is a misguided attempt to help the user, by filtering out all the non-launch files that start with the same letter.

**Comment by mkhansen-intel** [comment]
According to this thread, they were going to support the "_launch.py" convention in the tab completion:
https://discourse.ros.org/t/questioning-the-launch-py-file-extension/6352

**Comment by mkhansen-intel** [comment]
I submitted a PR in the launch_ros repo to fix it there:
https://github.com/ros2/launch_ros/pull/24

Hopefully that will get merged and we can close this one.

**Comment by mkhansen-intel** [comment]
My patch was merged, we shouldn't need this now. Closing.

**Pull request closed without merging**
