### PR TITLE
Use native library haltTree()

### PR DESCRIPTION
**Pull request by doisyg**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | Dexory Robot |

---

## Description of contribution in a few bullet points
As discussed, draft to open the discussion.

Update to use the the native cpp library `haltTree()`  method in `BehaviorTreeEngine::haltAllActions`.
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/61c55ed720e0630f211686b3830942ae27e90501/include/behaviortree_cpp_v3/bt_factory.h#L162-L179

Before this change, only the active BT node was halted when finishing the action. After this change, all BT nodes `halt()` methods are called. This is very convenient to handle cleaning operation (switch off your lights when leaving) in halt().

Also updated `nav2_behavior_tree::BtActionServer::haltTree()` to use the same. It is used nowhere in nav2 but is useful for external users (like me) that want for instance to halt the tree on preemption.

## Description of documentation updates required from your changes

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
I see no downside - why a draft?

**Comment by doisyg** [comment]
Switching to PR ;)

**Comment by doisyg** [comment]
I guess a note on the migration guide ?

**Comment by doisyg** [comment]
Docs: https://github.com/ros-planning/navigation.ros.org/pull/487

**Comment by SteveMacenski** [comment]
Honestly not sure if that was worth a migration guide doc since its not actionable to users, but I'll always default to more docs over less docs :wink:

**Pull request merged**
