### PR TITLE
Normalize navigate_to_pose action names to be snake cased.

### PR DESCRIPTION
**Pull request by hidmic**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | follow-up after https://github.com/ros-planning/navigation2/pull/1467 |
| Primary OS tested on | - |
| Robotic platform tested on | - |

**Note**: it took me a while to get this one up due to lack of time and because I repeatedly attempted and failed to run `nav2_system_tests` locally. I presume I'm not configuring my environment properly, but I didn't want to further delay this.

---

## Description of contribution in a few bullet points

* Normalize action names to be snake cased.

---

## Future work that may be required in bullet points

* I think the `navigate_to_pose` action isn't the only one that may require snake casing (e.g. see the [`FollowWaypoints` action](https://github.com/ros-planning/navigation2/blob/3c736f87dfcbba029e92f2f40de332073aba742a/nav2_waypoint_follower/src/waypoint_follower.cpp#L61)).

### CODE REVIEW

**Comment by SteveMacenski** [comment]
How did you test this?

I'd like to make sure this does all of the following:
- Using the Navigation2 "Go to pose" button, which under the hood calls the action server
- Using the RVIZ **default** "go to pose" button, which under the hood uses the topic, which covers the `/goal_pose` topic working.

You're, at a minimum, missing the `navigate_to_pose_action.cpp` call.

Make sure the following is no longer true:
```
mkhansen@mkhansen-desk:~/ros2_dev/navigation2_ws$ ros2 action info /NavigateToPose
Action: /NavigateToPose
Action clients: 0
Action servers: 1
    /bt_navigator
mkhansen@mkhansen-desk:~/ros2_dev/navigation2_ws$ ros2 action info /navigate_to_pose
Action: /navigate_to_pose
Action clients: 1
    /bt_navigator_client_node
Action servers: 0
```

**Comment by hidmic** [comment]
> How did you test this?

In no comprehensive way, really. I don't have a robot at hand to test, and `nav2` tests failed for me locally in a variety of different ways each time I attempted to move forward with this (not a lot of time to invest though). I'll try once again next week, probably clone everything from scratch and use the Dockerfile in the repo (I have my own containers for general ROS2 development, but to no avail).

I'll ping you back when that comes along. 

> You're, at a minimum, missing the `navigate_to_pose_action.cpp` call.

Interesting. I thought I had made sure to change the action name but not the behavior name. Something else's missing clearly.

**Comment by SteveMacenski** [comment]
Well, did you try it in simulation?

**Comment by adamsj-oci** [comment]
> Did you try it in simulation?

What is the preferred simulation environment for Nav2 testing?

**Comment by SteveMacenski** [comment]
Here is one option: https://ros-planning.github.io/navigation2/howtos/tutorials/docs/navigation2_with_turtlebot3_in_gazebo.html

**Comment by SteveMacenski** [comment]
Any movement here?

Also please rebase off master, I pushed a bunch of updates to fix CI.

**Comment by SteveMacenski** [comment]
It was tested by @ZakariaChekakta to work, @hidmic can you rebase to master so we can run CI and merge?

**Comment by hidmic** [comment]
@SteveMacenski my apologies for the delay, it's been a busy time. Will do and thank you @ZakariaChekakta!

**Comment by SteveMacenski** [comment]
mhm, there seems to be something wrong. All the integration tests are failing. I just reran, maybe just a fluke.

**Comment by SteveMacenski** [comment]
Last failure is upstream in rclcpp, merging

**Pull request merged**
